tssc-config:
    global-defaults:
        container-registries:
            registry.redhat.io:
                password: ENC[AES256_GCM,data:t/Y9uc4ElggNOsqfpngbBpaYmzwXSPEUvb1K/la/PWhlkp6Hndsyo+iHAdL91z7dQU5twDtmrIDMBVKvUBYz1DVlqWQnW2KneG5KkAjU+DMwFEJ/Wjd3jFOP+gVHMcl+fUokQjVxy0/O7hz2joTmUkF9Y9VrelSmGE2B0xoQZSOEExIENUSvoOmR8z23QqV0/Z2uoX3YOJ7w8lrh2Z/lBMoJXw6K2pkMoFJ9xlLWcCyluMBg4PM6w6M18pwk1Ltih8BRVOmGqyQ7Rdm2wPRcAnAxPpru/qVoXXLHykwoG5J6qXxP+WVjb87p+mfoY68VcgEX1DFz7WW+yw7/Suqcgic6eBW2IPutjZMafb0rCuHE9IyswwelyHA90sftSuZFVySBL0YL6FqnCo2+eDhFO4Kw7agDudALk6r2ccVbbFP9LAws92iO5rLJuY2PyPDghELsN6kMP9j7XVnBr7e6do8x0HOZebaVWy7ygCWeQ79yT6Aw/l3Ac6RXfzD2Wi0aJy877Z0+VwYdhs+64gETq0WVy+PDfMYDVFh5hQaTHd6c+5CD0Zr4WGbWp64CZ3AjZanJakQ/E1M3zJXaVfG1luCgqJPuVfJwlPy2k/A+Mq+DHQgae3hWXAClSaPVAjzfx+YHcB12xqhcBSElvsd/2Jsy6XlQIR/IzJCPZWf9DW+TJ8e27t1Xv7Usvo00YuQIIdHLQ6cXGHRHUckptr6eh/7DV2XtD4409VPB+KIvxc8Pr/gNwrfy1Fz1i/8hfqh5PjmgoeQmdd3r9dFbwWIDwJwuYZ4pkyvB6epj4c7flu0Sd/EZbTV0sZWoKp2oHn+CsJDSumrBpfP/OK0VejVMj4naqv63fUst3rW5j4tQZDpwc954zhSkV92U0pv2nYwi6OMBxJlYe/vpkQWR8Xj6/Eqo7rzM55IAuRxQW16A7/Qdv+Dd1Dv0cSm7y6bDAIdrPpXTbKBqLKvdaiOAtL+pRcL+p0VcsC7aTTQGGt+jA059Q1lsTNL14Jk=,iv:93KcZ3bxvwzE7O6nFFSs9vT7o6XpgoayrLu6dE5X7TE=,tag:7P8COKWpC6s8D6/VRaH5gw==,type:str]
            quay-quay-enterprise.apps.tssc.rht-set.com:
                password: ENC[AES256_GCM,data:dMK//3uGbG4FGOXH6RvJE1JOE0icSh2vGiVd//18Tz6Si0iqQhEeuidRWNLvkvw2I9KlFX5R2+m9+b7BvOhL8A==,iv:mR8l22fGvXhshcw7/xDIYpTulWSpYPWSj6RO3hmIgqk=,tag:1RduaxfYe91Kmv90kCUkPA==,type:str]
        maven-servers:
            internal-mirror:
                password: ENC[AES256_GCM,data:NYdwD3xTTMosFgcAdas0rMDT,iv:+RAq6DyV0SoIuZnl4FLs7RffTBXkX1epmimJFrPjd1I=,tag:58KEck9GLmB9pW5KryWXOg==,type:str]
    tag-source:
    -   implementer: Git
        config:
            password: ENC[AES256_GCM,data:wbIoAyxaTqSecoDm,iv:toZfJoC1YD0ITJLyNDMNfjNwmvGKen9uW4482EdHS+Y=,tag:32Dc5KfmltA9USSb85BS4w==,type:str]
    static-code-analysis:
    -   implementer: SonarQube
        config:
            password: ENC[AES256_GCM,data:SzmqYFtFd8TpW3Vhrq6emKtW,iv:8gQcDymaM1vEShKnqj+T5piN3WhD0o+hH0vsa9S+o3M=,tag:1Ejxo+z2T52l5XhZQ+ESiQ==,type:str]
    sign-container-image:
    -   implementer: PodmanSign
        config:
            container-image-signer-pgp-private-key: ENC[AES256_GCM,data:wWxlKXb/d2mMCMLtxY0d+ms8mvT4fvUpxl4XBxlCUiOxXCsWmyRPf4SQNLnAjeV0iW/lm6I5JeVFB/zoLtt3F3br9yEYsMuhV0lyVRJnlqeYmCQ+WbXKMuM4eQ3fW9ubUwcjhOKcInm8EbIRPsLgvEM30rFsOh2GgJw6GIHVws2O5YugXOoeHJmzi/hmnpY4PP2s62f5WyV5hrVHZzFcMhNjlDtcb1+mQZyl1vkF/mVZRXrjmBx2rMmjALW+GfmOCvrAEBscsNwW031NYCQIwGFnAOo7Td3KgsxYtv0WTLDkdiKYNHP34SjtLsFTDAC0UbuCO+BVq/0FSIMTMZIJy5FdTe/h3zyxp5Y5BWiGXoOwN3JyQJ3jpniexSE8Y+SXEARNDDMd7J2h8oTUOC29Hcd4l5/XvxsMBOtnKmpSP6cA8rnQ6EleJlTe3iadMkAfZlLOYSjyfKgxknTZHqkggwdxw1edsTOLVIKdv4TVxG/fDYFwF1SE490exWKXJEI+1r6+XMsoSmTUDA8mMg9r0MUE2h95HBQXfVgBTzWsB6Y/aW3F9yFy9tRs9G2YrnCEg8JAlSFW8LCypYR2ZS0SMdqvlsf7qvTgtnqQksVt3q0j8XiI3ahAQU+bfrYC639mjsSP+EV1mzAQBbvyIPqFLwTyXAe6QDOZtQrRBTcg+GzeT0z4Qh2kn58YKuYsv/eKpHuIoQeFvS8cQjnwR69ox+Eyjrnoxj8wVvs18keb9u123dYNRcJhrmgw0bbjmlVCYdORzTQLcUT9QCHTFbDbtC7DHwTGO48rW6WbEVJANrOqL46fYNWcbb7K1r0tmEGhZI/f3wIFEUizHANHsrJd3dZTaGcJ68am3HgdiUD5dlZnc2lbfG9ZPbNGj/FALzw4qL58a+8O2fAb1Eu4iI60fJtr287hVYQVF3E0/ATru/3isHW4PWOnV2PLNLDljzrqhvge7ovJ+SR05a4BOaGrHsoeqZQQYcx/2qYDisfQM1jk2TnFYel9C6LE6leOylHGrb98ZzglQMaPYgqzdWlVjvUu2uWt22BEu6C9cpsPq1Id7iP6YTuEq89ppeh2xBMY9SG7Yr71wPoU4lizPHryfWXiaPjxwup3BFOBSbUbyaEbf9jMsvYpdN+HE5esUJiX/bpbrGDTuitpNz0Y4FBzerI6twZRf5A8PEarPQPdx8Os4Dm0txJv9iucNihERCZibPPXs1rAlYofhphb1iHVHsFWZTPbvu0BgEu0mAxuIsNgZFmjh+XwiNZH28LUwA1ea8cNGh0nXtRfrhftC2RuoRfdVfoFrKjWAFMYfhg3tUvEGjmFCeAwi1Re+Xawd4YnKN3RG+RG9wClDr3m1OcGwoOSAFKhSYoWgpsI4PyO3B73ndWkAkBVbOUjRMnZrYP1ji9AtYUgyblBbhKCHkA6AlS0jwBnh95OJf4PzSrPufNy4tv0PhA1sB/rRc7/MBPy4ahjfPsMDDCsGiBRsqrNbvbbaEWImcVPW7jP7oF49Xm6KZNhcrCbu4ReOVFmgN0nMYJotLzlukq+602rauIMThqj2kSKQxn8idKsd/yiinUOXgVF8Yc8Gg4/5QMUARo1o5Fp/hshtIeCGjIenUI0yeqhq3B8bsm0+2lJd1ljLeI7qkiqmzP+WFY24/7/5gfOm6XpIPcsr4LGp7Lu3rEA5ecczAwO3jiXsMpNYLwXw6vWEnBoJIljbR6Rw2Bn8TBI8rKoPoDJakQ6PhNOt0ef9+Uph9N4GPD5DJFU/25Ueo8nnW6vfY1QltvjO+tp+UVoLEDOPFZDESLaHO/hDQ9dpYMEYYNOrL181kb4UtIbI8Di0C7VTVWsDF5lTlzvwguSw1zlJI39uNwbiEfyOLTALt6oVtV6w6iX2jPCp2hI/UD6vQk5YVrREwGaof5JbpTRM+CpZMu7BWYgSnEDE930wc86+03PkuiHql9S62SQtzB5mrPP6i7bvyh79nzeWGYdKt5FMUEgHVub1dQOp+Wn1q3HPZBZOrDb33bSzXXeR4Mn2N2YJ5b4k6fRLssuPHrat3YvclN6TiteT1n6qrIVz/ZsYFCK5HAD04JRjzCLuJFkUSPG+a1hIkMKXe3P+e/PFKqOSYScwRb/kidnOHQbnDH6xJa5p74g3LObsCipaGQuEaKu1mP0UxfA/IXm0xXForitFjD+8DL+TWNuP3/zXSh+97E0rVLd1vRVLt4LuQ4NWqSQ0pGp4vO9b/f9FtmJSKa5XOcDxlKB+LZIajGF00rjeb4XZoHvhAb4nGX03P66+BFiKNCdM19Xf1NPSS1M9YvOQH0Ft6wnxO00p5N+HSGL0jFDBBRX7W0t6AX4yCAIJX4bDanAfJA0ZQeK+HcVbAgHv3IZIPFLsj6RuVaE+My+T3fsHx8htgDOQXXePSSXCntrNHA9v9t6yDLsyKKi1i/o9YEVTLbVV4Z0q01AI3e53qvFtLUVmemKuFe+KSv/YaYIAb0+G7ihSinSjGyh8hH4/8eNgqBcCukBOTDBn/lU/hKrNwvFaFwQ0sH1yaKpdL5h6U9n+haUJt7MNaNFtPe5v1zvrIV1UgIBQax6RldIjT+rsiqRACPZfPhzUf0RAwAxJ1dIEeI21cp64ASKDKqFCrRorg2mKpjMVfai91RGJyAUx+bAYSCeWn5a/sB5ACSQZIQtCcc4l+g79lk5BOaEPIK3kXJPJnbNtLxqvDABXaIQxFxbNvZ+ksZbAvZiIxuW7aK25ZQ/AWzE+ouS7/JLKPzX4gB7D2zCxCHlFyHVOntWElMNPwo8W9WZ4JjIz0CweLUKAIlGYBn74WbRHlrQquWngZEPci8lNfx4rYLjpxIY1vpSr9P0BpADAuucznjlKjIg+S4QEZqCTcIeG7DX2iliWF8fhC6SUPe90TI9Q9PfEPn6klyOvIycIhEOaWJ01XMn1DLNd2DhMheGdXaLt919OcqI7PeGVX0+deiQ8YFuV6JrRup6PcKG2Z2c08/lWeJIRl3ePUR//i1NGg4s+Ucad08orHcTHzdNFAhuvwibckbyI3Ckr22qLwhXhnxZM8bnRweoHRFniHxPZjPoKSW6lVZ/wsHWZWq3Yzt+4mhmSb2TZLdkx+qz0bhVPkkHODVpNlfrOEpBIoj6MDZoNo3UgY191i29pfE6m5qcuAmZUOgqAXXnmPMspWfxai9k5H9e0zQThnPuJgFq+e2zPuMjVMRp7LTUvgNQ8RasJFk7UKaqgjAXDumFTGTcI+yJ7Dl5IPkBwTj+CYX9VmhyIqFWDsf/+W8NpCsXop440zVRyy7RGXON3d0c9vfvd/nzYyOzO6USKePdv8FDwTqR+F74DCGDffoIGslruZD+qhEsmwn8dccqEKqsTh4MXptMyz0AWIGRpYv6Z8eWmKaed/sxBmXDmC7ujx9xotVWVb/lNZOJPNiSDaZcg/1tCk06gEbXr+poFZbHJdOUelAXsRr3OmBtlICRkaPPJ14529ANa4mR3rDTFAgKAt3Ld9dxL/D3s83nsqQjrBbfeEFf5kCtFNwZzff6ZDd9JZ7Bo/eIxnhuGXCvSno9NEo+y001Nq2LDbd0qoACRplPmH0Iod8Edws3js+TTkHIu+66f7JOWkf6NO5AHLG8vmzPezs4XqfFO45m3KQLzcfoOqXsD9JXxSgnOrxB7tlJQn2Piu+3lpHpP5rfi2TgyILEmJ8mkOi9quZkWIVDt/tjTsjmVCCVkZGb2cPPIK/i9qJjH/D6mD8oJGlNKUSGDI0QDhotIzyniZ+8g2n0O70GgBUGjvXZ1jEGRnCalNE9BmY0YisPOPFAO0tW8HaUv4nmhlK936YsHTTXds/VsoDOtMMXJO7v6c25nXS/IoZQN/ja26pqAqecL9i7rV187qb9gQ39L0hgVv+6+yWcBiswdgB6KED72aS7RPK2/0tnlYUD7KH3DfuWAPcARN3LMaNqO0vck6xWxd9K0rzV3PIiQdnLktGB9NtPVLfLS3EKN272jLCH2ZZd0vjubN4UU4lekRQv0PFQ9S/RpHstJpTkysLQpVS1WLnKOLoBvkxj5TkjmhEtiJd+E4YbRWxP1Z8F2FzJHMPPdL09wAd77VLGgscDzupjRWn/J09J3YkETNIrAWooecPM/NVIyHxbgiVSNvsQszpA+kSYGvcWVtgY2TENIJXA6zSfUSlJ0aO8gIkTT2F++bxYu4b9jO0s24puSWaJtFThEVRXw4UY9kGfGHZkaI9ZCo1JqNDzwnrnC1SG9n0ALUa2m98qLEU4XTTIP8d3cDx/13c1UW9jbMwQZt9yitLS/LIBsdJCXTZ7rQeds0J+7Rh2+B9HqJZPKk9qGs+aUlEBlz5SUsQFu8tU5EGqvYq7XJ7b+kU37Po4vLDTU4Qmf5SnGNDs2kidjGIQuncI9bjhfuszdSc3w0e0Y+qfzET+Rx+71sxYcfZNTnamrluBkDoa3GHJI7xhJOhTHNGCCi0uSQTjrNqfyp9hS4/1p3nTIotR1iDbbezsKl1glVw+x5Tj8OSR88diDjt6gJ/eJYDdKh1ZPRrU8bpMEMfFQbKKtXHrGe1feqmHHGNgmliopnMecdkpQNh8TCvtAgQq8QoAMqq+Pk/dULZStDG/kBWgeMHQr6Qb1IzYcq4N/51dJQB89kzwxQQf3YCIAf1y/JlcnAiyWbmhySe2blgn6oUCfDicoboPUWEy8nqCqXFXdAG/2yoFqHzFk20pD+AKM9u31txfXjBl/R2VoiZFmT+425Rrh3PGzh8XzH7eFs2lftWay3TbdeoaWxiVzwEFcYWErGT+1vwhWUsTtc7eD0vEcAmIwAVLCXs7bYVDh7jQRQBH4uV340L7PeBCoe3gfW5FrIzI0GGP4vkWvtcCAnhulqnDHbGvXKgy3INPA+0lg8fQ7jVIoO+vEDWXfbijPrSRes2teG6rna3HR+Qvd/SqcyRbSKYUHfWpgp0iBiDkwujeINMPrFEAYBLUlSapeNnFwUyk+A8e5X96S9tb7IxP7V+bP7nuEmfyFDzuESgQj4FrOpI16V3hnMqWaFig+x624sRXnzsYVWvyHzu6MmetPYSTwyJLFYTa9TewpejcvVNVNvEJvBEHFgNx9nZABQFdkboW4MGu93mS/DCIR29psN9dx9vF8FlhofyPg2rgtk/t/kbTye3vE9u380rpwU5LBQ7OPqbwbz7eXNdOf5eoWOgtU6mbDcJ24mIYHFUZdopuerXaOJl/mrCltbtIJUOLWAFVI1TrzWLvJmT2x5MhmkkQdv5PS4le5blq956SuFGmTGR42oooseDSAypEorWGUVtlsDYU2x7gKfco+x1ixhRpiUxm+64Mry+lcQeM6q0avJMFIK658omQgP4q0fbkKkCLgxtpTn3Zz9UmAMgybwK/nhv7Her4+b3L7fn4mt4zhQlFgqswfoYF6laN5AEEoyTj0guUdAlMvYVF47T57gOkFKRZqkJh+IUaJ1WxdGkCcEDMawdHR6K9x9YxCuZHKSp19HKFqzMvtGHWp+3zfb1xRONo2NiMR5I6YtKGEytqVbCxf14+3ZWOQayz6rtUR5gIOF97HvdmTyGlU/2kO9Aqr2riIy7VeJc5PSBg0zsSiaIz57IKDXKTklImvJ9F/r9np0cLIdK9nfiSkURHuP89OlFngriLCbXSv9GqB5dZTNsaswq+du6bPpsh9LmZF8j7R7OyS2mhvIZGgtKmWcSVvC7TlAlo1QF9iMzHtNQWi7ZpaMd3wHD2qI3S+mXGqqMeQcPLQvhYsROs0nW/weIMSnFDEmjuk7QyBbQnN9SBaOG2/PqIpWiyd7mIMbeSF5VVlu1po7Lz0HThTZL/YGMSf4/2bP0E12pISia6J1/bKqVhmt1ZsuYRSyTj0/jUzTpUmFeDtxYXq4EpQf6hXxbZuZ5n6mMda7hkePWpmQn6vCtrFwNy0RFtytTWIW4vHka9weu1jUjs6SS2ByXswjZyu7KLkHEbA+ocQd1AYo9slaEKVKFuO0/r5oRcpnHETiKxKByVdF/t9aA4j7ymBe16XEhsDnvwxvoe34/eFUsZEo8b7Y1UTQ/6aMR+wNJHfVIDvbXeKgnit8/4Vgw6vcgM02IWA2ZfN4weH+THOEO7sdPshT+n6+ofVrn04D0yqi2JHxJOAuO/rmgMbUe7TkAEdYLa3Z8Axtf7J48AAeQAm061rgaFxZIawGNyqXjUUpb7YmBFuDS8OZxVJOumFrkPSIUqwiNjQHSEc0nx6vJgzriF8ur0epm6l8QP5+lBrpUbvs8upg4kt0yfCxM/yBtqWg+urP+9sPoYDUT8959FL5NMICZC4KZT0ZLnFMMAQV3ixJPgOv724MD4xAuL2H957aAMKxbgELnzQJT7rK8jAh8NNVlRCJhcH6VUDOe2XDc4Hi3S9hBh1wvWi7UVKfrusARnWmqQA64dkZX1Iiv9D4xYdAgztI3n6ouORN0VpYJpZkUuQZzk5rKw7CSN3ZS61WecTzsH4BZhRcnMqHGZZqvCOzVjFiXX2+qQdr5+g5Rbgx4v7dD8qpom7S96e+pJvmgAbwfMkWZFmO2ovklQZiz4Zcbb9u/9kVwRQ2m+1yIJf99NkT5hWpz9taNzzrp36UTPnIXoceYXlogtIlgKuh4IBEOFu3u9Lu6eFSjlRYyF4mato0DeAxUNnqXR5QlN836OOMBf/luFCyTeYPBU9y7UR2DjEyB1dR+wUXAwmcMFh36jyMKknjMxm6Y1lxXvniWPTsVakmz/v6xv7IHUkROCTi4sCHkBDB4X3HLGnFHNjz0pzV2WctbNmTuVSpebwt400CPaKPpQr1uNI4v7FEGDwm7/+ODAaK1/YpKL2/3kpz4BvEtQ5kOU,iv:IkndBZGFhYx8io6AsN30HAvrjoYRcLAf6V7tDlFy/1E=,tag:L/RG2DbouWGS42v4pnEQRw==,type:str]
    -   implementer: CurlPush
        config:
            sigserver-password: ENC[AES256_GCM,data:vktIszS3S9j79OAubDbi8CPb,iv:MlG/uy2CPdT92ey08s7MEWeomFRQF8MFQYMgDggbw8I=,tag:8Xn8RoWNcWGoxBKewtdroQ==,type:str]
    deploy:
    -   implementer: ArgoCD
        config:
            git-password: ENC[AES256_GCM,data:qC7MnBIWQcmYqf+B,iv:SLrnc2qH2P6n4hhEIOh5XC3MyX7wxuUswHMvSJglVq8=,tag:wjBwALAQhvgLioELPXU5KQ==,type:str]
            argocd-password: ENC[AES256_GCM,data:4V1dcfYd,iv:th7hP+6NseHk27537wS98XBe/kQta1m2jnnxHcHozHg=,tag:9Ag+brIxdkiXeFdeK2EMzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-10-01T16:43:18Z'
    mac: ENC[AES256_GCM,data:oNzzSxuqkSEmNgh38iKjpy1k/+dM76ygQh6bd/bpkyotakxpfr+6iczCvn+tCh/kEtLWnsvXOSQADIa78IuJjmKClXp3l6Kv6hJ8qGoCMw5iBCN8AAnojmZfZcUEL95Bmz2NWZZ9pkeExJ4+clkqnQ6tTTyy9BRYo2ZT4luoFW8=,iv:HeobDftVI/0sZYXevNvjSMP3+y4fxWKkhg4zVASqZ40=,tag:P4dTWU8J2EwXYvXja8lS0Q==,type:str]
    pgp:
    -   created_at: '2020-09-28T12:23:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQgAvwSrqVOFtdczzC94Th05/FZ2K3mRCYcNwvzEi/a6jsCb
            RbADeah2USzSD6Yqb6vlc4Ehlgz7HdKf5tn6R3gufg+0HJ16V5Ic48EpXNA4RPZR
            vebZG1xdPHQo/cMOSmpfg8Z/IaguSlS+I36W1WO4D8F9LoPkmHKSbT897piYbaim
            iWUHouG5PFwZuObvHtM/35GwMfS4Ui0FdZE+wCWvbVJcM59cokS/KX0Hn9JceJn3
            AlCBtlFiMX5BtyLIjRIECo88/AoOLJsV1jXBfEI8hM2AzShCD37t1Odw35n0fOUy
            XxW70B/C1Mzzi8XY+rPqYG5Q1tgIaHieRUDe+ugOzNJcARUeifr/2GdHAvUD1gJo
            A9vS1hsEqLW+nNq79tP2L/AgKWgI9+MWCCAJXcpPTi7FHqSghD54xsu6RNlFSlgP
            2dKWwENNjo3Bqk1RWmQLDb01OQLUOGjA1KPxASw=
            =CpQ6
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T12:28:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/pHJVB+8SuwAQ/+Ly5wpkc2FfY0YR0i/ROoFgBRbz+4D4qSN/qkG4zRHg3R
            KKI67wKlXb7ycsHtWPnn0qK9cWkX9+m2263w2yYt6wpbJrtBqRAxmPPbQn9n1+/9
            ISdGTtUhTC02Pyh2r2crWn8dBUAd4SMGC82IKzHtBxv4r149/qgLNu+2udjSkqsL
            sNrZJHIahvlrl+F96YmJh2XhIH80lIGvPXNKo/bv8ed2ICT6juVrRscEblAH5/6T
            LleD1dHLtW1DIBoCmY40K1qsM0vwN5lMcvOtoVSirU1cLYOrKvj3i19Y7wJLrVk4
            /mR8VLpYwz0e794qV6TxvM5gGFvs7mzqJ9fnBx+ngClManmJKaHituCQNASFXGK9
            KaBMSTcfV7QnOtcMDR/Op6tmE1wc5tw06V+vqJtTfY/mlvpHzGxqT1zoKIPZuV7Y
            SJR9WPtw52mwEh2xI9Ifyuyf5QKS2aB2QeJlAWuWsZHUnIGuKsPKbgo7DYRf4aJy
            V76SqPqJoZl+WdHNvOpwlfsiz1RqUDDsn4jUNC5V4TzHLXQcsUwuXS1+QZ+xKlZ4
            gfHl4wQYxWsxA10PdyNT00Jx101JAY1WeOsoB+sTUQlDgvAEZGhqlvtz7lfr4+qL
            P5EOzzF38k5WBvtKmDTKzxSDyeAuQj6wIVuYSnm9db5AIWPwYd51vovkJFnZwgbS
            XAHbliGg5XQPunRxzVwY2iKbWnYrfZIC6c5Iv5cPvr+rB6+9G42Ub+QN/4A6wi7O
            d4WlrtG3iuRcXXlCEJxpdfJ8KBa/WGadhKX4r7we7J4KUG5/raYh/EL3OQxl
            =+rXp
            -----END PGP MESSAGE-----
        fp: 355C11B55E83B15E5CF6366283637FAF9D7905E1
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/JEnAHZDjB7AQf+NZXpmQ7+qFvEceY/KsAOwKFru9wBkY74S4E65+fVTtWQ
            tTlVTwtmczkOsxfVGJPQuXSOS48JlB+c526Rn2mank2gqgfs3BVP2icsh63RtmTp
            BtHEnlm0Vm15SZ9d28z5jolcWdIzQ4a7d/BAGDgIIeqWotziqasQilrvagTrXa0f
            mRS1AtAzZytauMD822VdLEe92DIpAlaEa0auO/Vac8R2bcQLIQQols/1tlReighL
            tz7YVVAMpOj5a2CpnzgdvbZ6w5WefHfUkutGxuKELiP4rpRHtHZRhlloquGNO99B
            +KcihMt/6dfNIx1MJIKsvuhHE9XZtHynjWHgmapO6tJcAaYpIatU/AqSKPSi+UOM
            V0UbaOUyK1mYAK+Rh8MTQipnJUE6zWiV23EdOKYwWYQmTbfQGDAohLORvl6O7l/e
            HlcqNBkaNX9Seo5WWgfY0FbMdKDj3saiLXbDQ+4=
            =fdkC
            -----END PGP MESSAGE-----
        fp: 2A25DA15018235A6206921952730D7A70EC35190
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6220UozeaaQARAAtk/9evlCxWCDbfKg4m6z1HITc5g1cXBA202UPegZp/y+
            CBSbd8YOGztbL9HY8qzymLwKBYyxouPylTT4+vPfOeSy9Y+p7dUYVUuJx+QVDwTm
            auJsLkMFzPsX5POQuccCYvdLjO8GfjL3K6hrB7SRMbecROYt924pA1cREUg4T4jr
            ERqUsTDtbE5iuD9aM39meVPRQelquo+Y9EjO6A19tRXF8Wfm8YkT8fCiuzvytdhL
            5slQm38yL1k3FfOOjG4QsSwifCYvlL8ki9wmbGt/hRZB6kruSf843d7YMNCLhf+u
            MboJI/E2ikA1lK+oGc4T31pBkS2nAb2rTK21HAeSfXQ+Wj+H5cCSMU8x6omdpK2q
            Mo6ri0qbyeNWcH0lKnfYvPAE1d0fsaRQ5mC19Sf9yV7y/i1SRVfHWQyhN6ZQpawM
            kklLgvpHsnWUk56uDlEoUF+knbXoatcNUzia5/hyFychmusYZRw1Uuv0MoU1TmhL
            gza8zl9+RFZ61oyBBnQnUPY+vwcLv+FbDreAurRuoILAHjv2qi3uGQ6LgpxeOGuK
            cTc/0TlqFjDsiFasMJYT+wekgpzC1C/kPp3uXCTxsgFwrF4ZtDCIEjowJGIrcu+N
            /L1u6ykCSgdM9fDqZL30a9YP7Ce8lwVkSlKJu2fJkyFAUfrFhfQji1R+zUoF2kbS
            XAF0yQCmhWtiTdmNzVE9PDYVP+G35nb4fuC2No2cJSbERc4zoYEF5lRUkMk1xCCT
            s+PQzg21YG3OjBqYEJvtlIAkQ5IhQ5kCvSm9KdBz6QKyarvZYY5Dmp85Zhb7
            =GAVa
            -----END PGP MESSAGE-----
        fp: DA7B00C8ACAFED2DA7E33D1ADFA8C968E1F69B13
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx6ne7Mq17RmAQ//UMJ+8lKN5/A53KHHI8PwMoEc2UaEYfTlsqcXeQ0SMXe3
            T5I2HPaJkf9bAisUnvKMBJpBBoEJLrhx7dX1bGnBt9iFRD0fJ6Aylf3kWyC9l/N4
            PyxJRybZiKbYJ/R9qUZIEWUczeUV4tXhEzbhfLZSbpGvpOwtlphZizh1pUwZeFHM
            fuT+t1/mLR7TbRPQKQTe25kivAhtN/7cH5tghn5zjPPcNxWJ2hu9A+2KdBB89QT0
            Qf3N9irDeRz0k+FwF8OKifSN75RodSQk3fnGX4pBp/HpEHbVGSQdAKYPVpIJbZBg
            6ZJ/2oV+ywoCSOwgwUbIsfCFG5TAApEvX3hqk10GOlpA9eHpFVNWbuhZIA9EcIvg
            YB+utHINrCjBF25f+YoMGnh3M0gnUQMZB3pr7PTuXl99AkeitqwPNIH1fsObvomZ
            sxkeZGVOiQc+UTXOEoGcii1AE5SgfUMgY9Z9YJudRSrjQobAbtV81YLHDUbJLfhb
            1fVsBnOMhzfnseCRj9JCmbo9XZsTDU8bKUK0QYdqqRcxtEXmwnwcW2FGxVayDedZ
            0FMt8WAODoEkgqqvpFo8K5SutUfn78DrJtyy002u2X4wT6/63dX4h68+Zxc64N5N
            cVdyo4zrjbq8OxkEjUnA7nF9ek+p64yWex+n2Q5QLgZpFINYHNb9ACmKnRJ86CrS
            XAH6NMKEifsdQek2bXbypftQ85lAETZO+ccJ44XRM55fFDSNSTlRTZqhMy1ti3Xg
            dWH2QG6q9yIMg6GWNGGqnDQlFmPaXGrPWZNBOhO68QHCMHlWPwmg/Ju2Z7Us
            =jH4K
            -----END PGP MESSAGE-----
        fp: 911B366FD384B2CF3BCAE8EE01F9B7BD00DCD57B
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75NWiDtWcDHAQ/+KUB1bOmmsrbSbp3DELlvQGpCLlx86mtMgvQjHG9iKrv6
            qc+/J+RYmJpw0XpLjoZyA6Bcy9avEeedd/UEJ+0zItbQsZwwnVZ+p+zPD0BW93ws
            xUjqdBNd+jVk8DQSd5ztP9AKt7Dou0mQuNKIFXmYKqw2Cs5DKWt2JjMcjcCqckpt
            lALRdapTQAXCkKVUtJJ7uz76jhMmwNekch6ZZTojN0O/Wf9WHDYay37BYb7KYijo
            4We7/JyBIL3MKm9Z4o6FCRfsV2MqI0t3FesNK0HqhcpyzZs4lWT/YV6WW+23zAeZ
            uwIJ/iF3pHpqB+NylgPZj7qbssprrlSEYBlB6V4yHmv8GvsR6VK3dGPVgi+JtkDq
            sChiXnAEIH6XLS34G/bPPJsZOB5vQ42h+RcK3opplrbPHyFsyagELGzxNso2Z5dv
            L/iGbEjqQucOmb83PJINCA7nweXpXR4SNXP/c9Si3p2sl7IxMLs2tzmwm508uwFa
            NgewXgM/2BjDhPCv6tfad8Dnx1DBegpJQr/KrWYwTJh+JWoHrzxkGDAV6EnsxQ5G
            MT8Phg812Z7Z+ro65YBYoqEPOz3zpFFc9ca1DeWcgZXGuwGUUeaGOoamwVSFgNCG
            t55ZuwFAt7ISj/j22/Irxp5pw8Ukx5/4AKafDOk4o/OTDrdIf+sYAZeRT764sufS
            XAGUVC1yhI2fswv4k2EQI3URDUIFAMAa1q1CP4DXXD5DOqkqP7kt9ysyrsJgwaml
            mTSjrr5gtpPy00ugxVBcOeXpiFEQXJ7maxxr9UsMCVNBRtG9yn/YFyaMf+/K
            =qdR8
            -----END PGP MESSAGE-----
        fp: 4A4B9A8F518CD36766AF86DE065BDAD92D70F679
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/haI43zIlNcAQwAiQNR2nmi9q/7gnkaMFWN4qsvSr5EAS2ZGRrLRVygk5Yy
            OF0U1jpKrg6K86ffVeT7McEHXQSONAJOPmWGyeNQeuz5GxvhKMCIzjr5/b+/0rfq
            kiB4dn11GSZRTNUu/oWZ87wdG8jDoZiX8WEYS3kKXRWX847QSBcT4ndVGVe92vGF
            pOddZV/TgkORyW/inthIfFwPwChylDdKENBZbtD0VFK10vutVyMuZ5ygaAUrwVBm
            QWE4CFuDuWp2jnGsr6p8VkGgl3s3+9H4T3LyZLBWU5AaaKNBj+D+aUT/ZwJcgub7
            KMsjvR7SXEe08rQlTPkLR1BshnURER+a5vhEIDgMKvEzS9pF1/lDi1lU3arZzS8v
            7yGAyYlSu2hnIXglfcTXIh5ODODcglhjWYAfAuvrjXcP68quQjGoU7IQ4T5Fhey8
            m6CtaeD42Kma+1sQG6tagLOa0yWaJ6md90/j106fTQH3gNtZL3X9BAavG43xqSJ/
            VohgSJdSmr5IbrJIT+M90lwBpTUeMf5NPrtM4Hk6zNL7kN1fF1TvglCcs/jDAp9K
            GcLZWHb3q4UTrW+cIE+oR43DAaYfyX/I4h+rtNdWblqmCGehmAWXGWfA8qgpdkeE
            KEBblEvcXavdRR6FiQ==
            =nZ/H
            -----END PGP MESSAGE-----
        fp: 6B9CB4956CDDD0599A518BA6CFF195C6AE9E4939
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQf9ELqvJ2QwKKphBJvISs0gMu1Q7IcUtJe3VuQEi1zmOqxr
            zoiGrH5ZAuiIveuTiGyBy5jx3MFCka/LVhVg6G7d7Z3rrzaend8YIIchDGyV1lyR
            YTcVnabliH0VtC4Npdn6l0yZ/qqnYin1xYCHkelOpBZixLp63ENBbWZjD27E8KA0
            YVle7l9jlHQX4I6MQKFGn7+nrJqbg/3yOSRGbowxXbg+8lOddILnYuLrzjddzT9+
            QTrWzayup4PTvvYTjs+79XGPycTNQKKdqB7JztP1jfRLUkQoJOwJpAshCtyqw4hn
            gS6PWK6jhp4/OTwHEd6ONkMT/IxLdhd6i9ilSmf8SdJcAVuaDT5TPTZkrpYbGjdG
            fXQ1FyGQYGZwp/iQO7jN0dHOKJeRRhqx7Z9R2iu+k2Vmb5P3Ak/RpersjIjUB7jd
            ptfHiTyNpYJxKtSYHJOaTl5sz0isv75zFHKICSI=
            =OmbY
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T13:51:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0ZhTnV170YBAQwAppJyTyCfrzDFwrZneEEZbT2PVxt63/jMgrVbsCZKPpb7
            84o7E/JQ8uRBCxA0mtAUQWjLL57h1IU8RoIJH0Qgv0o0futoAOM1RIEjLePUXshy
            aoIV3D9DcfAtAtW4DZBioa7DPOiAlXALigaplxLF+2vu5r+VdmEtCakJ7XgsVo+e
            /OrMm3eOvCfpVcYOoa82Q/B9kbxo6JsGnnlz/WdmiGKTr3ItnV2RqHWR09PtRIeG
            x1edMRTIZANXk41APZNMT3Oc4tZEqWOXfRcxbZVOduuUIej0nLhLrGj2KUVJxlBk
            vqfaEDt8U22Si+OTjF0JU53z1ZtEQrxnQzABHDTVUWuK6IatvH2An/ugxYz5yBev
            jBo5s+OVYNSEJaAPDch214084g0gRjL1sXSqvaP3pQWWzai1ZzOSbfgcVLwrOj0F
            QaS99We6+pstnHke7PcvK1Q100gIY3pIIZJURD7zLPBChE2PxpkLB92MFh5uddFH
            d2PdoSbO72PiWqdF+3tt0lwBfL9q5p/sWkgAIFZa+z58H+vkXP8TEDL4In/aDIOl
            D1QLlhZJkiNTSiXyiEev9ssXlJEE8WGn1mHe66DiFEdb5fWssfXrQfiHTbIV/FUe
            AW4pkl5L5U7TfRAbnQ==
            =qD9M
            -----END PGP MESSAGE-----
        fp: CC69D686B0FCFF3B5C2147AD8AFEC23AB1EB36A3
    unencrypted_regex: ^(implementer)$
    version: 3.6.1
