tssc-config:
    global-defaults:
        container-registries:
            registry.redhat.io:
                password: ENC[AES256_GCM,data:fdcxva/PHsgfJiCgAPU4IO27oQpBSSZJow9cV4GdEpO5zlJpNABHTH3p3l9AeowICU8l0AlgThYcTz9SVWNsTijsCJZ/H5VkYX4htqcvSBQdPo3l2SgdaGYIPhl0orfL5kuod+RGXQX62eEcCMX41CsBLEQtdKnp+RMhQc/huC4KC5v1Mjic6tVWS8FO7XX2uFIDdlQpacyq6fTKQAtNeMuVPK6GfnkZWQhmh5uaPyAg+OirJSqXSEnnIOIgjR4Ky2mfN71TAwjh1LhJ82aG5NzTp9Y1oofhFUmxHw8qvN4bJRYYSsgaSDb1nKav8oiUG/R/eYQis+YBra1rBfci1WeM2WIzAEejE8zyqrtzP4gGAa0uVtGsgMpOGa+xtJVkL6/Fk/GoDgpfDCpfuGo1Du6SbZ2EUz24/BaPAB/3k4LYg8YLvQZLPttyfzSSgKQ1OLaPKCRuh/J+dSPy725Fm1R4EhaQ+HQo2XyUhAHQa59FYhDOrs2skA+3/u//1TOrrmxn4lskkORmh/N3Fysq/SWvVGSSV/1fdchPEuka4j2BtIebsgDHPNysdu21sxWUCB5ZWoB3xz5vWe6R8S4pDbDwbnuxWRUHn4QjYMyLOCZScuy8KvFpYOmpPz44xngNyEccE59STaJVtejvA2F+lyW5UoIDpdJTpQFzuy4Y+LAq/YnQtTMft/YSi/fm4RkgCRHToQzOuAS4Z2qaiBdvHOy5823B1H1m6CAV7vYmR/iJhyifB88lsoWCETqH0ksnAZF00WhvC7feMJkhcCn15cxTy6dPDM0/OEFP7LyccvaiPQnvLwB9IyywYj8QkAF4Q5I13whU15maDrDxFiKMDxDAbsSGSWPmnekjfVpp4qwx0MyvYz+5HYuKDScXhWDYPb1l3xZLMlz5mvBsoQYAF7iYp/w3sdXle2p7gyR1fX5GKXbx1R5A2K3ND2pnkBELDEMBhkXV1DF2yv2z3K88NVJrTmOYC0NAL/soGTUjW6IgpvIYbbcXoBY=,iv:93KcZ3bxvwzE7O6nFFSs9vT7o6XpgoayrLu6dE5X7TE=,tag:XXyr+e/xmF/sMSU2TRKzwQ==,type:str]
            quay-quay-enterprise.apps.tssc.rht-set.com:
                password: ENC[AES256_GCM,data:uDz/xv4Po2KjzfA9BTNk75jvdPWaR/6KDAEUPc7IluidQSprRrKyHDj47pcsX2BhWfY79ieZnzsV0/MHnM93mw==,iv:mR8l22fGvXhshcw7/xDIYpTulWSpYPWSj6RO3hmIgqk=,tag:jld7YIWl86dF3bnsEDIGdA==,type:str]
        maven-servers:
            internal-mirror:
                password: ENC[AES256_GCM,data:4MOhuU4T8X9129D4PKCLJn4N,iv:+RAq6DyV0SoIuZnl4FLs7RffTBXkX1epmimJFrPjd1I=,tag:5reYtJbv4DsCZ9QrtfJfZA==,type:str]
    tag-source:
    -   implementer: Git
        config:
            password: ENC[AES256_GCM,data:L1yxgFxEnFD7mUx+,iv:toZfJoC1YD0ITJLyNDMNfjNwmvGKen9uW4482EdHS+Y=,tag:6rud68YW8T+dUlBBfgcdYQ==,type:str]
    static-code-analysis:
    -   implementer: SonarQube
        config:
            password: ENC[AES256_GCM,data:UrGaZgd6IlsYbFMUNRMG5Coh,iv:8gQcDymaM1vEShKnqj+T5piN3WhD0o+hH0vsa9S+o3M=,tag:a81ifoTi0N6wYlJPpDO4xw==,type:str]
    deploy:
    -   implementer: ArgoCD
        config:
            git-password: ENC[AES256_GCM,data:asr/slMxZTCL20ud,iv:SLrnc2qH2P6n4hhEIOh5XC3MyX7wxuUswHMvSJglVq8=,tag:XTVCkU2QCaXngafV4okWsQ==,type:str]
            argocd-password: ENC[AES256_GCM,data:DP7VXpSJ,iv:th7hP+6NseHk27537wS98XBe/kQta1m2jnnxHcHozHg=,tag:6sO2j/OrxVmNhxUiD/E2uA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-30T21:37:23Z'
    mac: ENC[AES256_GCM,data:GOdZLDR0UkEvS5xLalf6SzCWMjNxuRoCa5nFEM8ASQHXuTh/aK4Phky3Ft3XtnVcO1ZZBVEFfEU5OksMBZYfLz9/2HuWgb4RXGA2LyyoU9n96m25mNF9kV4PhD66pwM0OsUJyVHX/tEHZh78QOdcOI5ctp68zQOugwHtxvP0joY=,iv:YJIlIwWKpabyHh94/aQRiD2xiBSE4bbNje28QZJbrs8=,tag:qY1lynCAw1sI68S9yqo9PA==,type:str]
    pgp:
    -   created_at: '2020-09-28T12:23:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQf9EDpje95sE67/BxQ6/2iM9CLJmOQOCP+olmm9vlJvZh6f
            rT9Sa+D8t5gwr1OFwlY6UNq/h71g/+OXXkEtw67GatiHNUN68cS50pGhzZIUSwZd
            kZUfnHu9uNid6WIMVrYPXEo9MqUow2mNzteseBFSKRmPNZ7Mzq5UxSeu4IF7ktTy
            NrzRyonYslns7L/p1BZWFA8BIHPLewP+77PUqBKzstetDsgARqbIy73+bvktPOxp
            NLgPzDILkQqKhOuaB+IRkDnkrf/zq3CpqO3O6ldPH2dt+es52cLnrr4YcndpIlQN
            ecz8coS3+RAkb6WCvHwTDxIFnMLayDn7OaDbeVJuItJcAT3P1pr4TVfElDUoPN0C
            HnHgHP0dsURScB7VrJifikEnFovpt5yhe86Ry7FC3+tFMO7JIKZtO6IB6aPc5Yi6
            gBuKwVwdaNPaa6xkBPVHHikVRHsR9wWpn66dzpo=
            =Bxbq
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T12:28:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/pHJVB+8SuwAQ//X0VYPD/8+rIs2E4KFUyvJw3DmDdXRiFdZuMDEKD1quEn
            BJ5HdhUkOVvp2qIFWHKe2y5LERPWvxFlRxGXHq9BWr1I5+EkryPVaOk4kqFXCGdm
            6MfF/7nJ15rLxxADpQUjy+Jx5Ve0taLNcy6CC7lescgyY2qeD8DwsUi+3Xt6EP15
            RHnH+g2e1zI8xxGppwQsRKcnBM4g1WYEqUWrpIlqesX2BL9NToiizhtlLtoTcX3d
            U1a70zYnGeUOBJ+Mn395X9qRqrR8g+Vlcu7pHX72CWtQ5t3X3+VdJobSzE1SWjRe
            MGY6jSbkvaTMeDDZTajvFGzCujC2SWgV4kWmarVw6H+FPYLhnuCOd15aLSbGSsKi
            xIjbLrOVrcgxRnUyxO8IXXVolqLoaTRVt92ZVdlLgKlBXlISscjhw5OELCU81fsM
            hifEj8pjGm2NA/Q2rU1/8iPoEmpaXDOPSqdCxzefpVzG0LYQ5uf5X08zsgTHYfFd
            0gpCSuRizigN1pVmVVw9Ed25jYlM9ReAMtflX8WXGjBJQ5gKIEdH7Owl1mskyQSu
            GnAmUjRMyMGpf8k63BDNJDihPBgFeeBbUz1sVv6w45cRECRgk5NQ/72HjvhRETRo
            RxZJLAc+oW3E6eTkhl02x10MsN3JOQfHJfSZGjKDgtCX7sHIWrKzUrbDDV6NlSjS
            XAFora3AIlNjUlpgDZ00e27gLdc3b5riDGAFL4MIGiEVJnnvI5JYqfGGJ5zgoo2R
            34JS4gV7Jl3YNdTpBn+Opb4vTYu5Mq9SbWOa3bqbDAl1tvD9BzHZq2a1RcJi
            =VKCg
            -----END PGP MESSAGE-----
        fp: 355C11B55E83B15E5CF6366283637FAF9D7905E1
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/JEnAHZDjB7AQf/ejAaDuNzGTxw3sG5T3dqydl6RFsOLxb83PkKu4MwHOYa
            feFbCtdBR5v32p3pZkVF4lA6DdR4XTuqmZJcfNI1nuor/7l8boZnPzu6ARcoVowE
            YFYI3lQykAy6d0BdZeIrpb7OMczvGDrC93xxadSAySK3+yEenyfgmBrAU9YqG6JY
            1KWDCCqJgS/995iwFug3UzVzbx3XRbygDmS8BKpsRp5N8+GadlsovPArTVIfjV5z
            AwVJMFJ1V3ff8xufQoVdpcmfwwczcSz6/F4TjNccD4KbsWIMi+EVjJ3lJodbOVUB
            jIbRTHShKa0qDwimR9wACfSxQia02HBPUkSLcZqvPtJcAcwE0tpeFVvWDJEehZj2
            Z6TW5FkBVvRshGlcmEpk/9FDdnBPuu+vv3rrcpFsaF1HmJRH9Fs1SM/uMO6cv2Hv
            nUk8+YvetaUsG1Bt7mLUXQ/3nFNXj3ugPOwy6Y0=
            =E3nS
            -----END PGP MESSAGE-----
        fp: 2A25DA15018235A6206921952730D7A70EC35190
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6220UozeaaQARAAu8kw3Z4AThl+HmCylsRUsaVf0agiHO8MvH4KQUjEEXgF
            vHAgWF1PykFcK7uPe0CYi2A1nVf4K2JQW4GaGK/eGJO7NtN6AUv0Uccv9PJy/g5u
            UaRcfYBLGHDUVlgPhb92/6Hx+PV85390tqlh4zKRBUAF8zjfaVmZB4ow7KrtYNG/
            u6YdClylDT9FaALiSl9PI7Mixl/o7E7eYKNr2KLuFydgQVCMWoYsVr6qUnpQHRxE
            UYeyY/9wh1y14Ow6gG5G0llcBFeSMjSebIGe06spXBoe9BZjsgdDgU2vSB8Piiio
            prK5N4lfAAlNLNTxrT99gwW2tZOF6zU2G2mwp7GccQJXG+P9sKfC92shtE6FMmNa
            GslpWALTQMiX0IysGa0k2gSeflLvcYJTpVMe1FmNS5BZzJ8zM9D5KjEKMBd1K0Pf
            D6MHiu5XT+VZIwRwg+1097uWb+DgIthg4aLBZGB4M63CAy7Wu/ugOkxRsJUH1LNI
            r1vBNmTCf5P7OF12rf9E9zOG2+HArxhvbY4lJRIZGNXw62YioRqZod2xecFXszpG
            JYOoBtgESU51FQRDdGNVKwnDpo0e7csExFKrSBdBS5t1LXDeX7Nj0sm28iywtkxn
            gF/0psGHuZuTMpYs6M1QF6mtaYF5VxNvTzvTyMZ8+KIuN5RzrxOTWt14uUECaQbS
            XAE3o5TW5f9s9lSLJfx9RW4eMkm5j3uUR0hxvPRdPiAJq/lX63yCN8dUwJZdVF6o
            0eTLbwXEnDSagCn3PF/okR8ppYaIPxx/AJaf4Q3zBC2w1pNB8kBTrd9ROPt1
            =MvNR
            -----END PGP MESSAGE-----
        fp: DA7B00C8ACAFED2DA7E33D1ADFA8C968E1F69B13
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx6ne7Mq17RmAQ/9FDCA789i+Do8oPOBGDzi4yjO6RwkqeypCTFUPbxLpRZr
            RbgsP1m0wNLl3HBT+MZVd2imB9pq5R4faNedKe7y4/aLmPtAw+Pxfq26azYyAGv3
            JXXV1e50gsxFz7qVa1TbGQrkeBn+4OhbeYwB/MlIghW6Gg/JEYtpFlkdZm8IZRiP
            ku9PWRkE+zjNop+QXaf/wtDEowJ1zrxq4ovlU2HfQh0VuRIddQLMDqFkMtV+1fEe
            An8lkwAHaPxR7LhMXXyzZUAKRq+Cq7WzpQWvEEZ0ZzXed0t9mkRolcW1fcpgkegt
            ITWUs8eoBiP1kibGVU59HFcex0IqG0X3Tr9kCJvS2HKkIX1pnqxxh+X5kPxkdGoE
            7E1GTCktGGhSpC7g+g/LoVNYlFEHSJXsrkgAx14/rDj3DOwEE2pjaJvUsG+Zewin
            v2Hfq0Q1gcE2zocN/g5cIgXx01499I0O2trslhrXPEyzQ4pDuq7S70jUX0Iqlp3b
            bbFcWaVx6eEsgWalc0p8JUmzFdd8fbkPMZxnfD9T3NKmlF+V9LMYdn0x6wNwbuwq
            bahIRhx7XXq2iqzvQ9LB/DXOyAn3yxDO0RsVtF6uDwGA3QfaXbNX2yZbhpyjHmJq
            ZLlSdAalJIRAhn/wqeZDyiQTNIfZwnnMJYK4TdzoERezY7w8i5hLSHJ5EDuCoMjS
            XAHh/8/1HGvoOHPqbSeHBOERyG4HQwliInbLjPX0AYZwegyUFn77QiFIy9U+vQHM
            gHqKMv/x96sXmCbTpt32434woLK1Bqq+575HmdOJa61xLwB2SgrkknbApKOP
            =aa+u
            -----END PGP MESSAGE-----
        fp: 911B366FD384B2CF3BCAE8EE01F9B7BD00DCD57B
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75NWiDtWcDHAQ/7BfMONjL+ccDGnTp590gvIZS1K4bjUVYh84aOGs8gBzNz
            Jktb22IiyFoxjoX5f87iGqYu//6mWrzU7/qX85GjlZFpQoecvopNXOMH4x1COcnC
            /daqFA4BJzGXQT8Pkkw4NDEPld/ajSkeFM7Pf3127y8kACG3ThxFyikPuKTDjEsD
            NzdJLz9Ub4p8Bt/VrfDxQVPI2Xjd23Jtyq8T+c9Mv6fn4YSrAfa8xwzrWok87ZUB
            iQ/qaozqDEZJsyTuK26qN+zCiQdLeyWC7B2naR/ya6Geb37atyJ0b/aReQpcGpqr
            StByIL5cdGxsKbREc4HXiK83LG95ZrJLg1/8EtlltjLutuovxaj96RS3Og+oQTEJ
            kDBUpIYipX4xXpAbyPriJqf+TqsPgeHgLPedYEQYEq4L/q2ruaaXfQ9l0Xf45bQ6
            B0p8L3iLCX6HLOxZyKPAABKkycDsYjBT5re9Q2waZI1yKTB4Jl1/pzMrTxBfZBlt
            cRa6YlPIkKI+v/gOrEIi/jwszV92CBl/KEPt1bxhWAHvODlBgqwb3LgH4y6/8B0r
            An7DqLfGMPbtBgynUVzduMgvFbq60uRQZJ18qeGn1vVerZbzMfScM0DpG+3J4W1Y
            QAJrOfhyAKaMslrRCoYr27KaROttAY3uz0Ozt/XCn22MvVbthYRV4HbLPgarxIfS
            XAEoOvQPL4RCOuOFNuHrrfyVYHjvddi2Ziza0af7UDP9zhirspRk5Fwc6fS91phd
            Gta3C46MXmPIhP7r3oha5K7JEpu5q4ZXNRb7/tclfKLUHzXg/tRLhRTJ3nfD
            =jXo5
            -----END PGP MESSAGE-----
        fp: 4A4B9A8F518CD36766AF86DE065BDAD92D70F679
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/haI43zIlNcAQv+Par4atfcxEUoNpqE+bIr7tC7Ps4GGZUrKNrbw6zj70ZM
            mn/UMOVnEOZj8Y4JGDnd3sDm5roHvQMgNHr6EZO+TCaN2jeCbR0fn7qCeCqbRBpN
            aiBiDl75qIV1GfnoaKfJPgxXO+MFk3VQwXA8TetBzwUncmlR0D5aoTLltEsbRaex
            XEu5J96Qym4SQpvkqvm7AWvDXi3R9cQ+PzhRdc/4bi9iDoWdIgf/ekKszfVrPUqq
            /3UlAOJ7eAOc96H7Imf/OJhXf9WQtg6tQdnkpCJ5Ja7tK1wLXNWlKf2CI7kE3N2s
            MmuzZRPsi4QbWJ0Oz/zC2GWRR2WU+LphcV+YvoKP+0IwBEbtLXnI8AjQqxPz9uzO
            S6FRQn8Crjpq92YjAsYo3PrjQTMpooI3hBu8q8V2xWK+oHwGMlh27bzoV6zSeJIe
            c7+EFmnOeTaRgMPRnJeiRFJ3WXWajcDjpnB13uKvfqEgeDKDf+7elznHxPFge0WR
            zWNluW8mn3dtdokZO3sq0lwBibFoOAY6OlplQbhpvO+NHzGRNx8vR0XcIiCkgb+t
            3fmZNILUAGw8mF0PG+W+Pdcpk3+fG7hleXCxs1e5cdAPQnAB9U8Hi2NJcikm++sI
            ZdOooGjZoUZ5KnDqXQ==
            =JiiO
            -----END PGP MESSAGE-----
        fp: 6B9CB4956CDDD0599A518BA6CFF195C6AE9E4939
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQf/cgC0onnzfss+ElHT4RRL+Y4qoQQcgP9EK7Zn5nEFTcol
            NkJb2u2wY3aCGwnYsDwnvZ4DpIOj5zxu/tC8jFZyUwmjfrKX7Zpc5s+6Ab7CalgL
            aaRPXYVaMUF8o5TOzupXnQC22VF3vEILZ04bcQCS9moyZiDU2wh+CjiIVcVhRmJc
            EVQf5Us85X66ioXX55QZjVnQqbUfjOkUYxxgSGZUzKJhEdWGg0ttl1IeCEa8IJGk
            r8a749/krMPcAraGfu0ELEsdSK/PsZ8L+zssKdFJL9kWWKVJe7BkYHxvuIMb1wQL
            j0dbKqrrXcV6I5HOKWrLzr3TJ7wfSjcD8I3Sts/E3NJcAdxV8zftGCnG8abyU77k
            I2spiDHjlwbKiiwRWNiXTngTJF15gJBnZ8SMgE8PtUbDAD5DPbqgVZ1s41ex5VHa
            tZ/y7qg0PXpf/hfle3qQY1bXNmo5XsCZD6vn370=
            =mu99
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T13:51:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0ZhTnV170YBAQv9EdRIk/0Cdbnrnrg+LJInmqGQHuOf7ATeW8HON5fqjQi2
            kOTE1+HUG+7rvI1aN4bHa/qFP5Yh4qyUHvS0HyNuuslOGh19eMMV2RQn5MwwA/tj
            j83nrwjGceXLoY3dr8FDUnllY8bVa6C2xX4i88f09/rygQEBFZFz/BvW4W+zo12D
            nJ0gosJ0eu2Chf3awT9tyX1swqj6+zFs/ysuULBXzsAfcbc9m8HiovxSLsp+yzPO
            BQm0Hvpd4fZbXvIBAZXD30igQ/DA/RPUI8VwtZtlUCMnMNrzJqCxlpm3FLo1ik3e
            pTJdRzQGzKyCig7c/E4gqerDllw0+6Ad7xlwt0mq/WpYCKOqVisbr/3LLjasAIXF
            pqwhnq5kPVXvWbCZH+UOZj0EU+02b8+7DjeCWIndQg2+9Bq1vYFfSgPWhq/s+tat
            UOa80Hk6yjB9KChujHz9OIvv4o9KHiorOBLusQBjPPR1IHhP1Cra7nbDii6HWHxx
            0qfnl3VxmUVFpjNLxTBT0lwB2jzdX7dsAmyvCwQabxi3fMIk6mQiKE8Wpv9Hf7O3
            7xi3x1VgzAImpdUqZWmXt86QbCXVp8D+qDOvUaWS1Nv5JXTrfMs0VvFGXGoE8nCr
            nln7U6CP6/ibOY8o6g==
            =hVtx
            -----END PGP MESSAGE-----
        fp: CC69D686B0FCFF3B5C2147AD8AFEC23AB1EB36A3
    -   created_at: '2020-09-30T21:37:17Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA6xIjVuCi+XoAQf/XaTfNJd++IDHGA2gzrtvzFdqgeGYkgXQqtr8JH/HtcDM
            cV4VrUCuMUK8SZuf4c09b0Z4PdHl4WQQCFl6Zf85cOJcNRtN1cqKJ0WaN4XpUkES
            oeN3IcQy5wgPdCsU7RY1f5JRO7F1Oh+jXTMxI0uH3vjOWyokI9ax351S5fMnlMI0
            CXIT+V8sqxjeObj01jT3spPYPNr2k35krRupKIZeCp7K2S0EWZ8vE4wEcaf6LhfE
            L6bNvjKavRj/bYoh47XY/68Kr7IqenNnmpxKrxcQxa26C5Y9IknOs9x7q8lGeWPN
            1Ekpef7nXwdg7y6cvefZ8D1e7s5wXM4Z4fuKiAGbTtJcAaS4F65s6WhkmPFlJ5Mp
            gxkUxL869MVDYgd4M+86M3DpDOCW3ZNWTX7C9Jqy2vJ2SE+Jt1HT7JMwpV/jzEb7
            jcWVC4enAPmeSOvSReZWN6qiEh+EjDFNWoQcQlI=
            =2pLI
            -----END PGP MESSAGE-----
        fp: C7FFC0F56D787B25
    unencrypted_regex: ^(implementer)$
    version: 3.6.1
