tssc-config:
    global-defaults:
        container-registries:
            registry.redhat.io:
                password: ENC[AES256_GCM,data:eeQKAao7RMI1X+IrHdRoaVXdKD5f1Yehn+EZXDD4E7aeKcINz8uGwpxe0+7Lw7BiowZ7DNKaO1stktPxTVqnbqQ+kketPAcZiJag8PkCUG4xFFABxyeNgXaOOLA65ZBtVa3WAZTmhuiZ6dx0CThCFfF2arP5/zlYjgkXAdcl31SZKCTNxk7zhL2FSzWk4Zr0A/vkbGpkD3vZxZ67ZVUMABr4qyBUQ7Kn2UcG0HhsH5UK7x9SGTMGFIrpZHsiXkf51mBof25rIfR5C0XW8ryqWCNP2kQ4iyzSgZ27L1rBbVXn58e4KpXaoZXLKcdJLoDluN7ru3TZHwswNQCePkmn927qmcqS52bc48vFcJYzW+hY1Og4UVtF+JisvsEZHEjykq3Cm6FcAteA2ml/uRLvrKidXInUsCj1wTQIagoFTc3+Jna6wcC55KfUP11XVxEm9KM6j/Vp+upvAdVrb4dn17hyYqe/ayvipvkczOHyoGC1OgRi5P+9COBMVGDzwyR6GS20Dy5xp+lkyht74bRLI+eQg9rT8AlHwRVaozO2j8gR4GpN1S6dfmm9nKgyUvc/JIkBQIjOhIVtfNqIT8rWpMzLRwI9ehdlYnoQoW+dNgwcKcx1CKK+GluJH4s3Ow4K4t0mwm2O51KGOuMZF1GYLI4Qn2K49iEICrznwEaTGoe6kWkigxpsYBv+65gANDYWcrjnKcJAqAsMZ8hSPAAKXGIQO+7NxbG1bNFmRtDwvluW5wSOHIMPw1lsNzRWygWI8YiaERwPlqc/RI0VUd1vfQZWPftBwH8iDl+x9vNaCFJCdvnz9FFm2y+xNd5jI8DMFxPmji8T2XAyiv2XkF89cMS/PVx0poY4ovRLE6K91Gfztb4NejWbhalheexTbJ3y7aQk7RbFP5D7SfkQJUbfj/eVx+5HGeJVb9r2xamRmbOGEvDMqin5e7GeLCG54SHOp5btuViYRVFPNfJlM9UeUL6ThXckF0ToKjCr23G23N0PbTQHcJFMdEw=,iv:0TVntM+JilSW8z0OeZjq7OAeW6D7A+kHbNr3dYMhjC8=,tag:QDWHO0X9qUUZo+KhrqeKfA==,type:str]
            quay-quay-enterprise.apps.tssc.rht-set.com:
                password: ENC[AES256_GCM,data:Ykdb4ocIcY7JKCoPSPpGjmnReJw4043zsy2jGLGmmnkRhmlWTqqEEhGLr1IgXihZHcUxVbAcFpEpHxVXMcLC8A==,iv:olNwlkYXECCrIxnbXYFMAIKjVv2OfJbZd91bQxFbKnU=,tag:hZXHdMvuFoIcdbRcAtiRsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-25T13:22:19Z'
    mac: ENC[AES256_GCM,data:foxffHbVEePE9f6ihs+NUOVeSqhMPs0k7lpzBNHBTAecQL8998Xras0ny4YOkQLeDOGn80kYY0qeQZOEWgGfK/WnrrzLmlulu7z2TfYA1fhu8youg17khNLAdgKNagKlaVB7AsDSv7rU8avRhbWlh5mn1RSDonKMzq2IcJZ3xgc=,iv:sF6MMTI03ugIzayetGbXoOssZ2LzK5ztGVh9xiwztzo=,tag:SIBNvDBWSM2DAMLU3Ai4Ag==,type:str]
    pgp:
    -   created_at: '2020-09-25T13:20:47Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6220UozeaaQARAApeASyDyACpE1MLUWUU58aKK+GXzHYSgIFBqXTkfMrlXk
            gj7uHrS8dPQMW6kURwnyBgphZduaArD7JMlxIZsCfRrmazSMlObD1u4nmmuNu4zk
            ztSa1oqg+b4t70l0iVOXIoiyhVh/7WCSACm9VEs5vhZtbgNT8snvP7PmPVEzWJy0
            ru7466oIV+h8pewnXpCp5bWhyZP1Lq1fXtvybE8Ic12iAc4i7Gm9Cpem6PentaEQ
            Q8sjQycmbpINY+UY5piWZct9DnQaHMQV3Xpv1aaNsy7pB9wHJVFC4NWlEVI91UZv
            WIwaMEz17FC/8YDP8niYFh+NXdUNvUr/3TI2yH43lPX52RXYeOSxcV5Z6XdbugBK
            c+Ddabsv88nrNi+GT4TcsI9u0O8vKUJTdoPxupoSIUn8f7QQadqxqJv9yBY5TuV7
            azvH0jPogMBP2w0mmzLChWgebz/RTKdzq3hsW8wYvKinwt2wGcJ3/WDbBHG/5M3c
            dv1w/aKd+rBpCEK2O5rD7DL3Nxv/kTU4hwv0lPzBiTSHEy2Oo1g0usX+61X8WPjp
            +b6b9lIAXYIBoMETvMvvKtTAxgfzsvlQEk34wYh7gPI/3k6mfSfnnEsbdLKTx8QD
            QmfVQtpXbwERYIL3uZpqRbCoyAEcE0G6c3xZQjWnE/nhsAsaag88bqcnpm36So/S
            XgEiJ+53jpr8vJTE09wuyNKGMJq7lH0rWCB0yBhu0lShSfZubGJ8N1+JlSOHYaeS
            dKOVNc0L7+cz0vqmDYsRY51eWgqbQEtOUrSoR69Rdn0aIDKkPx3d80tloNffMUk=
            =1OOR
            -----END PGP MESSAGE-----
        fp: DA7B00C8ACAFED2DA7E33D1ADFA8C968E1F69B13
    unencrypted_suffix: _unencrypted
    version: 3.6.1
