tssc-config:
    global-defaults:
        container-registries:
            registry.redhat.io:
                password: ENC[AES256_GCM,data:9iWrtcbivv+vxXidQKxhpQ/CwZNsfjVBsurHeXAIoeyERKDpuLTJ9D5oM9IJCjoc7kBROX/fojHPH0hVAFOvO0DlBcic3bTBaUphnBtW0iZRZLP91SzsTx+DsfcXfJpZAtEgHWD/j9oNk/R1N8PcR85HCEwor/viTzMjTZzh5kfHR6JSA8v7dt7SgK6v0LCGVMWpTpCen7/7/FLZaBhT8TVrjyFrkvk6PDKKZvrLdjdjzD8gOrRQ2QksPlVzQm55my60SlS/fDW8eMowu8NR/4gO0HAZ/v2m1lBjVYrSu5SikxN1Z9aeQ1JMZcmQ3sCV3Tm6zBqjradt84oqxtkx1tpMj+mBUE/pRw2KvQCUgkKuAelvqpbjuefzOpaKXegBOjOW1502Ebz5TZ79iNxgWhG7LVIvmIzjDR80RMAn9yaQz6uhgwuGb6rFdpvvJCUrFkK3LR71Yz3uReCyz1oxItrVZubaqxis+ZxWnrAfNEWy+RdbmRe712ObtOmdHqiIxaeV/RML1BtEpy0LIXWQyDtbItW4KO7h0J2vfUrt8DXGof7Pwoiu29hZuV0JhU1tFLV1NEdsstOmSFq5GOcyB7EWQS1zblm+zPh1nOr7lFUbs/Be9zentFvV0lrnU6G1P2wTKfRs7+Pz8nweJJgosn4GLSOB+cbwFvqHp7ruFqbpzewrkR5bxdif5O8an0jgEuYFGWuH22JsjJinieqCKYvXay3UrWMFOtOcAzeiHpKHi67f2pWMC57BZA7+4AxDmWUshAxsHjTwzQwgTbJI65gOxMP9vg8rTogsYcsjG/Q+0MgI/jTm4ffHtoSoOjMY57k8V3Lev/UyV8z1wAZ31Svpm7Sx18HBAji0d8Ehfi+dNKSeQyy62ECTd4xEymnhWsId1ZQFqBwZQ3Mq/ahSYa9vu9/SS6LRefgvDlhy1yh/vgAGL/Z7lcaC7IdyhB2/S+BFyDNN+4pc5vWCVJz8wUF2P4sQRcPyvaMOJRw/UwAGlaETE8vRxS8=,iv:0TVntM+JilSW8z0OeZjq7OAeW6D7A+kHbNr3dYMhjC8=,tag:UMXCk23yUxapPrFoydbTiw==,type:str]
            quay-quay-enterprise.apps.tssc.rht-set.com:
                password: ENC[AES256_GCM,data:pRlSUm2/SLNHwjQtKqw5FdqMuGRadMQjfeCzTNnsHoJWNMik/SqyoE5rU7iab8KHLumzRTIZX8RIk1gPUKUKqg==,iv:olNwlkYXECCrIxnbXYFMAIKjVv2OfJbZd91bQxFbKnU=,tag:KHeCowzodZeHITsjAgZK+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-25T13:36:40Z'
    mac: ENC[AES256_GCM,data:l3/q/MoXEByZC/ir3YKNyLa1x1Jd17CWOMgJo52glLuvQ2zgqbuz+3f8Yxgc0bIzcRVVL50+zTloSf9wZOWI/CYKmpuOlCZB7E7yfSZgqDgctBoDgLSk0CYSePZKNj1Des7uuSvybyTk3vJOx1q0XWOozOKTuMHcN2qsckAiTVQ=,iv:StVW6ZU7kcfYeiD65SBzedsrtyJ1IFIeyFgU3l86AzU=,tag:JdORn4KE+xgCkN6+e6Kb3A==,type:str]
    pgp:
    -   created_at: '2020-09-25T13:20:47Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6220UozeaaQAQ/+OPXGPqEmqXDYa+OWklITseyKPJKTMwT0vC0Te/Uw1RKy
            69yGf1/Drrz5B9BcXmbRczNL8KN2FE+wMEnDvbSSrzpC+jXBpFURzX0a4jTFnglx
            KfpiZEZ4uW2E/FepyYGWkKP8tdWfEGaulIyhHN7T7x6zrhe1ca2CQJwJ9DCN2bdL
            R6TtQAgW4DezD6Hv2Ewl5gUBOxXGzu9z8gC1KCD8S9iBQ1bDS1JCnYvnwRVV0uuB
            Q8KYm/Xl3AMy0EQnwSmsvAzv+aizkYtYZTQ0UdtzxlMjNNXcffSeRdBVWC2iZYy1
            fJuV8A5KI7VXtCCcsDPwWVRD6T9Ly/JA9pHKS/a3Z/NcdsgAttuLx5QPdSRydyME
            hHv/TpCfyMaNlSXCFZs41KmwvOKeQD3HhP0vjU7m3M7Uj+FwSHQB/yXgLYBH3ulB
            2GiC+khVml0d1bmx7NUEgW+4IFTC8bK51O4Orr4z+Ah3HOIs7j9tLYuODZhi1rCx
            fXR8Y2nLLzFQoDgTl/JXlMt8p0R4T7uaxqDILFSawWzFaRpTU41bVY0QFdEY47Ja
            EWq5minYpMexOVQg0hc0aPUvGzlBOkJrpk4WrH7sigssXZpJ+DBeTC3wCGvPRCwW
            +4p6Glhu0y6MLd6B8lBNYXx2LHcShPtH1R5b1I9jVFQxNaFq2vnsJa8IWDfnTxPS
            XgEOmaIVJS/6PYnt/rqFlA1s6bZP3/4G3eOpbXOFG4lSajM+3ia+az+g3WKSi5XY
            e96Ip1vPm2AevEQ5YKN/LXM73fIuHddz/d9vZ3Mv83ICdBr7aJ5Fy6Nw6u0N4nE=
            =68i3
            -----END PGP MESSAGE-----
        fp: DA7B00C8ACAFED2DA7E33D1ADFA8C968E1F69B13
    -   created_at: '2020-09-25T13:36:39Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75NWiDtWcDHAQ//RjC/l6OSn+5HZ9YMZSrH4VnoBAMGPFX5sY+GLt+A2w4Q
            Rp9637udxXmKPyDHtg8s7SvfSKRaksEsVxejQfTGYScmQgorvdMHNaN4POh7fJy6
            yaTJg5RqD4Q7WW00DhF3KR6WsBizSdxdXEUrtHUGnpsDqnQ3smC1xnNqVeqyw2DJ
            taG3AROLjpOQ+9cFDLP/IKnQ8hfsKz5X6U3uznRocH0bv3AtTR1U6x0/Wh+vG2If
            0mI/jotBRBUB/NFIwoCQIcqX9jr7DwSF/5BOkVY2lRdeYikjRNostRA60l0wUNuo
            vpuDQ45AWuS1EjGHF3krQtIZ0ERtaWfN0itdWSGCSFr4UZtfv4yw1NlXIJwCyC7v
            ttl8cvGPkYFReIqU3ZCCgwXpyl+FFlkZq6J+kojeQ1819LS0tVsYls8XJgWA32/N
            BuhR2eAZLKxNcvLfc5tK3c1Padq/BXbywPYZWGphwkM3LQ35g2BhYsZ45kElU3J1
            Lpl/3kO19f32n1k7ICw/noKHbFmVVh+CkBN0Q+c6lHCy5AHQpOMMTIlvtQ28DaO2
            wkXVH3176euFqVb/n/soMu2ZCjPMhMXSB34qlB0rNh3T0sihEySLCSqZVyp4yk76
            GuFVkvR2LGm+zSMYLz8/dfw0jZnbtGOw5Hm5yhZqpFTqmUnv3YLG0EslAJUWx7TS
            XgEULrqsC16OkoEvu0G/QvpnVX6eQfQVU0ercsxojDwZ5rob7FDl3wzuefbgmp0m
            znEKXcGhxSypRNMr8j/O88IlhwLyUBhY98jGNngOjozxQqu2B0XREunlsZuTZjY=
            =Mjwl
            -----END PGP MESSAGE-----
        fp: 4A4B9A8F518CD36766AF86DE065BDAD92D70F679
    unencrypted_suffix: _unencrypted
    version: 3.6.1
