tssc-config:
    global-defaults:
        container-registries:
            registry.redhat.io:
                password: ENC[AES256_GCM,data:sC+px9C0S5RbAz1E3kdyETm60JvOt8DoRmBeECuBQXmqaUNBfxGoczUp9F/QBsDTeaJnC8eAh9XVeWGH1dl0fTzI9Av7wqSqUmCcM4KXbmcK1iLq9AehQQKW/jgZi4hOvKR1QRRNquJs18iaia2kVY6Fcek057XlsKXkW72s6i329AtNiLEnNQPYglgesniRGKCaFs/QAMj/blvWAlb69WLvkJ8B08zZBbKxynrt0so9oyMTZjdL1PiSLt13x5D4W6yEaZQZvvK+poRxYdw1VAP6M5its6yy1etEKa/fpp2K/0jD3IfPbq9Zqydn5LuMcbgCS1hxQT5DUfVqhZvgc/zYkopcRGQznLS/TcXq8tQe5HNgejeVOIzuZoVrdL0TsKrjWQUbvEH1h297wEBAh6OJe0TbrQHsf9PcGUtNpO4vTfnsSe9eXpgKgG5N0mPv/TffJ4DIxbxWhjEnbr1x1KTxl9qXZuqxfYFSUzE39nhCAd7gf1U5a34tFgjAjRScDKWa56EFOLgXFmoWi9ySPIelGW2xFS0ruri4OX/9vtr7LKh/mbXUkpSYXiElke9wJ+o4rV3dfqs9+Y9XIE1QK+oxXey2+SQG7k/UQyqKLI3TezIpoO5uyF2445gA+x6eAzgGLqD0Q7FPMNSIJZPvcShMK82UZqMkXfDevIG5cU8EAFKONFIWlQp4y9xuLv+1OFgAfpYKhX+qykwJLKbWZEF9BmS66XNGtpJqg5P+Fz9looGZO+5YjfOLrU7U3rSRkyQ6QChHqh9gH3QDJcmHUKO4Wt4RWhyZP2GYFS3avJ4sny8vO8NNRKePJ+A1IFelSTJDNsfyrlnAXHEIwUpzp4KD2pFeIlesJ4KW/U9b+CVogWyWSrFKsaOP9KJ9jtIV/EIZsoohZvOu7S4+huMlm4TJUYU39k8t8TFnI8lvIoP/YV1RELqB37WwiYy6M7XoXd826HdDntv9hH7d0h9dGKDi2JXAXLuYCvSIPC1G+loTuFNhOsaKEsk=,iv:93KcZ3bxvwzE7O6nFFSs9vT7o6XpgoayrLu6dE5X7TE=,tag:Sx48+amXsh9X3UZ4VwYyQQ==,type:str]
            quay-quay-enterprise.apps.tssc.rht-set.com:
                password: ENC[AES256_GCM,data:bb4KFttUE7PTSbr59P466HbGlLJPDYrldyj9mVlohtyhgHwetsKMeywHbbZkGFo0xxI7nUHCnPdlyHegdTrtFw==,iv:mR8l22fGvXhshcw7/xDIYpTulWSpYPWSj6RO3hmIgqk=,tag:QqxiqnPI3yONNVwJJQRw6Q==,type:str]
        maven-servers:
        -   id: ENC[AES256_GCM,data:Lgtd+bEKlZjfXvf6y73D,iv:FFEvjLpuOSeg9NjkMlenR7W+8aB+rMEiWvXel8RFD6s=,tag:WV8ji+oWwioTw8yrquaagQ==,type:str]
            username: ENC[AES256_GCM,data:rd8s2A==,iv:xAVMYHibXWIIKd5xu4wWxPHGksRDF9u4pFW329oRUbs=,tag:YtBHxF3XUfahTeBQn0nkow==,type:str]
            password: ENC[AES256_GCM,data:OYXm8JUwWhaqxElfhlKkKWVu,iv:YwxanLTJFiwDOJk9T0Om68zNAC5EAoJ/iesaWEo/fBs=,tag:lodbqbvKISyT6wB6TpAoBg==,type:str]
    tag-source:
    -   implementer: Git
        config:
            password: ENC[AES256_GCM,data:jMF/07R8uaqL6LGT,iv:K21Xf0tZk9z8c/j9cOzrH9lEICEpIoAHcsVagF1V/ds=,tag:Fdl58jpdZBNZISgf+k0Gjg==,type:str]
            username: ENC[AES256_GCM,data:m2TuP0W5Q02p+kp99IiZyuo=,iv:cEex6lk+ihmXURYyL6omboQjddqEku6qCIJ0KZpbI/I=,tag:YF+dgFa77MqLwFytRLe8Ag==,type:str]
    static-code-analysis:
    -   implementer: SonarQube
        config:
            password: ENC[AES256_GCM,data:nehfYyOikqttpFtmAL75sIbz,iv:8gQcDymaM1vEShKnqj+T5piN3WhD0o+hH0vsa9S+o3M=,tag:in7oTnNpBgN0/xZZFdUhRw==,type:str]
            user: ENC[AES256_GCM,data:/UTZ879wgSA0tRz8c/jQm1s=,iv:RXkdEW/OIztLdbK8kjmCdjPs72YeQvzPaARrr2kop+w=,tag:BOrrMVzoa11gk2ucFrWVSg==,type:str]
    deploy:
    -   implementer: ArgoCD
        config:
            git-password: ENC[AES256_GCM,data:jS0wBCAJiRSgI2bP,iv:SB2lvQFPcRLl+90E4m/+vl1eF5BNHS7Wm+xXgdjsYW0=,tag:xbpzzvZoOshj03oTLPV2JQ==,type:str]
            git-username: ENC[AES256_GCM,data:VgL0qHymLBpmFfcdR0lUGZw=,iv:m9sFPV++85GfJmp+gdAaUZ8S63o18TkRSQ6PARi4RNI=,tag:JHUCooOFfMloXGESTnPsqw==,type:str]
            argocd-password: ENC[AES256_GCM,data:LZl734QG,iv:th7hP+6NseHk27537wS98XBe/kQta1m2jnnxHcHozHg=,tag:lbZUHnCEcMgJvrsqAsvaWg==,type:str]
            argocd-username: ENC[AES256_GCM,data:5o9JVa8=,iv:vuVtf9UgGjQM9SrOvO0AtT5c8XvH/DaV+m6UkeEBpc0=,tag:CK17HODtxW1m0jFnXBjVQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-28T12:28:18Z'
    mac: ENC[AES256_GCM,data:XsttGUthji2wSifPc2hCZFwlazGtEZVptdfwq+TpLD+8ko4ts5dMbGdpUBNtKi7eokLzjkdMY290xnZ2DLwQqAOafbFXjpl400c/DRc4l4o7U0OVzsNnJwHr/17A9Nh6sjqlxbn4xOmBIiNqU3ZgunhoM6wuTen76USQbZzj/UM=,iv:yBk8HntDvMo3EEBd0o4hfkG8I0gifjSwGI7CzUjmu50=,tag:xkXqYzLQiAWQhcrazKIiqA==,type:str]
    pgp:
    -   created_at: '2020-09-28T12:23:20Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA3GO6GKnGxytAQgAFU15FwPw8cVnXKYLgIEn1Nzc8xU91728h8ur5FgKnKTi
            xOmBj7rpDBCxjUawb09EvolBlxe8MiRUBTd6vu8yy/E9GdyufhCPxwu2M29Qp8OV
            RZCZ8DjJ75MliVcQYXklVAzHAXvU92vFk/T/+uZtQjKHLFeLtZRNnsginQdWONu1
            5f9Il2kmkCqnfKO+jXd21gPyiKAybnTISp18f6EFoYA2FRJh5S0u9OzMTM62iwod
            XgW5+qyYXSXbxaEC0bfLAA5XA0tTq7wfkas6cAbsPy10qdIcP9cz7+izwAwIvhB3
            EWaf6Kh6xQiYLBUe0OUOOqUIukxQJVwKqvK2YEb3P9LgAeTUC84E778eqnyrWpXO
            X3UU4ReV4B7gZ+EOmOC74h2yBfXgr+XkbVK1CqcwBJ/CgibKC+rp/+qAL6vKg8fY
            gL6ZxYfYOuBb5DicJdARS7kdoFmCbYTcWU/i2YY7GuHrHwA=
            =abka
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T12:28:18Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcFMA/pHJVB+8SuwARAAioM4lGV2BlLrAYsdGHxZvdx+hiph/sXKVwn7cbOIIf3C
            2ecWfgvldmIgxwIlN2GX4OsuP7SXodDnDiZ9y21fFoXxw606Y9MsmIWjAMe8F0B/
            Q7W8LvJrGsVxlKJPqzcGNlbkcy3hKwnCm0UDVzBMeAbiNH+klJ+9wucIzA0/YtiL
            5fDG9/DvQ0UAiLLjil0RJ1wJtLvc1/043S2TtSxsHP7uLsLBT3i/S5bzJxs7iJJb
            6ZPPJWA2ERzyNDRmSk4o7pQjtJDcZqmD8tLva41Pksf/fEyJdqHUOLPquCzPgZR9
            knbjxMVPQvroxqAiT9uBnY6H3Ie0RRvzwTDqrcFv5rCVIlx6Aa+kc/KgfZki7s+t
            EUdJgpzMA0C6JRU/pB13D6I0pAGRo3ukGVtZnKAFQxRMxPABwyY5SyGiV1J+XyWw
            86uNBQIF1vdII6m85CgJ6IvdL0dlB4BLNZORMrZwM1hnOFmTnoNVVQvL0r24a5iz
            kuKscsmn6cSeF34EHmlNXZYCDowXLInih3SpYg+0t/aR/2zaLkqG6zjbss6a8IH3
            MieR7rYU1Xian0ouvYki4PgLqyM5ch0+yvlFIfNq5PS+yavTW5YsBepXeX6Zsv6R
            vqsoUPdGPDyY7nCoF02VfEawkGObUAsFXS7iUUzRWWAL9Z6al272IVTYymNxNbzS
            4AHkYCaJ9Zdc5Se8BkeCDKmfXeH9PuAh4ILhZHfgQuLzagex4Knlx70ceSDaSgzp
            h+c1Dr2l8j9uRDZgyIX4bRGm3q8YcvLguuS+Ybn9Cg5H+s6mvr+vWXrN4rifk+/h
            yvEA
            =YDbP
            -----END PGP MESSAGE-----
        fp: 355C11B55E83B15E5CF6366283637FAF9D7905E1
    unencrypted_regex: ^(implementer)$
    version: 3.6.1
