tssc-config:
    global-defaults:
        container-registries:
            registry.redhat.io:
                password: ENC[AES256_GCM,data:3vv+8RjjCPbI9egIkBI30la9xuJgjyvr4hDaf8uQo4hqb0psztFkltOQQ6RCdbWAnCR5TZx6l4uDhupK96VdP/SE/IKyafyHUgQNEwiWP54jzoCI8g0sQ8Ov6xRqGQBF8N901V/2ZFSiSyo4Ba+o0wNY7H0FAHP2qI5cNKzWg0v5SGUw2GfIHDa3VJcv4oETH6sHyy+3W6Fgq/CDrHamH/eMV2fvILQGKQbW/FmwU/xT8lwbknjztN6khxQiHpDQ9qtPMZ+XO+KXrq+LFSHYf/8Fk/eLE+lz+9mhcD7NEV09r8kUE9eAqA3JuA+O+L0dJBkdCDvRGAsmxmZ4XdPNpZP/CsCGlSTw9+T5SNCrhKVUZl4NNuc2Ifl4K6Ut2Dmg1OvGj7Rui+uBalEzuJkQpHVmuNto0J8uZVKD7u66p1L0bE4wwUvJTKBYeOPQTi5vi4q+/tHQJV5p4PJjE+cYoBvScbXOXe+fY1TTJp+MD64qQbLbxIUfK4t73pqb4+0OT/TdklB5qrjd3hPAdA1AMfF+Hh+aiNoD8Y438ZGDS4O8gOlt0YOFvJ5sL6wJXK/KiZ9zoGK0ys9cmoOUUOijR+IvALH4X8JpYypoK5i7a0hEWLZwUC2WVkzwvHRJNzLUmy7qbK5xBmvDOZUJr09borG4uJAFDX6eoBMyPFSUIDtGPaoTPiecB/YOG7/mrIS303cVW+W79mZOKZn7miQHlvA4NwwDlhIxXI4gkHW1kX42D7opP7NtetM3BmKhU+YbUzVgq3eQ52lKJpll3hECohZuF1AjIpCW8J5YGYyNqwnLMm9VybHbh8Jt8hRxm5+U81PcmLG3p3RSjjvdsFHiNi0OsFXrnsjhcZKTBqs+fe5lNX1GUu1xKwaUnNqTzyCB7sVnrzE9PeOpSP8PwdFkpMoAIPG4VYO2eAGoiHZqGfWPBZswxB3d1repM45lucmLddJ/jFQOe34tnlPe34z7haF7aTPkKbVgCO8WLBpxRumGmj1R9jg1LBQ=,iv:93KcZ3bxvwzE7O6nFFSs9vT7o6XpgoayrLu6dE5X7TE=,tag:XDZ5gENhzlB93CtkXCVC/A==,type:str]
            quay-quay-enterprise.apps.tssc.rht-set.com:
                password: ENC[AES256_GCM,data:iyS7Fj+sVBH22DajIpXmaqFh3J9VL+g5AFU1P/r9yxdnt1I1WLIK4CURI0rudWBSdGa+G5gZna2RWf3wBPmmSA==,iv:mR8l22fGvXhshcw7/xDIYpTulWSpYPWSj6RO3hmIgqk=,tag:4oAt6wjoAvSFMAPEsP2G5A==,type:str]
        maven-servers:
        -   id: ENC[AES256_GCM,data:OzlhC2/xRzNnD62YOM0I,iv:FFEvjLpuOSeg9NjkMlenR7W+8aB+rMEiWvXel8RFD6s=,tag:fnoarxFUWqvdeneugGvaNg==,type:str]
            username: ENC[AES256_GCM,data:1kmt3A==,iv:xAVMYHibXWIIKd5xu4wWxPHGksRDF9u4pFW329oRUbs=,tag:fa8bA9URXpSfqzHV0fA/0w==,type:str]
            password: ENC[AES256_GCM,data:x74tGxDOr8E0QsLnv0Qf/8Kh,iv:YwxanLTJFiwDOJk9T0Om68zNAC5EAoJ/iesaWEo/fBs=,tag:QqcYiSvjSxOAmE2qnr35gA==,type:str]
    tag-source:
    -   implementer: Git
        config:
            password: ENC[AES256_GCM,data:2HHeqKFP+X5Reb8i,iv:K21Xf0tZk9z8c/j9cOzrH9lEICEpIoAHcsVagF1V/ds=,tag:a+DFhdaa3+iT2lx+y33meg==,type:str]
            username: ENC[AES256_GCM,data:C40vY1bfhQZ4Bv9fzxl97xw=,iv:cEex6lk+ihmXURYyL6omboQjddqEku6qCIJ0KZpbI/I=,tag:jdNTQAl5oFszlHfVFNpBqQ==,type:str]
    static-code-analysis:
    -   implementer: SonarQube
        config:
            password: ENC[AES256_GCM,data:FmLWLCwF0T1JD7JAZSKvYJBN,iv:8gQcDymaM1vEShKnqj+T5piN3WhD0o+hH0vsa9S+o3M=,tag:Hgn1yWfrsqxGaVdhrW0VCA==,type:str]
            user: ENC[AES256_GCM,data:eeWKwuyrboQC1T2jgex/xAc=,iv:RXkdEW/OIztLdbK8kjmCdjPs72YeQvzPaARrr2kop+w=,tag:r2Rfucq7AYa0lXmJN/VSyA==,type:str]
    deploy:
    -   implementer: ArgoCD
        config:
            git-password: ENC[AES256_GCM,data:hP62UfCqeJRuXGAW,iv:SB2lvQFPcRLl+90E4m/+vl1eF5BNHS7Wm+xXgdjsYW0=,tag:US+71GPvOJWXVkyquJYIgw==,type:str]
            git-username: ENC[AES256_GCM,data:z71zSAiWGY//R1PwW2NG06Q=,iv:m9sFPV++85GfJmp+gdAaUZ8S63o18TkRSQ6PARi4RNI=,tag:p5hHkP4fQTSLC/KnLFa5lw==,type:str]
            argocd-password: ENC[AES256_GCM,data:TdzgMeCK,iv:th7hP+6NseHk27537wS98XBe/kQta1m2jnnxHcHozHg=,tag:wHcp9RyPCVXQp4DonoCOBA==,type:str]
            argocd-username: ENC[AES256_GCM,data:B1kHGb4=,iv:vuVtf9UgGjQM9SrOvO0AtT5c8XvH/DaV+m6UkeEBpc0=,tag:7pxS0iz5jVWy56ocjWA8tQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-28T12:53:10Z'
    mac: ENC[AES256_GCM,data:0TDc1oBXQxboiZZnKOc2Gamd1dSRajQeztxUvAinyj7gzZFPG3O1Ybt6y2cMFtIEGkrfmF9Jp5OL2VAQavdlOEdMqTn23NA2IU0nBnTn793xHDBMTPMAJovYpf9bsXD68ey9HON7nBtUbBoAfnytlcChF1PZeM3tKkFV5Yhr9Io=,iv:/q83ZDroyqpL6W3Os9i63iWnajkWyfDafqaIkA1hZo8=,tag:B93T2Qqu6Gz+BG90yzSHwg==,type:str]
    pgp:
    -   created_at: '2020-09-28T12:23:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQf/YPx7U6e6GsdT60aoPtc6E0Jomva2sZh9RqsUSOl9yiMu
            mjsC9G55FxG5Lknpl6vABm+MDBoIV9/GUim1gXH0pUCw2eFDq/lKzx0O47blpeN0
            h2Km6V6NRLia6FbbLx4gQ7oelh+cRsSyYRdJKU0W6JH+7qXXPJ0nVu2bgWpGcBOY
            aUqhis/knw+q4RBRkl2BjrtPB14DqyFsazzILwAfCqHYszEIGwL6hM4rTZumH+kY
            uNjc88DElKASfGsWmQeOsjtCWg8BwuXzTKnrxrZsk4Q2TgCCHERX8yGlZvwPTYLn
            tjES76ujAHenkxI71QBcTEax2WJLeSSjsvV7jY3WHdJeAY8PZ4g1eopXhNZ280P0
            h+6QIHfpjBSUtZoE6x7ZabEjocxcV42wVXTWdb1fiyESvgq+MJwuhkpPpc0wYzuv
            wkbXy+mtj54LGs5ohq4p5k/rc1RVsj5vrm6ivUcEbQ==
            =sZu5
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T12:28:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/pHJVB+8SuwAQ/+MFomincZRC0id483jpgpVT1AX7FIlND8FaASUqZYa2M8
            XJEOo8MpeDFi2xsskfEeBa5RX22waskc252im0iu1TTfCY3RrU/hmStt3jAqVtAH
            JMv8GtLBqhuBb9SEMykX2CjJnv0GxfSzVP+1pNqNqLkjbkb5KTueFbfZnjARYuXh
            vqxoEUAjRXLUoYRUXWmGlzwTO/x1n2r2cO6DRlx/eVujUf+jglo2x447SQLHcTBi
            +ozSakzFIr6iWIKU/EPMLwlvv9HKKoqHO+XS0E3T5SrZwt7a/viMockamPGPtCgG
            rZbD8tHtmqOBv11DFJYaFfMFCh7EwpHJgThNeeSKZVVBdDmzIbACWK8TvNNJ/KhP
            KaCl+ACBPFY/4z9foeYGpLYz6kxXO19ijUc0NybNvEISliopsSBcbqNlr1peCPO0
            yL2ezWBhU7ejL3OH77yyuIBhKlytgzqphy0d8cSVljhMPskk6nbQquVH+Mc5hiCz
            qKsTy4I4HLjYJXkHMwtd6zxrNZWHxUS+UY0PHcRNfjzhBORn6ExqWkp69toPl9Lz
            ejJ96a6BgakaW6fE0MOFgqc6nuP56qyVKjNBzIiLmfUpculhLUoheCgPCuOuX4yD
            qq6lTFLl4MQ84qUMEUiTZknTEgNDR7DoZfdZuxmwfL1+3dvNo0JZsT9yNd/BLInS
            XgEZmTEF1DNhlaIRy1nF0NaxH4KCcZSapxSupzgqB5oIlNDTRYYWZeaVQpBmq0bv
            urJywckLuaL221f2e+TveoM9xeDhKar6/Sid6O1dBTaNuvUwT5duX8zeGoJWKjM=
            =afHW
            -----END PGP MESSAGE-----
        fp: 355C11B55E83B15E5CF6366283637FAF9D7905E1
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/JEnAHZDjB7AQf+JugFiJsVDtoqBgWlR1YSDtS/rNnRzlNkRqfzWXOwZDKE
            Y4TGYjOjBCZ4kST0GB79S+y/yZaTuvW4oHuCIFkrkKqHWLlPL83xgxSE/VJw/O3J
            ZcZpniPKNjpd/59yFH+dK/SZ0vTVHL+kh0XpEhS4MK5g3ek29AVpTXqPThojBMoL
            pOWmAym7zE3XXbBm6/Pvp3ViNl5+CpOCg5K+yzpLy06XFwhEV6NCeqqTlsRVykC3
            0vMyEjJgpE7jW5EXTb9RYYt+uAgTXniISZqIilB6nvFNtq5tX/d+u56ysWuLfLSK
            364hyVy94S0o57sZKLYPz/ikYBCA6N1z9qZVBelgcdJeAeYhntYJ4mqP9VwkjPoC
            R7UmM21qdSs/6hK0u7O89Lsupc/AjFODCIowPKsGo9Rl/DWEXoJJGSGX8iQO2083
            nxjAzbi1tdsqhyIoVl/HM2dURtNT39sL9W1/wpWcPQ==
            =WAyv
            -----END PGP MESSAGE-----
        fp: 2A25DA15018235A6206921952730D7A70EC35190
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6220UozeaaQARAAs1sp7fdTvMGfrqZkZaDchNkfYe/d77bTUJuvC3aQfcDT
            FhStV5SaeZEDB5HCt7ERYI+DRB48wQgpr80u4Gz9nuAol259fgNp4KKh6jYLu2ay
            8tuC8ppxAd+Z6U2FiNa4uuz87bOKL3pokAzBaldZIQQxDGx6Z2UPQLUW04SeeBQo
            4W/KCyQWGysVBzTjzhYUiECD3Tk/fPdTq1ZE9MNAQMkvQPUlj54+0JLJl88hgP8A
            RtzDLtl0DXBAoZfymvTZrZ9j4srLy7laJ5IyVeAdBoJ69Yc1XMLl1qpEv6FQYoPg
            QJrOXvY5xL8W+zXCnAShQxEPX1Ynh+yVwDg8h8KDCRbR8cw+DY4NsLqXuPNGY4y6
            mg1EoPCBvcQ78SfYh8RmeOh105R7Tk8uk1IMhrjAXJxYPN4pubX26ZFnXicuhjIi
            q0JYslnAIvbuLkLqP8GJZQeydo5/ThBswxv2DrNhXdTSRXxpTBzHnlRLUcmnEKW9
            mUyIwyuQZuu0HiP/KWrut1ArLBwkH7yL/s9mCes8Kt27LCj2CZWk+2yNhCtkBa+Q
            LSjLoB7x7pk986C+HvisKgi+hE0OrTM87y7Ijg34HynvrDYkrzU/BC+RRbQ5C16j
            e6BlK4Cw/LKlLMyHGq4wXT04EpaEUdQ4PleD/qb2hCbzS6lj3miuumQaHuTAX5fS
            XgF1Omg+FqA0qs/34Fc1hQbSWVweDlrqGKEWQ1bPKWGunD51wioBfahV+jdEakAB
            iB+/d2tvXn3LCHZVdPUkT2ZEyk2G4MULndAPgniDxIz4tGFy2VN7l9B41gngTIQ=
            =oSKL
            -----END PGP MESSAGE-----
        fp: DA7B00C8ACAFED2DA7E33D1ADFA8C968E1F69B13
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx6ne7Mq17RmAQ/+Lblmmap2RdrpzNaGRjeC+l0EvyCUVr/GlcvwpEJHyYW6
            Zd/9x6DzDq7VyUPRVWGMcVRPl+WOR+mbcHQMe9iDwOnpHqktWzDeUfNbjQkbmVxv
            jubWDFQmPeeqAHVE/hIAmjqwOwcSn8xLlKinMToPcTCwKeMe4Nsc1Dzo4k2J1Rv/
            3r6kgvNc+cPsKLbemMu6kumXx/dGowvx4ltGcn7kThdCVSqdNerkp8Km4sRktjRi
            Effo4lOid71Yp1jiEp433hkXJDXCoikuq4Ec/NkkqrmpSNHN1SNbyXiMCCCNtVmr
            nGgUNFW7oKN13ZUR+waTGu5BwYXBMRoF4qLdohEhLccJyNJH33/wP3wmEz6dao46
            eh4PE63i7OYtpKFztYsZpDhCGHFpWFQ4grigH9js3Z1TgbqlLoRksgW9hGXR1OrB
            KQSDcPVKh9bGhe+DUjYawnieBaMGXQN1y7cwNZN1fL5i13hnAemM9zBgd9OvkZxq
            gBA1aYJKT81vk2HJp3VOzSKozVpFd+/qChpOYrZavbynaQN1zDexYJlffs9nGQ46
            W2NMUsC0tymNgwhjwnqly3P4WjUVhBkwO2XD5U6Xp5AJyIiqyfwREkFNgXzSstUi
            FvRopuEz8HGYv0yLnVQbbo7AymLvu99gF6h9GtI/VPvjpsJyaSqn2T+nQ8hIXmLS
            XgGWIpWLE8Wg3wP1WRVTwRp5f5/0dmxA3PJ3QeY6diMZm58bMJck0pc4j27C6lBV
            +pz20FhDytdsVbarSjYUKPVehKxRbu9+ADxzqpbq0ovBQLeVeTxvAf8gS/uicXM=
            =Fu2D
            -----END PGP MESSAGE-----
        fp: 911B366FD384B2CF3BCAE8EE01F9B7BD00DCD57B
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75NWiDtWcDHARAAqTTyZondtNoS+1XxQzTk85V3DoXz3/lLdXuWgNKfzERA
            VXIO7wYiywqSEzpSqfyg67N2Ikw18hvbECCrVUmfAdiOPbPPCsx3IU5CUqEd25rR
            aFJMAdnaEzyptMuWsMzqshQW7eTW9Fbf1cmDbH1g3zk/+VRjPfd60T1cyQaNGmmG
            5yOCwA1/qnLxBs8O1xL1YOa59toJ2nQybqwDyk3SCyDgXl105m8rAW6VzmzlwgGT
            70xK+SdluGomuNVX1163RifUxqs39dMPficUFY2yHs1a6ZS1CaDSb1HNHl+jhrnU
            SBZ2R508v0XANWg1pUiHUEqnW9cC03uoehduSoNu88gqG0gK12PK82Vlmun/MNoK
            xo8/KwcXFoYGqSwaFjAJHrsf9E5WijUnZBp2SeXMNJQ+nMuGbUpb1X57SRhnB6cv
            27PF8QBkokuIR0Kj0y+KnM7+I1EdHD2x+T+fmmEpOOZl7Yyz+SNHB3v+eZZ17p6b
            cfqGLAOQHLRNsKbg9WTso13rUuP+rfaDvbYwY1hpvkIz4GeUlVv+eBpikbd/ShoD
            Iwnom7B5W8U86NsEx2l825+/z+z5MfsfA+vOJ6OrTBqqKHP6KRLMMo4kyaru7P8K
            GDqapQrcFyzn7dABJy+0ce5wsHSJ/IV0eysjJ28/ibDGSm2fsPZ0CxfJIH/I4UPS
            XgE1x30zg0gAnRI7F853YSPBwNntnYIZ3V2oC0LGbLD74AQ/hozLqiv4uyDYaIUT
            YeR2attPvy1tETnDwehKGJDFTZdM0A2JVmmfyotNSz5pn03leoNvtkBSzV1mQJM=
            =oZVE
            -----END PGP MESSAGE-----
        fp: 4A4B9A8F518CD36766AF86DE065BDAD92D70F679
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/haI43zIlNcAQv8CyqX9OrodDx00j6boCmI05UHUBhDvTg6P8l9Tna3pnvj
            3e959P+TvFARf5EeSeUo2TL2j5g3Kd7PLDoF7n2Bm74U82mvmP1qFyiZfpBeItyD
            Zo4G7XazpjPIcEjVgGwe6dBsOmBFfw97uskMslzajbNkLf9ko64iwOWfULml5nSJ
            oExB5h1hyM8vUn9rETzQ3oHrm1fclJ1VAv8xgkh2waWm7x6oyk9gW/XVl9QsbIB5
            NoxfQYfrkXKosLMyF59YV1QUfGhvdp8aNLPnKjCfDtxeK0F6dy0BH9XN67mr84b5
            EGj54zC83BmkaluKrhMxiJidXzrndHJBPRLKtOYvXjmRRyPUc8eM8nWf4sfM6C69
            mdqcTiXmCRf+chaL+0OtaEHpE3W77dZumrQ4/wpJqneTg6uUFEJuVx5dVMzDBg1L
            oZlNPN5nXMq8biDAMRBS+KDS3DaLO8qgZg1hqI7p1b5OZVp/l5BvoBgKKRd9VNUP
            25MOs8E7e+idthrXs5Df0l4BqOS0Bnw0skp8gx26hXzySp5fcwHagYZcOloagogl
            LMhrP+ABZYCyULkHv4bhGHa6/7tyQkGVuveXSemJfNTDG79Pt5Z5EdlnfwWzfb3z
            N3Knw/4V1aMGXlrJhLRz
            =9f3K
            -----END PGP MESSAGE-----
        fp: 6B9CB4956CDDD0599A518BA6CFF195C6AE9E4939
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQf9HvyQHlumhV5m+VKhEe3pKxRKOgXkmpNXQddiE+AWZyMB
            zM1pa6AcLsyAbT3Jgs0xnayXACmJOpX9UxO0q2W957nA/+dp9WiqSNM1g/Pyx4no
            Lb0kNzWeCI6hXRuYRRioeXJRMFwJkLYpQ2B5QCVFkHw6VKUojiaREayqclL8USy8
            st6u/nUUKbNq86YuJXnrIUnskApnyy1k5IAzklxQZkGHU3eLHkUErzP+IuYlH2A3
            8UWKRzDlJvC+Z3YOrDvcZP3enT7augWLWLNMj96lS1UnPK+0hRfnLqvejjXcWy88
            MIDICbCm8KutmDWmbi3W58tIGgMK6RArFlMFv9ReI9JeAe+Xx5mqXgff7MOLpdiB
            22aOrSQBoB2o0fI/WZ1zO0K6tgHFwyAxVYz9aXM1d/nHo56/bEGH0QFYgLLsrs2y
            ajQvqrL4dLU40I7t61B2t98AsnpbqytnLIrEstKhfQ==
            =CicF
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    unencrypted_regex: ^(implementer)$
    version: 3.6.1
