tssc-config:
    global-defaults:
        container-registries:
            registry.redhat.io:
                password: ENC[AES256_GCM,data:t/Y9uc4ElggNOsqfpngbBpaYmzwXSPEUvb1K/la/PWhlkp6Hndsyo+iHAdL91z7dQU5twDtmrIDMBVKvUBYz1DVlqWQnW2KneG5KkAjU+DMwFEJ/Wjd3jFOP+gVHMcl+fUokQjVxy0/O7hz2joTmUkF9Y9VrelSmGE2B0xoQZSOEExIENUSvoOmR8z23QqV0/Z2uoX3YOJ7w8lrh2Z/lBMoJXw6K2pkMoFJ9xlLWcCyluMBg4PM6w6M18pwk1Ltih8BRVOmGqyQ7Rdm2wPRcAnAxPpru/qVoXXLHykwoG5J6qXxP+WVjb87p+mfoY68VcgEX1DFz7WW+yw7/Suqcgic6eBW2IPutjZMafb0rCuHE9IyswwelyHA90sftSuZFVySBL0YL6FqnCo2+eDhFO4Kw7agDudALk6r2ccVbbFP9LAws92iO5rLJuY2PyPDghELsN6kMP9j7XVnBr7e6do8x0HOZebaVWy7ygCWeQ79yT6Aw/l3Ac6RXfzD2Wi0aJy877Z0+VwYdhs+64gETq0WVy+PDfMYDVFh5hQaTHd6c+5CD0Zr4WGbWp64CZ3AjZanJakQ/E1M3zJXaVfG1luCgqJPuVfJwlPy2k/A+Mq+DHQgae3hWXAClSaPVAjzfx+YHcB12xqhcBSElvsd/2Jsy6XlQIR/IzJCPZWf9DW+TJ8e27t1Xv7Usvo00YuQIIdHLQ6cXGHRHUckptr6eh/7DV2XtD4409VPB+KIvxc8Pr/gNwrfy1Fz1i/8hfqh5PjmgoeQmdd3r9dFbwWIDwJwuYZ4pkyvB6epj4c7flu0Sd/EZbTV0sZWoKp2oHn+CsJDSumrBpfP/OK0VejVMj4naqv63fUst3rW5j4tQZDpwc954zhSkV92U0pv2nYwi6OMBxJlYe/vpkQWR8Xj6/Eqo7rzM55IAuRxQW16A7/Qdv+Dd1Dv0cSm7y6bDAIdrPpXTbKBqLKvdaiOAtL+pRcL+p0VcsC7aTTQGGt+jA059Q1lsTNL14Jk=,iv:93KcZ3bxvwzE7O6nFFSs9vT7o6XpgoayrLu6dE5X7TE=,tag:7P8COKWpC6s8D6/VRaH5gw==,type:str]
            quay-quay-enterprise.apps.tssc.rht-set.com:
                password: ENC[AES256_GCM,data:dMK//3uGbG4FGOXH6RvJE1JOE0icSh2vGiVd//18Tz6Si0iqQhEeuidRWNLvkvw2I9KlFX5R2+m9+b7BvOhL8A==,iv:mR8l22fGvXhshcw7/xDIYpTulWSpYPWSj6RO3hmIgqk=,tag:1RduaxfYe91Kmv90kCUkPA==,type:str]
        maven-servers:
            internal-mirror:
                password: ENC[AES256_GCM,data:NYdwD3xTTMosFgcAdas0rMDT,iv:+RAq6DyV0SoIuZnl4FLs7RffTBXkX1epmimJFrPjd1I=,tag:58KEck9GLmB9pW5KryWXOg==,type:str]
    tag-source:
    -   implementer: Git
        config:
            password: ENC[AES256_GCM,data:wbIoAyxaTqSecoDm,iv:toZfJoC1YD0ITJLyNDMNfjNwmvGKen9uW4482EdHS+Y=,tag:32Dc5KfmltA9USSb85BS4w==,type:str]
    static-code-analysis:
    -   implementer: SonarQube
        config:
            password: ENC[AES256_GCM,data:SzmqYFtFd8TpW3Vhrq6emKtW,iv:8gQcDymaM1vEShKnqj+T5piN3WhD0o+hH0vsa9S+o3M=,tag:1Ejxo+z2T52l5XhZQ+ESiQ==,type:str]
    sign-container-image:
    -   implementer: PodmanSign
        config:
            container-image-signer-pgp-private-key: ENC[AES256_GCM,data:aECxrfMCdm4OXI3fQH/eHVsdLeRVDR3LWQqbJ3SJHAWpteGlStuXMclyPSO0vgmL2m7rPSvq5xEHCc4VaRnXPKQCStIiUPrYp6Yw1OBbnuovKjRNZVF8NvWDL8lXv7v28Fic44tz6SMJV5A96KhCQwBId5a/guAGtfMi8139+v+AgblyrQO1w4rWTYE2TUDb33yjHWe1LvftOH5pvZTBAz4NHId9rLXgvF1c+KcH1el0rKTtj7GN0tiv66by2fjuZRgT5xK9V/kJdw4aEyR8GxM2xAFa8Fm7JhY5oc5yaiUCzatXEkzQlyya1orqbxLNCLrY3iENnaMJe/CCc1UYmt8oMd9gpzGaks6gHY+gFrxwSWhATggGvOEQfTZ9aPu2oINEI70Y09YiPni94lmAO8u5t+mYRkoGR2vvDS4MnrjNX6Wc7snne5/5lSHaCjIXYMk2zkZ+rKFrl/L0IufNrY/5t2gNP23zV7dPOGz0B9bOVuUoZuPrjpPorQgdefReOfavxYWWOKOrBgsiGe/1ed9LVhK+gX8VlrimaJHz87go5z/FQAPRXr30ZFb1LgVOj0C8Zm5ulZrIo9K2CxbA2KMXWgWDwRX8rX2GnqhzBOQJ90MmDvrOEWroYNPsIfaxrevVzob8BYfXz1o4Oc07INpFihqv3M1rO9/QfAQCYV42Pa8+C0h5eq+nr923cojho4GkTDkVV3U8raxOh8xRd2/S077993ejLlQF5pL73o0PbQ48zOeSAqgpxC/0lfn/hjQ0mpdWli9V32QEPLgAe0nGP9tUotLtHcLeEZ6PyIXbidB8HwZYFZHZkUffuSiM/gtMU/RXnNY+OXENuy7iDGX0CLWkjNKPSwqRlAyB0f7EONxM3R6cooL374UeeNB0q1wIwlxSG71Ya8Xs39ZJnO1rC9FW75uB37jB6MBj3XUGebkpvZ01GP1vNnClYMc/0xyApQZscVdFhqSj8nE31ZCWkFUzv42JG+OHJEQYUE/fUig/+U/2ZpZjBOHXW95lZqJtyUaqcSgGsQK3VGVYKDgSEmZO4s2C0jSdSkpuk2C+v4ioQclC9v9I55mIkBfC/pnoPLgQP3zjNJrDKGTiesiCjkF5ksWfsXTerZP1tfIXkw9yR2MPsiQk8oz0ab2KQ3RSAbvC/fxM/SiA2/8MSGhcK2IGFxW0rgOYNgCTdekJV/IAFYzDJSPwdYU043IGLfTmnxZEs7ZGo5yYjj9hqJoChtCWucm4YpXfm57jFL3EMyTe+KyHHjgfuL+5QCAtZDhyd4HAjfoqIghD+BKMiZaIh3sY3gCl5CJfKVRNkxAxZ+22KZnenaceQmEpXlWQTINmPZte00qA6XL3b0d4aF7IcLugl745aMFvS3q7c8lVWftY9Mdx/KoYJ55Po1ZrNXsEVdirMq9eG0y6Hr/39AHskdRF6J2R+CJgRur8KvkVxJMEZ8FxEov292ccTK/1YKTZP73tVyyspDUo0BzBGPZ89Ol3kUdeFj28y5z+xXQLPqTrxNmcJK8rffd4joNvGFDiC0QrDQW+q78u59rbd03UILkgeylsSZlMpikMPok+6W+bDuV6rRopfO/i/W7wV8jxm/L/KuMG4F6/ir+h1v51pfScEwlRCR4Z7qYecDMIu82b9JHukt0qgl2rMdiZPeXb30x+fDz9MhrOTLi9hQ7PZ/zPPzQhhBS7cl+FNShcCbtZT4OS/orQzKmSoIdnKe7ySQrKoxgzAQOE9ooj4uBGZWl1sJ2r0nmkqxlvzD+umpYoOU1nuuzpeu6oEr1jxxwcrpf3yV3liGknMChLkKndGIRFkUU0PkXhhhxJFvc5/RIuTBU0PK2kQErg/Nl5AEeyjWTwrz0vT47/wavNCCllNlarPJav4dBxb/sY8tUZUH5HDYfE0HONkijFNw00MJz8l++eymQWHpDXucJpUFGJ/5MCOTQKMQZa9G5/NANy134VNZ/t0OwPSv8mG/bmk1KRZC6sdms9kVdNTlJhA43Pg+1FG1ZwQl5eRLCdeGHAbOPKvsLDu/4Nd+OtaUXUyWE8nrAvpzowAimQs+3SIW/BhauDVJzQRlBVdl4f1u2YBDjAnXBUwEX8iU7QRl2js+WuZSsWbWGPUIMc1YsCjoI7YQkbsEwqceJbDarPFwJcrbSJY/OTmjONBaSIbg6aewws9uEjC0bLunjSkJZjRIgBXmK6iJWBMyGbTGHnoRU6cRvWtADMj3K8SXj7jV1PG47AeuOI4BbfoTJRNp6yWxQ0VNWyrEzBpJi/k5oxkCMIgiilOAs0bqx9ICthdmGuASl5pt6PEWxvWyrcJWQJ8KVVKmHUsO96Gtbi36fzLiUa68Ku4+UrFydec5AyKsNvtCzL287FZRiUdmNlvabQkJCl77hCGzD1adFB5pKY0mmNO9VljIZlcgFTkn6q5O6yCCPsPphw3x++u+A962RuLp3XXj43bKfT+6lUzKYENzpC1Z3MvwqerotJsmJFaqcYvrM+1O2tbqjkus2sn3mLAx7AQOTSLaaRWuJakm26O19LfN69ratn/YtkWDBZ62LgkL9r/npOW/J0LI6n9bQXernhZr8SQpQy0K/2R+at+MMCRySuHn2GGpoJdj5o2ZvBLNsTLxmu7fypxy2Mz3x7elgARfuSF2aUJ7/5gLkxHO4dh+hcMQRinImpf4sA70CtdBN5xe03cfHJm8/+rOIU6fBLzD+Ic6bDqUl6QbNxvr06lGEleX6ipYW4P6+86FvPuU7D9jN/240leO+bDY4h4FRNift9ONXb84E3XfZp5jFcgo4B+d5MMxcfNGjuJeyBydg7r8TeEWnrIT0hakOjF6/seMem3lKYeBskv7UkidpegKVov2FN1+qAbZA30LiyDVTCPzKyNEGwhepVWW7OUduI6Gg6iYxRjySOmA7uqQ3arI9I/7pt/xwNErSjzYP7vfpndGUomDovLj2S6ec0yQdeueJ3qVPumc7wKg3HkeRb/EPS4ODqI5WFu2/+a4sJdaRNH/aRYXNH/aYMfvGKmsZLtEDW6NcV/W/IA94J+yC6kMyBIbmoZ9KAf7qztFgtE0TRfIg1KTa0MpYuo8cF0GvoWykLusVW4a7RDHH1gj+GxxAT80tpUxd6vjGMOXrl2Vs2WrYXnYVAbSTi0ag7i0KUeg8zHUSSMo6xh4Qm7gJ9eBCf50yLB4Ht/FqG0cFkxZlkPJ+8x79VwpQHgJPjeAwRioUlU7+vdSOBMiCLQxzol1dJpBpohmGuUIXB0f+AVaXg4lOlmYVbEajxLcHinFFNnkWjMcdVpO5l7Wtv2nU5kCRoeW0bdgcBVRTHrE4LChy7ej0/lIPvirzSsMBI/2ArvSuVaaQOT6KLTSnldthVZFXaC0qEblTKk57RWAtMZ2jnxEvQebj7EGGywf+C5a+Z8GgC4IJxWr2ZCSbRumFq7vE3hcvbJy72jejEKylWw1ivrGLMEGfC8HxFn2AXPRZl6BjetsHCl6aMSQowkAmLOiDQTzO53BusDSmdWYvxHil8vL8wsYUPtW9OyU16u7mBFtGXtnNjWuk0pvD+BSRGi1K8VlncJvpfX1YAI778t/zvDs1lUH629382CB4WUQQ96G0I7PbDVnNYMF11AlzJrIxNXmGFMsIUCqb78GJgFbNgylMn76D0CrGd326jTBkWXOK0rbWesEJtCm7iiIUjyGqZ873/lbIsnd2v8jWgfrUUpVJICsaaa1UjVfS5VkZiQtvtoA0ZnAMQ4Ly7KaNgS/7YSlpXbJf47FCBJG1qRivoO6myLhPaIMjXFSLnr4bQrJOZ43OOQZ3Ev2RSHGUEMb0eNw1LMwl3AO+WlVkUxHoAWJ47Sr3uWyMdz/Sp6Q2vRHAzhkQwhjCoitARZ1U1fsOmkBMalafh8wZv8vkKPsTLbvI7oloKa7c6V2puS9lZkEEGrbKMMjd1QrpoyXsHvG6hm+oKfdrMRfp4LlD+gx2VsO7x/jRQHmDd2yLVkOFyH9oVMxfEuMOunoFaXg+4meVYyiEoDZ8FYLi6hyqAIiRtdhEou6PZgxehQsKR/qxdZiiZsiE+tdCugOn9mSHMROw7TR3SWcbh4Pp/g8NUJ/dl53w0EzmUWvmrw+MWr1JMkkrCHbw8Wf32+QaClUrxZWFHrsdlQ+Qfu0GThkpAauO+F+Ejf7WUz8sy5TcINeheIFHTLB1ppiO5SGH5ZNYo00aORzkp1oZIko435ZHe3Vd35wJOBHVH3bcCjSkV2/QEFJRcuPEhCv49cz0aBxtukPh1wYQQYjCnskk6s5VHsQ2w+SlUQc61H8VMTdyBD+qaoCDvNwfpW2n27ZMP57SPWS8ZJT1nU/iViCO9sK0vdOf4sLjr060IXozlYNWaBnaWIERwPcKciamL7gZnYFxAjJQtQHCGMo5U7kGP0exC5okbAC/iUZmXfNtSEEjX7fhiihKqAhjNBLTki8Z4xwBY01eBTHn4kapGiKSlONLiqPQfOySYFeAzNumgpgxOhtjM2q02v7l1jP8XOnwSFlV8NfJ1skuyjSe0ZgrZ1zYbVLeO5lsL6wmYQN43z9LplSedyJDJNN8Fno8HshQ8lOJzUBrP2BnE+vs3c3nZJhrQTGZmsQ+aO1g5V6iucbi2t8JckyqzZd8znJuvLqD+I3Zt56UGMIYEq1bQQmpa+IdO2ktX6X4C0vjojLIEKRGe9bMOAyg69oPMZSyFEsJsciktBHxsRYs5r+RNgnDbsPN3NnCvEmGbk+pdDlqzTqjvABSa4HefoWdVMtsfVnHMJXOZnROQetU/ErdBdoSHx42HVFRURqvZSSm36TbJtwuG1r8hj2GiDXBMXdGCOoS/AzoqyBMjqANwBqgcv7O7yXByjV3Ex1uLH3/1m5xLjO/VJNXdRUtzYAzXZ8LDdC3vV8Q9E0vweBbgTNqdaITm3tczPwpozSYR6BJiJ+o9Z584B5qe/ohyggvYvHKLjRqWmNX//YeDxo6Vpl+GpawgfN9zKPnXD1qRO5kqqCUvSdUli0BkX5jt+DBT0xqJbKngSszltUX/GRdlFhXGBtVwv9+XYwB487DElL5D+JxSyrr8zUlkN5vN4ilzQtdmxNZev7RLviT0MW/Tr8Hubben48Njc4gDWGtK4fdmPX+CPECNssbdo3IlHbEM3OlIToOT2Kj1XMtKEflcew/hcm3l/shg+jLGtsBRdyWwADC6yLlVD3CzSl7JhpM1jwnM/st6NYbDxivs1WjIgtfjxn670riIslMbuU3Lpv/6P22LyRQMsSfo6MiUWrLt70gpcH2+4b7ldcNW++aTxCQtUAuiWbmEpDDEtFtMim5ve7hePLII5Uy0jTwtUtOhUSwtjGIxWJ+dqB79n5ktiMqYZLmOBfRQVWIrlhEmKxR/rAmrTiYuMUnvzP+ApxxoMq8Djb+9hHPUrqp/IJ8+HjUDCDvcx3ISNe1FV1YF89QKpr3m7S6J4idxnX9B6338bzXSxrUPFq8KOiQPYPSetLgtSnVHyI8MhCmfs8SKEulIOgUSPZPtBUTOm0BNSIWNzZuTYKzGAVWWHD3M1JtybU2LOfuxnKz25h0Hi0TyPwAv1R4jLtZ5nrDbaFt28KcLS+hthz8euMOriwBKYPo2AgtT6eYRmFmfFoyT08PdSXty8gGME9zbKL5zSas006L9ap+h6gHo6Qwg1sPORDB2A9y+c6L8lN9vnQVMGoE1nZgG2WnPlLRNv/eOGCIDCCZHrdfPfpZyExCJrZ/abwO01Rwnwxv0jzUgCBCW6D5cuQOVcopFjYvec0LiH/wf7UxAF5PcaHwxxq2EFn1Xi1xlWVUeflF0DQCIeqqWKHnug4tfj56o61aX16U8iWoiEf2BzKCfEMD1OkLxgPuQKUrkulFq+oiVcjHJ5SJRsQZIc3Gsncg+q+T3085a+JLPoK/OF3TUwWdZqxtRDoxsvEKT8A5/KcsR04PyLZlEH31NMd9P1t2aum5ioOSFwLGKLrNRQFyrwJAine8BQlGBIVE/wK4+W7l7izOV5ET2N1tSPSvgpJX9+HiprwT4/r+tikMRMsEirsGS9rTFeP+F+M+IXLM+GbXYU/hsNaD5RmPsF5QjWxf9Isjvbl5nBLmvmbQLfmXZVCIWuc926UePI2hYSYIUtbBh3ySTjRtqnXQRSsEEi4yPCmMKlOQ/ZimW6gB1kZax3qf0ln/8XjDXp4NMGGQe3HVak7TZlnflCPOj7r3YAGKKMEdlRZWi3P4vY864naIqJILCm3mPzl3bYMpWNJafxtZbJKCCWEMcNLEyTs2u3I0JbeD39tQyYynTAPchw09+DaWnCyGCNc6XgzBn4yWcyQk6YQhHnktIO/iLxtnSwLeAqlNJwT5L8Q1zNKzxuSoJWKc/sMUKZ2tB3JniDLAd2DOkY0r/gn83gQE3+G+8NG5s9b59rymiFQbYeRvm8wWLxifU71Tz7Nn2VPNwwT6QZbBBI9virwJaFO1NZzgFpVTillrEC4Krn9ndIskut9yaCvpu/BrMz4qfbv7qm1gzuQpnnXfiYJ0W8jnxUB8OM7yo7+UtvJCuEr157nzHPHJa0S2P+yakPeQ3cs6Cln7ohJos0N7zj1MzOIDTBIlYgJiTzFj2Wl4K/+ZzblSBuOSgEdVLlZsfQrfyzSuaqEPqFEntWu7BJ8zwOV652nWa77dUCgAdjGyypCqiwkQlfMOhDXiTeU0lTTHDx7rc2EZ98/fr6Cxk4Mc7EU8dpbZ0UoTWCN1tUBe4HlpA4VgzxIQFJzf8pFaySM5bXFAU4Bo9u8Bq9C0HJhZFT30CjSZE3Q4JD9yT7+E9qaGvHeB46bKy85H50PkmxaCbEEGoacUzmqUj9M+QUGw=,iv:JxX+jRPVtt9/V4XGnGFAMRbaTf5CrX3i29b5kLiv3Vc=,tag:6PcvZlrYzaE6Rg6TeBRCjQ==,type:str]
    deploy:
    -   implementer: ArgoCD
        config:
            git-password: ENC[AES256_GCM,data:qC7MnBIWQcmYqf+B,iv:SLrnc2qH2P6n4hhEIOh5XC3MyX7wxuUswHMvSJglVq8=,tag:wjBwALAQhvgLioELPXU5KQ==,type:str]
            argocd-password: ENC[AES256_GCM,data:4V1dcfYd,iv:th7hP+6NseHk27537wS98XBe/kQta1m2jnnxHcHozHg=,tag:9Ag+brIxdkiXeFdeK2EMzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-30T16:32:32Z'
    mac: ENC[AES256_GCM,data:GK9as1zSc33t8HBYhDpANrHL/doj0i932bMOXj2W4uZxomy7c5Gc0+ncBzj4DQD2/hXO4rQk1w4N0PWFxlJHriCGR2/wbydR9r+/CMJmgu9gsamq3jJnJSp/XKpDQy3tE0RNtSTVYwsY1ONTQGFqxFqTl3UbnG3odz5sQ7Tkxt0=,iv:iJHNDfeRDF+WXjDGNvZ3aQ6Ne64wEJfvppTkJ35EYV4=,tag:gvDu2lZNW786cAqt1EX5uQ==,type:str]
    pgp:
    -   created_at: '2020-09-28T12:23:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQgAvwSrqVOFtdczzC94Th05/FZ2K3mRCYcNwvzEi/a6jsCb
            RbADeah2USzSD6Yqb6vlc4Ehlgz7HdKf5tn6R3gufg+0HJ16V5Ic48EpXNA4RPZR
            vebZG1xdPHQo/cMOSmpfg8Z/IaguSlS+I36W1WO4D8F9LoPkmHKSbT897piYbaim
            iWUHouG5PFwZuObvHtM/35GwMfS4Ui0FdZE+wCWvbVJcM59cokS/KX0Hn9JceJn3
            AlCBtlFiMX5BtyLIjRIECo88/AoOLJsV1jXBfEI8hM2AzShCD37t1Odw35n0fOUy
            XxW70B/C1Mzzi8XY+rPqYG5Q1tgIaHieRUDe+ugOzNJcARUeifr/2GdHAvUD1gJo
            A9vS1hsEqLW+nNq79tP2L/AgKWgI9+MWCCAJXcpPTi7FHqSghD54xsu6RNlFSlgP
            2dKWwENNjo3Bqk1RWmQLDb01OQLUOGjA1KPxASw=
            =CpQ6
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T12:28:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/pHJVB+8SuwAQ/+Ly5wpkc2FfY0YR0i/ROoFgBRbz+4D4qSN/qkG4zRHg3R
            KKI67wKlXb7ycsHtWPnn0qK9cWkX9+m2263w2yYt6wpbJrtBqRAxmPPbQn9n1+/9
            ISdGTtUhTC02Pyh2r2crWn8dBUAd4SMGC82IKzHtBxv4r149/qgLNu+2udjSkqsL
            sNrZJHIahvlrl+F96YmJh2XhIH80lIGvPXNKo/bv8ed2ICT6juVrRscEblAH5/6T
            LleD1dHLtW1DIBoCmY40K1qsM0vwN5lMcvOtoVSirU1cLYOrKvj3i19Y7wJLrVk4
            /mR8VLpYwz0e794qV6TxvM5gGFvs7mzqJ9fnBx+ngClManmJKaHituCQNASFXGK9
            KaBMSTcfV7QnOtcMDR/Op6tmE1wc5tw06V+vqJtTfY/mlvpHzGxqT1zoKIPZuV7Y
            SJR9WPtw52mwEh2xI9Ifyuyf5QKS2aB2QeJlAWuWsZHUnIGuKsPKbgo7DYRf4aJy
            V76SqPqJoZl+WdHNvOpwlfsiz1RqUDDsn4jUNC5V4TzHLXQcsUwuXS1+QZ+xKlZ4
            gfHl4wQYxWsxA10PdyNT00Jx101JAY1WeOsoB+sTUQlDgvAEZGhqlvtz7lfr4+qL
            P5EOzzF38k5WBvtKmDTKzxSDyeAuQj6wIVuYSnm9db5AIWPwYd51vovkJFnZwgbS
            XAHbliGg5XQPunRxzVwY2iKbWnYrfZIC6c5Iv5cPvr+rB6+9G42Ub+QN/4A6wi7O
            d4WlrtG3iuRcXXlCEJxpdfJ8KBa/WGadhKX4r7we7J4KUG5/raYh/EL3OQxl
            =+rXp
            -----END PGP MESSAGE-----
        fp: 355C11B55E83B15E5CF6366283637FAF9D7905E1
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/JEnAHZDjB7AQf+NZXpmQ7+qFvEceY/KsAOwKFru9wBkY74S4E65+fVTtWQ
            tTlVTwtmczkOsxfVGJPQuXSOS48JlB+c526Rn2mank2gqgfs3BVP2icsh63RtmTp
            BtHEnlm0Vm15SZ9d28z5jolcWdIzQ4a7d/BAGDgIIeqWotziqasQilrvagTrXa0f
            mRS1AtAzZytauMD822VdLEe92DIpAlaEa0auO/Vac8R2bcQLIQQols/1tlReighL
            tz7YVVAMpOj5a2CpnzgdvbZ6w5WefHfUkutGxuKELiP4rpRHtHZRhlloquGNO99B
            +KcihMt/6dfNIx1MJIKsvuhHE9XZtHynjWHgmapO6tJcAaYpIatU/AqSKPSi+UOM
            V0UbaOUyK1mYAK+Rh8MTQipnJUE6zWiV23EdOKYwWYQmTbfQGDAohLORvl6O7l/e
            HlcqNBkaNX9Seo5WWgfY0FbMdKDj3saiLXbDQ+4=
            =fdkC
            -----END PGP MESSAGE-----
        fp: 2A25DA15018235A6206921952730D7A70EC35190
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6220UozeaaQARAAtk/9evlCxWCDbfKg4m6z1HITc5g1cXBA202UPegZp/y+
            CBSbd8YOGztbL9HY8qzymLwKBYyxouPylTT4+vPfOeSy9Y+p7dUYVUuJx+QVDwTm
            auJsLkMFzPsX5POQuccCYvdLjO8GfjL3K6hrB7SRMbecROYt924pA1cREUg4T4jr
            ERqUsTDtbE5iuD9aM39meVPRQelquo+Y9EjO6A19tRXF8Wfm8YkT8fCiuzvytdhL
            5slQm38yL1k3FfOOjG4QsSwifCYvlL8ki9wmbGt/hRZB6kruSf843d7YMNCLhf+u
            MboJI/E2ikA1lK+oGc4T31pBkS2nAb2rTK21HAeSfXQ+Wj+H5cCSMU8x6omdpK2q
            Mo6ri0qbyeNWcH0lKnfYvPAE1d0fsaRQ5mC19Sf9yV7y/i1SRVfHWQyhN6ZQpawM
            kklLgvpHsnWUk56uDlEoUF+knbXoatcNUzia5/hyFychmusYZRw1Uuv0MoU1TmhL
            gza8zl9+RFZ61oyBBnQnUPY+vwcLv+FbDreAurRuoILAHjv2qi3uGQ6LgpxeOGuK
            cTc/0TlqFjDsiFasMJYT+wekgpzC1C/kPp3uXCTxsgFwrF4ZtDCIEjowJGIrcu+N
            /L1u6ykCSgdM9fDqZL30a9YP7Ce8lwVkSlKJu2fJkyFAUfrFhfQji1R+zUoF2kbS
            XAF0yQCmhWtiTdmNzVE9PDYVP+G35nb4fuC2No2cJSbERc4zoYEF5lRUkMk1xCCT
            s+PQzg21YG3OjBqYEJvtlIAkQ5IhQ5kCvSm9KdBz6QKyarvZYY5Dmp85Zhb7
            =GAVa
            -----END PGP MESSAGE-----
        fp: DA7B00C8ACAFED2DA7E33D1ADFA8C968E1F69B13
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx6ne7Mq17RmAQ//UMJ+8lKN5/A53KHHI8PwMoEc2UaEYfTlsqcXeQ0SMXe3
            T5I2HPaJkf9bAisUnvKMBJpBBoEJLrhx7dX1bGnBt9iFRD0fJ6Aylf3kWyC9l/N4
            PyxJRybZiKbYJ/R9qUZIEWUczeUV4tXhEzbhfLZSbpGvpOwtlphZizh1pUwZeFHM
            fuT+t1/mLR7TbRPQKQTe25kivAhtN/7cH5tghn5zjPPcNxWJ2hu9A+2KdBB89QT0
            Qf3N9irDeRz0k+FwF8OKifSN75RodSQk3fnGX4pBp/HpEHbVGSQdAKYPVpIJbZBg
            6ZJ/2oV+ywoCSOwgwUbIsfCFG5TAApEvX3hqk10GOlpA9eHpFVNWbuhZIA9EcIvg
            YB+utHINrCjBF25f+YoMGnh3M0gnUQMZB3pr7PTuXl99AkeitqwPNIH1fsObvomZ
            sxkeZGVOiQc+UTXOEoGcii1AE5SgfUMgY9Z9YJudRSrjQobAbtV81YLHDUbJLfhb
            1fVsBnOMhzfnseCRj9JCmbo9XZsTDU8bKUK0QYdqqRcxtEXmwnwcW2FGxVayDedZ
            0FMt8WAODoEkgqqvpFo8K5SutUfn78DrJtyy002u2X4wT6/63dX4h68+Zxc64N5N
            cVdyo4zrjbq8OxkEjUnA7nF9ek+p64yWex+n2Q5QLgZpFINYHNb9ACmKnRJ86CrS
            XAH6NMKEifsdQek2bXbypftQ85lAETZO+ccJ44XRM55fFDSNSTlRTZqhMy1ti3Xg
            dWH2QG6q9yIMg6GWNGGqnDQlFmPaXGrPWZNBOhO68QHCMHlWPwmg/Ju2Z7Us
            =jH4K
            -----END PGP MESSAGE-----
        fp: 911B366FD384B2CF3BCAE8EE01F9B7BD00DCD57B
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75NWiDtWcDHAQ/+KUB1bOmmsrbSbp3DELlvQGpCLlx86mtMgvQjHG9iKrv6
            qc+/J+RYmJpw0XpLjoZyA6Bcy9avEeedd/UEJ+0zItbQsZwwnVZ+p+zPD0BW93ws
            xUjqdBNd+jVk8DQSd5ztP9AKt7Dou0mQuNKIFXmYKqw2Cs5DKWt2JjMcjcCqckpt
            lALRdapTQAXCkKVUtJJ7uz76jhMmwNekch6ZZTojN0O/Wf9WHDYay37BYb7KYijo
            4We7/JyBIL3MKm9Z4o6FCRfsV2MqI0t3FesNK0HqhcpyzZs4lWT/YV6WW+23zAeZ
            uwIJ/iF3pHpqB+NylgPZj7qbssprrlSEYBlB6V4yHmv8GvsR6VK3dGPVgi+JtkDq
            sChiXnAEIH6XLS34G/bPPJsZOB5vQ42h+RcK3opplrbPHyFsyagELGzxNso2Z5dv
            L/iGbEjqQucOmb83PJINCA7nweXpXR4SNXP/c9Si3p2sl7IxMLs2tzmwm508uwFa
            NgewXgM/2BjDhPCv6tfad8Dnx1DBegpJQr/KrWYwTJh+JWoHrzxkGDAV6EnsxQ5G
            MT8Phg812Z7Z+ro65YBYoqEPOz3zpFFc9ca1DeWcgZXGuwGUUeaGOoamwVSFgNCG
            t55ZuwFAt7ISj/j22/Irxp5pw8Ukx5/4AKafDOk4o/OTDrdIf+sYAZeRT764sufS
            XAGUVC1yhI2fswv4k2EQI3URDUIFAMAa1q1CP4DXXD5DOqkqP7kt9ysyrsJgwaml
            mTSjrr5gtpPy00ugxVBcOeXpiFEQXJ7maxxr9UsMCVNBRtG9yn/YFyaMf+/K
            =qdR8
            -----END PGP MESSAGE-----
        fp: 4A4B9A8F518CD36766AF86DE065BDAD92D70F679
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/haI43zIlNcAQwAiQNR2nmi9q/7gnkaMFWN4qsvSr5EAS2ZGRrLRVygk5Yy
            OF0U1jpKrg6K86ffVeT7McEHXQSONAJOPmWGyeNQeuz5GxvhKMCIzjr5/b+/0rfq
            kiB4dn11GSZRTNUu/oWZ87wdG8jDoZiX8WEYS3kKXRWX847QSBcT4ndVGVe92vGF
            pOddZV/TgkORyW/inthIfFwPwChylDdKENBZbtD0VFK10vutVyMuZ5ygaAUrwVBm
            QWE4CFuDuWp2jnGsr6p8VkGgl3s3+9H4T3LyZLBWU5AaaKNBj+D+aUT/ZwJcgub7
            KMsjvR7SXEe08rQlTPkLR1BshnURER+a5vhEIDgMKvEzS9pF1/lDi1lU3arZzS8v
            7yGAyYlSu2hnIXglfcTXIh5ODODcglhjWYAfAuvrjXcP68quQjGoU7IQ4T5Fhey8
            m6CtaeD42Kma+1sQG6tagLOa0yWaJ6md90/j106fTQH3gNtZL3X9BAavG43xqSJ/
            VohgSJdSmr5IbrJIT+M90lwBpTUeMf5NPrtM4Hk6zNL7kN1fF1TvglCcs/jDAp9K
            GcLZWHb3q4UTrW+cIE+oR43DAaYfyX/I4h+rtNdWblqmCGehmAWXGWfA8qgpdkeE
            KEBblEvcXavdRR6FiQ==
            =nZ/H
            -----END PGP MESSAGE-----
        fp: 6B9CB4956CDDD0599A518BA6CFF195C6AE9E4939
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQf9ELqvJ2QwKKphBJvISs0gMu1Q7IcUtJe3VuQEi1zmOqxr
            zoiGrH5ZAuiIveuTiGyBy5jx3MFCka/LVhVg6G7d7Z3rrzaend8YIIchDGyV1lyR
            YTcVnabliH0VtC4Npdn6l0yZ/qqnYin1xYCHkelOpBZixLp63ENBbWZjD27E8KA0
            YVle7l9jlHQX4I6MQKFGn7+nrJqbg/3yOSRGbowxXbg+8lOddILnYuLrzjddzT9+
            QTrWzayup4PTvvYTjs+79XGPycTNQKKdqB7JztP1jfRLUkQoJOwJpAshCtyqw4hn
            gS6PWK6jhp4/OTwHEd6ONkMT/IxLdhd6i9ilSmf8SdJcAVuaDT5TPTZkrpYbGjdG
            fXQ1FyGQYGZwp/iQO7jN0dHOKJeRRhqx7Z9R2iu+k2Vmb5P3Ak/RpersjIjUB7jd
            ptfHiTyNpYJxKtSYHJOaTl5sz0isv75zFHKICSI=
            =OmbY
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T13:51:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0ZhTnV170YBAQwAppJyTyCfrzDFwrZneEEZbT2PVxt63/jMgrVbsCZKPpb7
            84o7E/JQ8uRBCxA0mtAUQWjLL57h1IU8RoIJH0Qgv0o0futoAOM1RIEjLePUXshy
            aoIV3D9DcfAtAtW4DZBioa7DPOiAlXALigaplxLF+2vu5r+VdmEtCakJ7XgsVo+e
            /OrMm3eOvCfpVcYOoa82Q/B9kbxo6JsGnnlz/WdmiGKTr3ItnV2RqHWR09PtRIeG
            x1edMRTIZANXk41APZNMT3Oc4tZEqWOXfRcxbZVOduuUIej0nLhLrGj2KUVJxlBk
            vqfaEDt8U22Si+OTjF0JU53z1ZtEQrxnQzABHDTVUWuK6IatvH2An/ugxYz5yBev
            jBo5s+OVYNSEJaAPDch214084g0gRjL1sXSqvaP3pQWWzai1ZzOSbfgcVLwrOj0F
            QaS99We6+pstnHke7PcvK1Q100gIY3pIIZJURD7zLPBChE2PxpkLB92MFh5uddFH
            d2PdoSbO72PiWqdF+3tt0lwBfL9q5p/sWkgAIFZa+z58H+vkXP8TEDL4In/aDIOl
            D1QLlhZJkiNTSiXyiEev9ssXlJEE8WGn1mHe66DiFEdb5fWssfXrQfiHTbIV/FUe
            AW4pkl5L5U7TfRAbnQ==
            =qD9M
            -----END PGP MESSAGE-----
        fp: CC69D686B0FCFF3B5C2147AD8AFEC23AB1EB36A3
    unencrypted_regex: ^(implementer)$
    version: 3.6.1
