tssc-config:
    global-defaults:
        container-registries:
            registry.redhat.io:
                password: ENC[AES256_GCM,data:2eO23LqCS2Mc8NgUrAcMqbkmcDj21GhHjYa2+EDZUdbpFildOBYQ1Fl2Pc8y0jEJJQCnt20FRLHPdtG2U3ziMn9SeAbw/7hxXZB+y8ZG9kRqGr0qLcoLh5edmgKd8YE15147DGCdslsmmNkVOrRH4IKw9ijrVgRdq4c3S/FR/Ow6rEpykvvQZ8t622G9yf4xiJwsrot/zOZz2ZuKYdI6wEVWmRmnfD7z9aY9i0TsqIuQJTrrryABswmIztwsDUmZUAhXbpGdKlGmE+ZrxeQlZzhInD4QWNr1kh0+fJ9HR+SczKohKx7r6a6I9agagt0E1Kix+dHbtDZCiY3DH304/JhtxOt4Gn3RxFeqT3W+t3pVlpon9fQIpSyb/FaQCl1r2hWGPtOz7np5BmX1Icjhzi46D1wYk/Ojuifs/xlqdlVDHArUgbJL/RiYV8vH2IRPDG2p4GFPF9JOKeddAOLx78rJGrj3yUT7todmvuJHgaFt+VfEGTcY9XypvPYvNtJSBrmfx3pX/msbLobpgTD8Visic5ENv7VLJPOCCaxnh5VM0oiCNxoHvLDrsiTH9+GZ7Nfa0kGrh0zq4NUQ5lUcP4u5m+LO1qT4RDghds0/PNUbcIA8ytEAQ84qHOFE6jqNvwEcqIdTbEv2HeKV0Fo2dUAGC4CMZY7do1roqCakpJiPdc7/klhS4zOB5GiYRvSZm7IES3sUdralOnTWl7czgkgx+b0C3245E3Mm/vj5uAqU33PBhJigVWrN+xKGDb0c7y7qziSZ4cniKqufkmzhxR9zwb7fMVHo7kP1PaxD4GPiGnFYq770EJho4RXBuO899si1ptrpcBCsYdGkx5CkiiQlVLs/fhi7xfZ53e5X6M9vnxJR9gEK8VtWtMjaJ33RL8kdEu0OYryksajAQomo7kvGlUS6ZChrbHbchQ7GHaxHGgZd+53TiXRYcAZnb6feTA9bmJFQhI7MgiehM/LXaK9zEevv4+qTjGqpWujZa+53cgeu2Fdh1Bs=,iv:93KcZ3bxvwzE7O6nFFSs9vT7o6XpgoayrLu6dE5X7TE=,tag:I/IjFl49viKL4kUs09rZSQ==,type:str]
            quay-quay-enterprise.apps.tssc.rht-set.com:
                password: ENC[AES256_GCM,data:e2DvVsjqsDJ6LNyzbYDB8nMkzyqboHGk+eC/TsRp6IrUOwt33ge6V4vbVd4BycnlENyrgAkaTQ6xWitkWe+LcA==,iv:mR8l22fGvXhshcw7/xDIYpTulWSpYPWSj6RO3hmIgqk=,tag:T6Iquvqm94I1t70hnJ+5RQ==,type:str]
        maven-servers:
            internal-mirror:
                password: ENC[AES256_GCM,data:CWvKGKGtioO161GonHDnxG9y,iv:+RAq6DyV0SoIuZnl4FLs7RffTBXkX1epmimJFrPjd1I=,tag:6EmrgZfAwJ+bGBScTFVRJQ==,type:str]
    tag-source:
    -   implementer: Git
        config:
            password: ENC[AES256_GCM,data:nPHElow7kHr1BHT3,iv:toZfJoC1YD0ITJLyNDMNfjNwmvGKen9uW4482EdHS+Y=,tag:B2yFy78pueiuC5eD2PT2Tw==,type:str]
    static-code-analysis:
    -   implementer: SonarQube
        config:
            password: ENC[AES256_GCM,data:I7n5VeJyQ8KdVMgJz7oQk3sx,iv:8gQcDymaM1vEShKnqj+T5piN3WhD0o+hH0vsa9S+o3M=,tag:fxo9NK7jsyLtkfj+k8KskA==,type:str]
    deploy:
    -   implementer: ArgoCD
        config:
            git-password: ENC[AES256_GCM,data:qpG6Ej6E+BIrLUYC,iv:SLrnc2qH2P6n4hhEIOh5XC3MyX7wxuUswHMvSJglVq8=,tag:uuqBsCP6eT74xAmhovcV3w==,type:str]
            argocd-password: ENC[AES256_GCM,data:mhwislov,iv:th7hP+6NseHk27537wS98XBe/kQta1m2jnnxHcHozHg=,tag:2UHNwe3TQFgkZrBoIAhrJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-30T21:54:36Z'
    mac: ENC[AES256_GCM,data:G+lcG52Ay+27sHlutnnykpzyug6igrLvNCQNFnkgHtjJVLS4C+wp8xw6oHH4ZM/SXrqJQma7uZkMhsOA3p528VusR3ogZrV/tRZmmyWsecAxg5sZryCGfXOPoSsR552YYQ8ZYkAu0usstbZs0PbWnS5a8Kt+8idolLxHN6L/KeA=,iv:ibnWTHYkeLWCfSKhlWYjLEbnfxxrgPDYuZHeAPbna7k=,tag:ANZEA7nkcpK4qADH/X0TZg==,type:str]
    pgp:
    -   created_at: '2020-09-28T12:23:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQgAqyHXjDQpiGrwIM0MCEsMIGXeEZ9tLzd9Npsjq2JNhsqc
            2TdIndch2PkxiG6nfff/Vn0VYX7QPJfsCCwzDgVJTE1XudkaHov3cKEnX26cTarN
            pR1f25Q/FxLnNjlfNlbVpMC37IhdcGwo85zG5HGnzpFaF8YldgFRxfYgvwzqsKUQ
            x6ARjzzwdX+zO/cmJhxkjGS17yVpBlSjERgZQluBvKjHHmYUdDabhT1XLjOMD5jn
            Nded7KwbGVXZyX1sDal5CYvZTrA6xFE6JuCdaE4ErLN0Md8EUbm3RN1z3zULG05n
            40EH42WONCGmvJzYeJsdrrNeU9GiX3+mGE0v/uSOodJcAekzB+J5/VaxH+V7VGbu
            2OYjQrMEUjpsgY8yFR4IPjgQjxDdFaDTUGTSuHEzG9FSEiPrTIwbHo9859mxQDMw
            lwsfFVfADPV0HBX+jsgQtGQxQRgdtgMJusqXCbE=
            =vr2Y
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T12:28:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/pHJVB+8SuwARAAivoQDUlzVPlzmjfA5tzdtsL3M9u1Tp8cY5wdQQNx3zqz
            BlrrRlS886HOGqfFbFP/mtBr6H0sHBcPN9X+NO6xSMm7JYJGrDJiHljWamgMOXSo
            icv7SGypmlmWZ8JD2AchuGq6D/cTKJ6Q26KPibsCmVSycuWze9Xc3UAsus+OLjOK
            m7hcb2hNQ0og6rfVqnzvh8/r4Q8NcoRXICCWyMREWldEYPhoq0TO6DZ3xDaUswIo
            7VLYq4iNKlEB3JGj5fNcGaHmG5fIu46pFUeMlFjpOFkB/ZF132dEo5U+dnokEMnS
            TUZ/NDE/QBAN8/uztTe0tojIT72/0aVTAuIIHS7YgoDaY4/6rxyfvJ2xLS6ks0t4
            KwMvKWKuqolklyU2Bf5P2pF7xt8+cunseVjacNB7uMYrrmK9c2dQGCMGbLs12kH1
            Iq+uOpwwnCXfrGqWjyZ0ggKwCQTE+gZs3unOrm2KWcpyJ7zUzWWAkxiX1M78pEoS
            xEmNmSh87kr43ZfsjK7RCtNyyc4ces9g7IYbGcg3o37qOXWHvAx0Ve8x/Wqke9gJ
            K8Q13FKIybVq5Aa0tjAjLjSJ07/GqWfA3N5a5Tg8Yt+0bOqRJifxt4uG4mm/AiF5
            5nJFyJxduO5LF0ehJVoUqODJNOQjJT4LLOa7a+P9jKB23d4FbiY0JDMh+3xnQpPS
            XAEsKn28lkJL9BzNiLWEz4seQzpR6mBTg9So8shoMzigjMOyKCfcjisJmKezKEpe
            xkCldlupAqWUy8/2WVFj+YLqKlKsdXnVv7FUFQd4wGguAbakNnW+3wWPfV3D
            =84rG
            -----END PGP MESSAGE-----
        fp: 355C11B55E83B15E5CF6366283637FAF9D7905E1
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/JEnAHZDjB7AQf/frBrVndr/4OINZ4Xb3lX7icFKlbuQNGT9RpW+ai1E/B6
            qmQX2Dr6zUx/Lws+nq9gBvQEJKC+Zj4yYoFrj9hXR7r0bZk6wAjSe0PpMfaDqbIE
            Qjki4YCgmUubkoyX7PSqSBv64oo+5sitnUY/3iBkUCUe4kQw4yDATywwq7X7Bhcz
            ZxnUhwK8NovNL+YvMWrZu4unpiatdxrGeXiblEbkr4oR/0btiLOJG/wa9CZl2JV4
            pck6L4AAVuLxduXkJcUqFKI9Zmfe3bjkAcCeup/DZ0wO1Jk7noNwrJ1izcUE+xUm
            5mcoDnwbTsBjFCpv+v2xXCt/3nshLsGhdws6VX4+6tJcAVvkkWPOBQsbtaknQZOx
            fT1WxiiLQHcYlnMEFemzI8xmtGwuzpJEg5c77z+gFANYzkOJiYki/bNJqYM+4lsb
            fyUIdIyoFJKXroRCCK88v4qkoJWv+PHS583Q/DQ=
            =9cNQ
            -----END PGP MESSAGE-----
        fp: 2A25DA15018235A6206921952730D7A70EC35190
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6220UozeaaQARAAkCy387WS2oN3uROejnjpprRNMqm9+BKXA94qQKERrvhB
            3nNtED0fRGa600wwTswNvqXK6SWYDbJNEzdYUe4Yh3U+feFFmjGCXm9MU3wjmRql
            hl4IQE+2LH0XePGR0AzTmYEssY+ghnM3/z5WC8vYz2gsMIbtelYVx8v5xHY4/KDl
            D3r0/1MuhCEJIkw8IrC0x11I6ABsWbkxDzj66FNdP60NuK7Uqz9Bh5Dfz+ASyhs1
            Q/6oadDIWFW65V8wRV1pOPX3YEQwXh+vOHiNgCtoWglVyhwHhLQxdL/sTG6Bl6y+
            nMLy1KcPGVSkejH6G1nkEb7i2R21JUYZxAYRu7W9sXSNSJY+kyLC3kvNB3COHoGV
            oAj0o3XAWqvHq8nWhfu9ltkoKh2XV76LXrEaKRXFyAHwo6aK3QLFM2YuXulvqQfy
            QHY3BnZU2u0QezpXEU9DJedVYzwSKIX2cKxMs374xRZg17mt4Wz8rg5vdEdKheN9
            YCsVJsuio38iitzpoY7dIhlFQ7pgGMSolY84DO0PFECyW7MwdaWrs4EiuVyIcyuM
            6zh6peAd5ObWGsBzeo43geBqlkOI8AwJXyq1t8Y/diFiohnR63oGBRntI1FEGMxj
            vqGVMVxnoC1Z/Rn6s0retmlAn0OmlZ6jurHYpAz1JEpAQJKluMJOQgGxVBA1nuPS
            XAFF4ltDpTZ+TLp674c5a6J2p3RC3RQAKlohT+ILkz6NW3egsYTGkAGpUIk8O6Jj
            XZEFx6rIXHARNngew2wqF11f4VMZMZozSD0PvqGi4PAm9KwyehZrymGM/Duh
            =BxOK
            -----END PGP MESSAGE-----
        fp: DA7B00C8ACAFED2DA7E33D1ADFA8C968E1F69B13
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx6ne7Mq17RmAQ/9Fv1gKrCSRpfH8dsg5uAhuXnkmdy7ROhffudXbed1Licp
            aLfRPAtfbnHjgpPvbd1Rffm1cPMNQIHs8CnIhlmUQOKH3UTIpI0BtfRUYJy3eNpD
            TLd6iyXeVAP6LxYTK05ArI7hG1On+CKKQ4/Rt0PCiAofp9NK9iAum0EaVfb1rSfR
            BjvYGwO+BgxTJoVJgpnbPoKzheIOwQskZX5HMLPZGYhzvI2X199RrQ6R/YNO6aEn
            hOoGv9oqFxVRe8ydoObq0F9idEhaTMAirTu/DGDNtO9f+pximCcFwpfJAYzXm/Y0
            D/LSrzcqE14dPG7Q0b2f1nRLFHV6L/wJj18zszUhtgA82XIdz8Bp/vQvt3RK0gFa
            W7O3rVw1MHbuGvG8hl5Ez5WyEaVpvlWk5gWy/iIaXrs73sxLVUTnBt8nX+Mm8aKb
            b5Uxs40LWT/JZKiT5gNuCsvQHQ/7CSqNCWJ3D09Ep9DuFMSL1921rt8jMSkc6wre
            r/fx101VRJEGMTTnFd3RXc/b3UyZjOh3gOy7z/TCXmoOL6ct09tlfJHv0WpMhrR2
            2b6H0f9F6FhPxU0MS17tu6GmofVr+rv6Ph5tjRKiJDC22kdMZ5LTRzwL9UVl3jqM
            vYNSpyCQT6PP3njnPEOP4GGZ+rOHJPzHKn54ulh35akpVyZhaS7WThJtgppfhw/S
            XAGuw0vzhEzwmr5crz2KchSjZXZHGUS9PIwMZ6weCiEQehylzS8xLB5ZBT2fR8J2
            cNkWnnxQBbV8NR7nF2Q5Jic5AlWDudJ75n/xnAcPlVI7C/QYH85i0LOfc9fi
            =HGhH
            -----END PGP MESSAGE-----
        fp: 911B366FD384B2CF3BCAE8EE01F9B7BD00DCD57B
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75NWiDtWcDHAQ//TofycJf+82E3gHmGOmg2nL8imOcqkn1ahc98YDnq536y
            iYV8BF/Jit8N+RTXM1wHZ1CwCTlIrPXjKrKhI3d8J5ig6UL22vA5rB4CAQUW+z7j
            Y4FLRkacWZmdcS3SelpClB09SFK3K+TIYXokDul0TmfWpo7xv7U9cDLgcnTgeuYB
            gpaYNo7aZ8JUvh1/N9cpCV5xjbNV1GjmI6FNj1n/27Zg5eBKbZ+/63vRcAHQELT4
            SBkdMUd8lxngPs+SvoOpKA3P1B/B+eKb6V4a4J+f3aiVSNQ4rhQojRJ7jQyBCpoa
            plpUN/bY0y6svETUpAzHkYS3/Yd050/fTswfKeuKx3tsK58Y7cuawzEuhPJB5u61
            dMrkkeYJrdfyxWvXOT/xinXGOTA/EZwQJeOsjSpCm2TH7iTB+MdVVLHQQCDLKWPJ
            7xX0LQRnwHOb++Mg1Feov/eRd5c9vhK1pgRtLuqXJfetY/XvzHbuAOyqBQrkJup7
            +nfwUDgaeoucsgrdR32gstEnz68zhzXlxoLoICB+q07Y4jERuQ4x6cJyjPftSbI0
            JBPminF+YFeLfa1fRsBIGdds7Z7LgGAp3Wf75iag9KtXWuIDXYvE6y8Uuw2nvHGk
            RUIBjn9rsMM1ax3nc6b05kfzZWnU2FDCs67s2iQ1JXHSRSy60v6N9L8JXA/BJVTS
            XAGhvzVcXFmTBe29VnlN0Qsk23zhRk7nWMoNv0ymFHCOQgcvSk2BzuWPzydCGPVF
            7ElauIVRydvjCFGa4Cnk/CE6uizCJy9vH9XvJVld988vrYuAUHQtZvM0sdBE
            =JzkK
            -----END PGP MESSAGE-----
        fp: 4A4B9A8F518CD36766AF86DE065BDAD92D70F679
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/haI43zIlNcAQv/WyL5jZ3TNHi2nzJw/GC9bmw10z+Fnrl22uyOWpadTNLL
            rxTH8gpyoTKT6Bte/ngA/17BoCUNq+GOLxLgJr9Bxj28GqTY4qH/BTD0enZaZh/Y
            LCbQkQbbAxBZdTz5KFz4PjwqtupCq7X4WSVhMRKNQYojnUCr99TTcKUC2pPYx7gV
            UBXJbmfV2jExKvARogDIgB9C8u6wXlGKr7QgT7rHQXtj+7KjmbFEQeTDkuGIODae
            bOBNahHlqcX8aC/7ZUErk5Z/B+D9kwT0Jr3VPA7xn8o1c/wYo5lQ92A5CEl+50lN
            rxvCHQBNQezSm/vz6Y6DnlKM/DLpCfFtJpBH+6QCnaSytlzprZpOviIMJTpUvOxW
            cqaIXUrh2q/IzFaaW2DiksXdA8jS/2pqGtmoQxgxIq7Peu7hzdgQurKYvjYo5ray
            V238RFp8odr2w0F0mSdAQcGKml5+Nf7bYW/5jXX2MsyCZULHX9ThLxR+MrQOcVpM
            J1SZO3b98wfQWSIGjxgs0lwBZva+wd6qb8MrBxHiAXKzdz9xQUQ9YM6/yqRSd5VZ
            4sJo0Shei/3IIOr9DDKaDAeXCqxZuCAoTw92THYNnYdxqTj29f7P0hzTJoA1tYXO
            rStf3eTDEfBS5BWk3w==
            =LXP2
            -----END PGP MESSAGE-----
        fp: 6B9CB4956CDDD0599A518BA6CFF195C6AE9E4939
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQgAlcm5cfiZAsRxxuGDdNBYc3H21MjGYHnv7EHbwlZC4ciO
            ctFqWwaAr0jldcTEcEc9Z1i5Ke/XKmMd1FwFJYRfPeXXrhuefSoVsB986dKca1Sl
            D/ie3gFgVL/JKSssN+k3q80+pYmlpWPf6WE758+IYN+jDCw2olxNSQbD184mEVGB
            bFY2wf2wiaSnH+ep3TqPpbc3n0rb/L5Uq/K09WSEMNlgNZAgX9JVg7um9aNZqNma
            m5BFLpbO3hCrJ4DjO1np4TFyYgCKcxu26d+qj/ErxOsz1E9Dc1lajPJNtgXV3CYv
            0aTORTRRGxPQbiq7YDQe+FoNiIZykF1SnalPfeHhZdJcAfyRXGaQrTssdcKrWlBe
            xcjRbYHHO7RjeHDuwm1p1Yohqy/pMLcYcRIAGf0EZH/oSJc0AYBjd0c7bTgkiQgx
            sgj8eGvQlWCxbf1rjoR59rIqTxIv+Kz+syL/8f4=
            =Ef5i
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T13:51:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0ZhTnV170YBAQv8DDUwTjkv8u5iByU+zRAoL1Frb6Ef6to4gpB2AMtfS+h3
            fNjHak2r+8/W2IWeNT/K0e5FKAx0Kq7nnIfc5rcjnYfnD6Eemf9Cg5pQ4xzx4Xhy
            bcV76B5y1rgRjfRa3RMY+CkF+8L9LWvOREg9+87AHCAP24tuJ9W70JBN2LoiUymR
            pISMnleDaGlo+u4XcFf9y1DAd6hI+xdqHvT0GNlnQw6iUMBGAmO588WKTmMcnHdw
            HybJqWJre8hfam5QmZNbG94VvarL9FuuxKoOvIHEaaclkG1UNQyv8f7cmzoCLSKI
            tE9QbYnqw0j7qz1fCBIFkZOggkWt6n5SwGzgLtdN0WIWlOXaPrBHu83+0ijxFcfN
            Y97RZGwxCGdST7pWoTcY9a4FT504ciFrBWTyvACJhwSlBlcqVFZAjDwK8Q4JA7H3
            2mORwWdh3SRUFGNWtFbxpEOatxGO90JD2BCP0Zss121pWRYQiRme1cqWXGNyLUuZ
            qHXQxJWs28O6NeHe4BMQ0lwBsYfWveOCzf783sEZAWduIvzDHqNfDZZ8hrBRP/9Q
            TksVY6kVVeN4awyZpWgcVhbEz3PxU/TG/NAKBlIvXWxFwkWXd9zCwtj+A9GHS/x3
            MYvFsWh1/rKDnos5fQ==
            =Bb/W
            -----END PGP MESSAGE-----
        fp: CC69D686B0FCFF3B5C2147AD8AFEC23AB1EB36A3
    -   created_at: '2020-09-30T21:54:33Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA0sgQJTuz3CvAQf+J6hNxpEn8+hGZT4XaRQ4oAk5tyvXLFZ1KqEldtqwo7Ht
            ToFNWogP+G5rqV6lAzqsBmyYPch03mObtgVVFGj48mBUrELvHAQbH06/kcosfpM2
            Jl+gvYQ53JK6b0WvqdQSTOvdnE/m7DAf6ChtKhWYgrOa2znIO9/frgU+OXuzgOgP
            EaMZO+7H/Ql8UsESX5fqAeTdyQ7oAS/rZgrGs1VioERy1zaEDHRG4p6n15u25aON
            pGgC3VMIaYVO48Vx3iTiBko5zZGcnO4ZcJk+8GmtRUtFiWGMpZf9t7kDQuv8utt6
            iFI1yieyLDTAGRhmjEXlvC16t/3nu50aSk/xjPqOM9JcAZqOnJnl3IDO+mky7eEH
            DpgPOPk2IFKqZHZJ+vy+2PJliSQ+zE2fJEzFRbNsByDuecJJYqwB+6zO9k2c1Mel
            tjtBp10b6wdJlS4ydZWA37uCop11e8Ilc4OrJCA=
            =LTVM
            -----END PGP MESSAGE-----
        fp: 84D2732F14E43B7540DF0074679ADA89F304FFB1
    unencrypted_regex: ^(implementer)$
    version: 3.6.1
