tssc-config:
    global-defaults:
        container-registries:
            registry.redhat.io:
                password: ENC[AES256_GCM,data:t/Y9uc4ElggNOsqfpngbBpaYmzwXSPEUvb1K/la/PWhlkp6Hndsyo+iHAdL91z7dQU5twDtmrIDMBVKvUBYz1DVlqWQnW2KneG5KkAjU+DMwFEJ/Wjd3jFOP+gVHMcl+fUokQjVxy0/O7hz2joTmUkF9Y9VrelSmGE2B0xoQZSOEExIENUSvoOmR8z23QqV0/Z2uoX3YOJ7w8lrh2Z/lBMoJXw6K2pkMoFJ9xlLWcCyluMBg4PM6w6M18pwk1Ltih8BRVOmGqyQ7Rdm2wPRcAnAxPpru/qVoXXLHykwoG5J6qXxP+WVjb87p+mfoY68VcgEX1DFz7WW+yw7/Suqcgic6eBW2IPutjZMafb0rCuHE9IyswwelyHA90sftSuZFVySBL0YL6FqnCo2+eDhFO4Kw7agDudALk6r2ccVbbFP9LAws92iO5rLJuY2PyPDghELsN6kMP9j7XVnBr7e6do8x0HOZebaVWy7ygCWeQ79yT6Aw/l3Ac6RXfzD2Wi0aJy877Z0+VwYdhs+64gETq0WVy+PDfMYDVFh5hQaTHd6c+5CD0Zr4WGbWp64CZ3AjZanJakQ/E1M3zJXaVfG1luCgqJPuVfJwlPy2k/A+Mq+DHQgae3hWXAClSaPVAjzfx+YHcB12xqhcBSElvsd/2Jsy6XlQIR/IzJCPZWf9DW+TJ8e27t1Xv7Usvo00YuQIIdHLQ6cXGHRHUckptr6eh/7DV2XtD4409VPB+KIvxc8Pr/gNwrfy1Fz1i/8hfqh5PjmgoeQmdd3r9dFbwWIDwJwuYZ4pkyvB6epj4c7flu0Sd/EZbTV0sZWoKp2oHn+CsJDSumrBpfP/OK0VejVMj4naqv63fUst3rW5j4tQZDpwc954zhSkV92U0pv2nYwi6OMBxJlYe/vpkQWR8Xj6/Eqo7rzM55IAuRxQW16A7/Qdv+Dd1Dv0cSm7y6bDAIdrPpXTbKBqLKvdaiOAtL+pRcL+p0VcsC7aTTQGGt+jA059Q1lsTNL14Jk=,iv:93KcZ3bxvwzE7O6nFFSs9vT7o6XpgoayrLu6dE5X7TE=,tag:7P8COKWpC6s8D6/VRaH5gw==,type:str]
            quay-quay-enterprise.apps.tssc.rht-set.com:
                password: ENC[AES256_GCM,data:dMK//3uGbG4FGOXH6RvJE1JOE0icSh2vGiVd//18Tz6Si0iqQhEeuidRWNLvkvw2I9KlFX5R2+m9+b7BvOhL8A==,iv:mR8l22fGvXhshcw7/xDIYpTulWSpYPWSj6RO3hmIgqk=,tag:1RduaxfYe91Kmv90kCUkPA==,type:str]
        maven-servers:
            internal-mirror:
                password: ENC[AES256_GCM,data:NYdwD3xTTMosFgcAdas0rMDT,iv:+RAq6DyV0SoIuZnl4FLs7RffTBXkX1epmimJFrPjd1I=,tag:58KEck9GLmB9pW5KryWXOg==,type:str]
    tag-source:
    -   implementer: Git
        config:
            password: ENC[AES256_GCM,data:wbIoAyxaTqSecoDm,iv:toZfJoC1YD0ITJLyNDMNfjNwmvGKen9uW4482EdHS+Y=,tag:32Dc5KfmltA9USSb85BS4w==,type:str]
    static-code-analysis:
    -   implementer: SonarQube
        config:
            password: ENC[AES256_GCM,data:SzmqYFtFd8TpW3Vhrq6emKtW,iv:8gQcDymaM1vEShKnqj+T5piN3WhD0o+hH0vsa9S+o3M=,tag:1Ejxo+z2T52l5XhZQ+ESiQ==,type:str]
    sign-container-image:
    -   implementer: PodmanSign
        config:
            container-image-signer-pgp-private-key: ENC[AES256_GCM,data:+c5MxErBarNm1YaYk4Bc8CP3Q3cRKuZqN2psyXF708E9YXwQzDZz5BRwYsTPp1GNniC2LGhIRyoGEx0VjoMZ9ShuYOCeJHfzAPdi4iqeHABcYdoPuxRaBdjXE/jgdcYactcPFJ2O+1l6UVHX0Rxhwo7pb2FMYIlCmEKh9i2xRA5tIICn7Y0+y8z/7COWv/R49/xEH7X7ngt1j2Y37tcdiay7VBAoGbTxS7vf0UYeTnS5xvHd8K2AAjCT+Xoz7SpnIjhUs71bLvRyZ0ffF5jDkzUSEiy2PmjWZQ2414V6HnDrOLwzj5OvJUiLYXj4x0A7tVoZT/Zo+qqiPpwSPRjPqpARlmZJKjzl/HPUDQUA5WMjeI106xVpDDEtRP72ZuuRKYbjSZctpiCxLRQg028+YAWrCbmp36wRH3Hsn77vBp+5ZumJ30xbns6ITRIq2lGg0/rHq4Dfyo32ZBRJu0Fy5LvwHk3wrvv4kVQr9UcozqZj95vrEAt60xKr5cXtqc5yazsUfc2ToJtOMT5ley5ByD2J5yvW1g6xKyFpScpCWHPG1UqQtTHbbpK1E/BUh0OnWslkYxDyI04IK5icIZso3jCr4j3RJNyzbSwyOdcU5FzSJCTk6Y+dC17KqtkDb91dQecmKpHe2HAZ8Jx+EVsr9vqMw0Det7FyfwFYI+Bo30QBOv7A2EWNoYZf8A3eKd88e78UHIUBYazPcl9ksJUVKv9daFnUy08r/KQdK5UWIY3QBpz6VawSMYMT9D6TlZ/67GxLOyYhB8XaF4Z18Cg0QDCYG1HWY2PKlsgo9X+Wj7X3SwfTT01QCknLCwlAQXfBeapTmGTMThieAlmrgWTSjT/MaMvA+gcsFKCYUcUcGUs4yOPuHhTSpdfaaZsvyzObZC/xW9hQx5urohTxxMWFt794LTw4jArqo/Ih4jz2z3mak4fO+D0+hL44ioMYo+xviKRwsb1Uotta4BCn4IbGM16rOv604keYwo0KBJEEY4cEzo01RSvNQNCMSnZtwvXnEOr3PtpGIfrv8ttjgNBa8CXz0jomR18Y86M3ByMOQqe5gYikIavcvIOWOpUQzk0xiAETqoy1mpMUn/dskiqA+l59GUQXQjhFCQUkHesZaRSalz+c2irUyaI3EFth20x6B0aM2vtRhlkOz1+g/qIZ9fwpe2UAhOeCowzpwiMLSIueZ4mQF8Kd5LgpUqT0cIktdNvJL23zj7PA+lqDnunu0XpHcpgyfEg/Ej03iXzUVOy27yIuDxaIALE3wTjPcAFK3rNTkIaVqbwAlb5skuEczM6VGzAc2i4uXy+IxdKJOJPhAqRaZjDAq4awNNYhFEzNskzdrGruRdlvaiEVYXePwc4I1ZKqGB+LErQLKQzCVZtVLVzFxysEG/20DgQ69021q+IRKKGzQPo+pKnLQvymQP9klAKKfwukdB4vWJv019vQUdjU/q+jQvW5j8N9ktArBI9unw8YEysio1b7PYxEx91nyDIGic8Opmo0JAmC05fYonA+J+Dq2nQpPk14wg5l3tma/5ILPH1fViXOpxQKy26i77yMLZEHoVsjGRdAzMgf5tb4EkfDM4d6HTlE/X+x8zg7h5DDAE+u1k0eO1bsx40A2GYF+gUF1KdH6lVnlFvMxZQ4R4iEHIBpqdHMjpJt0RwWf3Umepzv3GJOBZ0nc/zC85pXGCMm/CO6FT+JckPjhx1+fymUR9plk49i6mmeViWp6hWhH+5pxeonjqF+6zeJsioxjQL4uP2dieArVJNWeUK1wLbSobsyWdxPfTgvPp0A3YxT+sYYf+Q79lLX6VyMow/H1M/YFYYWQ4h6YXdsy4kqRtYTHedb3pBYTgW8gqj2neVKxU7V6+l5l7VhiWaqT/FYg258qtfwpiujonXlgnKz63DbCpHwrkZRg/gf0OqDOSpgqG2UFQYkkGNJcimQEl6r3fXVYOnmVyVmVzafp4bb8zuHDr6hAjXDGbTzWz/64EsP+mnpx+Cj5l5CHJvBIw6Bi6oIvtqtohHKLODr2ZjwQvghtve1T4TVL2Ozb9iXPU2M33nHZovhvBNgWbGeWRBnHjDiYhAm41TBEL7YBy46z1v8EcpHjze301gDqRUSET8elOmuhYIT9N6b3pKVnb4kJ7PCdixnOE+aMvfIHHHOSi9LGgBjw5JpS2LrhfgvmGGPldMeqi2xAM4koBK9PhQlanHATYFe9CIfJw79zu3WXuFbqXIIXTUTsDfRz48HpsoXwCC579+VXTgyOOmkw+cAI/gOjHRkhNTfad+CIr1jMOmpgAIuFPJNdwyhk6oFalgzUS8TIQyGSGTxsTiFRxA2HDvWFOJep8R72QuZEICG+Nh583bQQ3QaUgc+8AG0mjjUEtCZuSI6Xu8X5g9O7G9m7Wrz+lKYer/74Llc/DUOIvzptpH2yOgnQuabty04LIJlzfrlx3vgtF0TgQt9yjGokVab1aqNPt3IctjnzvH8kgCqa3s6HihxDLM2AaUCUDB31oAEzyCrkDjqQu8z1nksNEYoMgjFWPBtbwM7XH7xCtElSzXSOJREN+tC0AMYjaJYdJTgEmyk8f8PgEPV7rBMc57lxWsjKIJ99TSv5EmcADSLjGn34zb/rXnEqtpBru5I7NjyIQNbuACa7cARd+4SO1rBwQbcDN3JFAFyN5zf03KFj+MEv7qUjXRiysqFKcRHum4AbuCM0PttxCK3M9WG6nnx59y45TFckVr0ErDCFbRw8Xow/PHaY0k8Z6Gb4bOrWdHX3p+EEAtIM/0bjE4iD7FyfsZSVmOX9i+higyEfQQrbI/PcZKsAvObsaln6j6d6GtO+ozNy8T5S/+5GsgIw4CnLFSOnzlo1SzR/Upcng0AOqS9soI+s5o3QshSjjuzeLK5eQ5Iwg8nfnSYhEbX6+MCcdzY/x67JZzlZoGqDsfqPGAvow2VFhhnvZrXdJ2dSTl5A6PwGzvMihTwL3WDtN048a5VFVW+K8JDpl7jhiuzsQ9Gk/fyIf0dTMDgdVYiyny0VP4/SZg8ne1Tzg2du2dmrVp9T4QpMC2mSFHByqvSpbvYO9H1V1g2RC6PqvrkRbW8LtEXLBRZNvryBDjGIciUkVpN586rmJ+yhQErFtBL5NDt3iIHS/ddGZOUypHdUDJU5k6ON46VPhx61h/OhlnszzWozUiq9XN/jdATZih3WP9N+/AclH2Xt/pKyzEBebVKNtqIvy66aNrN/p3LfLGYhhipXQA7F2dqZs1YPGGkdkcrpKzjKVeTBOTm3HiuIWy5hHYF63DK3I3Kg8BS/pzgD2u/m0tcz5/uJOCpeJulsey3mVKzlR7QlO4hkWoGWNi7Q3840nL2EKynRAekxtf5rxaBncpmfoFGoBYi4TaaiCp1FI0ys6s8PFM3NaTIs4UEUwbSWs07cpqhkUI4GNN0OaaWEUqEKSzR9BVYvQk4ysr1eqP8YEx+gRwZxhSlagQ2rRKQvyLpHvLgSISQorayPlm5X++5JdWnyRXd6++XbLzSkgqMncKHnXxieoGLT3mvo9SUAjaXkmlqN4or0e6FZDJ0arFvqiWcKoIyZFqpn9REFO8Z1zdnXcBB8URwx12FM6aqlTGGRgf+Hr0EhUhPkTFyksmIZ81nnRN7X+7tvp6ugB80H1Mqz+7QcnXAL2EXA/OvSVTVFa24p+JCX4RueDVKjhP4/ASJGBf4ElQBIz34n4ksC/yTd+gdI9ejht2jKlWtI5GPjoCVw83pZHwHaiGh++DCpwzlhDnWNeWvjxyWJt6j/NnFX6EDH8XfpsrH9uioK0Kf7TyclReniNq3wiipWsUtNHNc2yMNAP8tpMoHbdsJueGSN4C+QpU9bt7l5BMUc6ELIlArmnELkPMrdK8LTzITclUkbgiVFlBrF9jjzqEN9El36TdBPWj+9TursE1T3iDvvtIJ/SuVl3Q0A5fj6fKrH35IDMxdec9mQjXZcxmYz4Mev5Xxqh9XOaW8bUTKSSNkr0DQg9qEEgUNef5wx8r7BIUro9TZHXMP+ppaMR4EjwbaZ6e8sDtHuDojqv1DDyy7b8rHrINfSUCnc8PKrh5yT8aztxw/k8+SYf0UgAgujkAK6G6apRvr+PQTuCPp0g1UU2848ryehZuEUBz7r+6rgQk7CGIE+6r6KtREUiAsThau2Dg4slCAdQ26tQYvyUYKzbxIuf+ki2+vh3hQ6RIURiOBOS3QgHBuihb0vvv68ijB792vLLK3qj1/MZWg8RzoRt1tI1CIYJqdN/6tlg//jNYq+ssP/ZFqXtLBpqd0ig2CLCKanGPp6Pmt5gyaBW0GWBitWD6dFSiglwP++AVngtx3GkXpwFWXc3n9zF12lBpYpsoh8AYtD97uMdOSEJHkFlMInxWMLA1x81r7fJSPfqNu67avygiJvZFvSUAgoDr5MHlSdE81GPe0V5LJ3MDNXRF+tWTjxMQl3uULp7FgF/6lINNY12VrblaP5PEPVvcdrjm1uEykl7tDtH0m45rooU76n8vrBRnbmJGWA2XIFUUK9IPAZXX/nBSu7Jq+quWwVQOAU4wCZY/ShyUA2BRuz+qvMyAKeixGi6m7NPWgY9+rtG+CuTlDUrO4+N1Qu5H9oDdch/Sn4yDHcqKvXdV0eM/iUyMzdd4TFc6bO3i19igWL7O5qT5SPpDo5ziYL7AGLfvzPYO51/sriDO10nbO448/CLD0c8t8Cyb8RVj4wBYQU94DcyacqNooNELZCsei/czr/AAoRHleJq73OeTmPWlzkhpsfjE7taaeY9HtW0RrvGfi4ta/zriYgOeEqFIXfZLrejmFe1EoP+nrCSJfMapUx4WnXq7axQVOnQ/3y7aHVlOpm8Hzn/YLRp/MELSlYP5eRXcuR1ntlHZP0aDZclEeOEi1JLh8Q3PJpOQxI/+GUZjg5YgBa4fZI9lmsUt1VWG4mWwleLJ3t3iEtGLkua8RrVV4z15MN3Znu3fre9pXRvuOLABD3hb2B02SjFUD8jXk6TB89I2dqRBvlVcM7saTNBVrrD7XxhSEaWiEzkvTjt7/i57oWn/clGSeW+6V7xpBNqxRVNNxiGzbpnnhTNhDAl7mC2Ts/TJrOudnKHxKeq+h00MhHdcpg2H1To8LO9yFpIFWZmwinllYAZW+fZG3GB5m+YfLEyjtHEDaLQL/R1qJz7PKQxlV3P3tyfM3p5emgBqKwbRowu5atYQ+XQn2T2eFv/UECRtnRda4JEYrK7Vl71eT0gqiuWnURD3cAgNwSH+ktoFt3TiPcwbTRcwhahbqVIfQ2o8smuEQwFdryuSLK4G4pUKnxyeh/WJxey3tmnUSQgP+xDfGoaSiUygpBVyGGUThdgRdjv+Ufjo4CD53h1xjkGhs81MvKxNRdugs8blh8LeG1HA7ylO8MBjXDijowrVjFAPUt/lvJ6iIy9ihJWvOorbvBiQ+MvDJaqlUw/0WDEJDPonE7EoX/w4jGbzGch+3WG5tBNFb3C8QsfJZEgqBeCuZutgoVO6VCO1BogptJyEY1nfI8WaPrT+fO1f/FajH300t5AcpC83xeXNyREmXXvmJooxXhqKUsR0cOhAshSh1NK0j8oxT0Bn+KNJpV2JSyBL4rIe4KTndlZnhSU3CSNadeVBFwdjCdq2JLnK7gzKgzV4Qmqmc5xymwdPetBW+4N0mqi6XkQTftJLtfyROLJsl1dPg6cWlf7SWO8fpdSC25Q5DGU0AuXAGz41n6Y3A152LyMaLAF+xHQFCNyuED6ZCRA87JwR6bqIek6uiTrAjJ60XwITWFItSxdyRlb9GDcazEJ6TM4X/moNIeu9DpsMkV1tZvocEe9p4kznGcjy+rvYEhLteHKfPZhO/EJ5MeSTtw8NCa6PaHR8avUPmHiFi2aCXa6NuIswBzvPQ0VJJAPF5nsrtQsAEi47ovkff8NL0128d1eB+bjvy0ctJYKhl0zJTY9W1F2T0qPmc/dumMe36fmOzuPPuhA+Tc0TSymu75SB6Y+dOHsjoxOjR8YCJJpQIYBuvghwyqfRiOXjhg8BB2sjnrHyWKDF6ydP391yALY0nmwFo3bQKZsZEC7xsL+ZaBwpHfQbSc9+Y8s/cttbsq98A+gsHBvr2jkE9+pJFjiow13VpQuOHbdgi4S3Uli66d8Ht0qtVKgnURf37pga9WAAj48LNU0zd7k1OHCWK8N438RxSOHsUGSG29gQGCBdS1N2cN5CfpdIXf/mY1ofzVal6/RXUgbjlb/tTrgB/kgSQC0qcFpiVD3nbAs7jyHW2HWU0+0LGPo9r58HsLV3Dc76F3axbtkeOzdSexA89pPJBFYBWAXHjbzCeh1QVo3yFPLencCtYBMfLPqr0eRxmUK85Byw/R+/2gLVsl3To7Fl2xLkZ79xZYYiotc6ppJzVXRZ6rYteYQmErX6UNfjCcRrzARoK1VV9aKNWwe0/rYtjp1zCWj0SquMvSmorgF+8vIiLiouAbN/QYG5/iEUGjtWzW5N45x8q1BtsqOXD2/TTQw/3oTPN19qBA7CdPmGwZq7GEivuleWnyF5NnphbQzbpYnFWtuDSkZpLe97UyXZ1oLhaIX3rUzK6GW+jvly743b/e11tjg1AG1SPeKVEeeKgR8iocvhfcrnhfjcTmM6udYGQJLRVgKb3zG3ldHvyBof2p/TjjmAKwOPlpLVxQ+aSAdR6YziDc7O8e94f8Q6gY6P3Jj1u6zHMyv//wsiEAT4VBozGzgWFZorCZi4fBXy+muXA2b6fLi9NTq76bClSL8kISFGb0BF+DA1B72GUG6mmSuNHqwPgnfGXXHlVOPxdUqL6TYTA1FhFD9tT+BysSsQhd4E0Kn8tQpK3XTYYSlXb21Y=,iv:YW8CiGZdK3CmUwCMDAecyBsO4KUVOrKaNnnsVJKhP2Q=,tag:ylLSlkfmVdInti46U9nTbg==,type:str]
    deploy:
    -   implementer: ArgoCD
        config:
            git-password: ENC[AES256_GCM,data:qC7MnBIWQcmYqf+B,iv:SLrnc2qH2P6n4hhEIOh5XC3MyX7wxuUswHMvSJglVq8=,tag:wjBwALAQhvgLioELPXU5KQ==,type:str]
            argocd-password: ENC[AES256_GCM,data:4V1dcfYd,iv:th7hP+6NseHk27537wS98XBe/kQta1m2jnnxHcHozHg=,tag:9Ag+brIxdkiXeFdeK2EMzg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-30T17:30:39Z'
    mac: ENC[AES256_GCM,data:zBsAZUOY6mizdee45IkalpmRZGhvjtW2YjM7VnkXEBFYhUsdRmz0iH8E+mX3Utmw4RGbphuKzli0E9tvznBvB8LZpYLrztKI4jOU+JkVau9C8L5Z5tPGGHJUo36f/VzDoSwUTHdco+9R/7jK63B32sx1/yyjO6rXw2yJbnsyQog=,iv:aBR6rME0vtW8/eS7ITqKR7YSzMkwjkB8bAP5BN9TtH0=,tag:ZoQma794aqjZbVyybfezPw==,type:str]
    pgp:
    -   created_at: '2020-09-28T12:23:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQgAvwSrqVOFtdczzC94Th05/FZ2K3mRCYcNwvzEi/a6jsCb
            RbADeah2USzSD6Yqb6vlc4Ehlgz7HdKf5tn6R3gufg+0HJ16V5Ic48EpXNA4RPZR
            vebZG1xdPHQo/cMOSmpfg8Z/IaguSlS+I36W1WO4D8F9LoPkmHKSbT897piYbaim
            iWUHouG5PFwZuObvHtM/35GwMfS4Ui0FdZE+wCWvbVJcM59cokS/KX0Hn9JceJn3
            AlCBtlFiMX5BtyLIjRIECo88/AoOLJsV1jXBfEI8hM2AzShCD37t1Odw35n0fOUy
            XxW70B/C1Mzzi8XY+rPqYG5Q1tgIaHieRUDe+ugOzNJcARUeifr/2GdHAvUD1gJo
            A9vS1hsEqLW+nNq79tP2L/AgKWgI9+MWCCAJXcpPTi7FHqSghD54xsu6RNlFSlgP
            2dKWwENNjo3Bqk1RWmQLDb01OQLUOGjA1KPxASw=
            =CpQ6
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T12:28:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/pHJVB+8SuwAQ/+Ly5wpkc2FfY0YR0i/ROoFgBRbz+4D4qSN/qkG4zRHg3R
            KKI67wKlXb7ycsHtWPnn0qK9cWkX9+m2263w2yYt6wpbJrtBqRAxmPPbQn9n1+/9
            ISdGTtUhTC02Pyh2r2crWn8dBUAd4SMGC82IKzHtBxv4r149/qgLNu+2udjSkqsL
            sNrZJHIahvlrl+F96YmJh2XhIH80lIGvPXNKo/bv8ed2ICT6juVrRscEblAH5/6T
            LleD1dHLtW1DIBoCmY40K1qsM0vwN5lMcvOtoVSirU1cLYOrKvj3i19Y7wJLrVk4
            /mR8VLpYwz0e794qV6TxvM5gGFvs7mzqJ9fnBx+ngClManmJKaHituCQNASFXGK9
            KaBMSTcfV7QnOtcMDR/Op6tmE1wc5tw06V+vqJtTfY/mlvpHzGxqT1zoKIPZuV7Y
            SJR9WPtw52mwEh2xI9Ifyuyf5QKS2aB2QeJlAWuWsZHUnIGuKsPKbgo7DYRf4aJy
            V76SqPqJoZl+WdHNvOpwlfsiz1RqUDDsn4jUNC5V4TzHLXQcsUwuXS1+QZ+xKlZ4
            gfHl4wQYxWsxA10PdyNT00Jx101JAY1WeOsoB+sTUQlDgvAEZGhqlvtz7lfr4+qL
            P5EOzzF38k5WBvtKmDTKzxSDyeAuQj6wIVuYSnm9db5AIWPwYd51vovkJFnZwgbS
            XAHbliGg5XQPunRxzVwY2iKbWnYrfZIC6c5Iv5cPvr+rB6+9G42Ub+QN/4A6wi7O
            d4WlrtG3iuRcXXlCEJxpdfJ8KBa/WGadhKX4r7we7J4KUG5/raYh/EL3OQxl
            =+rXp
            -----END PGP MESSAGE-----
        fp: 355C11B55E83B15E5CF6366283637FAF9D7905E1
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/JEnAHZDjB7AQf+NZXpmQ7+qFvEceY/KsAOwKFru9wBkY74S4E65+fVTtWQ
            tTlVTwtmczkOsxfVGJPQuXSOS48JlB+c526Rn2mank2gqgfs3BVP2icsh63RtmTp
            BtHEnlm0Vm15SZ9d28z5jolcWdIzQ4a7d/BAGDgIIeqWotziqasQilrvagTrXa0f
            mRS1AtAzZytauMD822VdLEe92DIpAlaEa0auO/Vac8R2bcQLIQQols/1tlReighL
            tz7YVVAMpOj5a2CpnzgdvbZ6w5WefHfUkutGxuKELiP4rpRHtHZRhlloquGNO99B
            +KcihMt/6dfNIx1MJIKsvuhHE9XZtHynjWHgmapO6tJcAaYpIatU/AqSKPSi+UOM
            V0UbaOUyK1mYAK+Rh8MTQipnJUE6zWiV23EdOKYwWYQmTbfQGDAohLORvl6O7l/e
            HlcqNBkaNX9Seo5WWgfY0FbMdKDj3saiLXbDQ+4=
            =fdkC
            -----END PGP MESSAGE-----
        fp: 2A25DA15018235A6206921952730D7A70EC35190
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6220UozeaaQARAAtk/9evlCxWCDbfKg4m6z1HITc5g1cXBA202UPegZp/y+
            CBSbd8YOGztbL9HY8qzymLwKBYyxouPylTT4+vPfOeSy9Y+p7dUYVUuJx+QVDwTm
            auJsLkMFzPsX5POQuccCYvdLjO8GfjL3K6hrB7SRMbecROYt924pA1cREUg4T4jr
            ERqUsTDtbE5iuD9aM39meVPRQelquo+Y9EjO6A19tRXF8Wfm8YkT8fCiuzvytdhL
            5slQm38yL1k3FfOOjG4QsSwifCYvlL8ki9wmbGt/hRZB6kruSf843d7YMNCLhf+u
            MboJI/E2ikA1lK+oGc4T31pBkS2nAb2rTK21HAeSfXQ+Wj+H5cCSMU8x6omdpK2q
            Mo6ri0qbyeNWcH0lKnfYvPAE1d0fsaRQ5mC19Sf9yV7y/i1SRVfHWQyhN6ZQpawM
            kklLgvpHsnWUk56uDlEoUF+knbXoatcNUzia5/hyFychmusYZRw1Uuv0MoU1TmhL
            gza8zl9+RFZ61oyBBnQnUPY+vwcLv+FbDreAurRuoILAHjv2qi3uGQ6LgpxeOGuK
            cTc/0TlqFjDsiFasMJYT+wekgpzC1C/kPp3uXCTxsgFwrF4ZtDCIEjowJGIrcu+N
            /L1u6ykCSgdM9fDqZL30a9YP7Ce8lwVkSlKJu2fJkyFAUfrFhfQji1R+zUoF2kbS
            XAF0yQCmhWtiTdmNzVE9PDYVP+G35nb4fuC2No2cJSbERc4zoYEF5lRUkMk1xCCT
            s+PQzg21YG3OjBqYEJvtlIAkQ5IhQ5kCvSm9KdBz6QKyarvZYY5Dmp85Zhb7
            =GAVa
            -----END PGP MESSAGE-----
        fp: DA7B00C8ACAFED2DA7E33D1ADFA8C968E1F69B13
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx6ne7Mq17RmAQ//UMJ+8lKN5/A53KHHI8PwMoEc2UaEYfTlsqcXeQ0SMXe3
            T5I2HPaJkf9bAisUnvKMBJpBBoEJLrhx7dX1bGnBt9iFRD0fJ6Aylf3kWyC9l/N4
            PyxJRybZiKbYJ/R9qUZIEWUczeUV4tXhEzbhfLZSbpGvpOwtlphZizh1pUwZeFHM
            fuT+t1/mLR7TbRPQKQTe25kivAhtN/7cH5tghn5zjPPcNxWJ2hu9A+2KdBB89QT0
            Qf3N9irDeRz0k+FwF8OKifSN75RodSQk3fnGX4pBp/HpEHbVGSQdAKYPVpIJbZBg
            6ZJ/2oV+ywoCSOwgwUbIsfCFG5TAApEvX3hqk10GOlpA9eHpFVNWbuhZIA9EcIvg
            YB+utHINrCjBF25f+YoMGnh3M0gnUQMZB3pr7PTuXl99AkeitqwPNIH1fsObvomZ
            sxkeZGVOiQc+UTXOEoGcii1AE5SgfUMgY9Z9YJudRSrjQobAbtV81YLHDUbJLfhb
            1fVsBnOMhzfnseCRj9JCmbo9XZsTDU8bKUK0QYdqqRcxtEXmwnwcW2FGxVayDedZ
            0FMt8WAODoEkgqqvpFo8K5SutUfn78DrJtyy002u2X4wT6/63dX4h68+Zxc64N5N
            cVdyo4zrjbq8OxkEjUnA7nF9ek+p64yWex+n2Q5QLgZpFINYHNb9ACmKnRJ86CrS
            XAH6NMKEifsdQek2bXbypftQ85lAETZO+ccJ44XRM55fFDSNSTlRTZqhMy1ti3Xg
            dWH2QG6q9yIMg6GWNGGqnDQlFmPaXGrPWZNBOhO68QHCMHlWPwmg/Ju2Z7Us
            =jH4K
            -----END PGP MESSAGE-----
        fp: 911B366FD384B2CF3BCAE8EE01F9B7BD00DCD57B
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75NWiDtWcDHAQ/+KUB1bOmmsrbSbp3DELlvQGpCLlx86mtMgvQjHG9iKrv6
            qc+/J+RYmJpw0XpLjoZyA6Bcy9avEeedd/UEJ+0zItbQsZwwnVZ+p+zPD0BW93ws
            xUjqdBNd+jVk8DQSd5ztP9AKt7Dou0mQuNKIFXmYKqw2Cs5DKWt2JjMcjcCqckpt
            lALRdapTQAXCkKVUtJJ7uz76jhMmwNekch6ZZTojN0O/Wf9WHDYay37BYb7KYijo
            4We7/JyBIL3MKm9Z4o6FCRfsV2MqI0t3FesNK0HqhcpyzZs4lWT/YV6WW+23zAeZ
            uwIJ/iF3pHpqB+NylgPZj7qbssprrlSEYBlB6V4yHmv8GvsR6VK3dGPVgi+JtkDq
            sChiXnAEIH6XLS34G/bPPJsZOB5vQ42h+RcK3opplrbPHyFsyagELGzxNso2Z5dv
            L/iGbEjqQucOmb83PJINCA7nweXpXR4SNXP/c9Si3p2sl7IxMLs2tzmwm508uwFa
            NgewXgM/2BjDhPCv6tfad8Dnx1DBegpJQr/KrWYwTJh+JWoHrzxkGDAV6EnsxQ5G
            MT8Phg812Z7Z+ro65YBYoqEPOz3zpFFc9ca1DeWcgZXGuwGUUeaGOoamwVSFgNCG
            t55ZuwFAt7ISj/j22/Irxp5pw8Ukx5/4AKafDOk4o/OTDrdIf+sYAZeRT764sufS
            XAGUVC1yhI2fswv4k2EQI3URDUIFAMAa1q1CP4DXXD5DOqkqP7kt9ysyrsJgwaml
            mTSjrr5gtpPy00ugxVBcOeXpiFEQXJ7maxxr9UsMCVNBRtG9yn/YFyaMf+/K
            =qdR8
            -----END PGP MESSAGE-----
        fp: 4A4B9A8F518CD36766AF86DE065BDAD92D70F679
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/haI43zIlNcAQwAiQNR2nmi9q/7gnkaMFWN4qsvSr5EAS2ZGRrLRVygk5Yy
            OF0U1jpKrg6K86ffVeT7McEHXQSONAJOPmWGyeNQeuz5GxvhKMCIzjr5/b+/0rfq
            kiB4dn11GSZRTNUu/oWZ87wdG8jDoZiX8WEYS3kKXRWX847QSBcT4ndVGVe92vGF
            pOddZV/TgkORyW/inthIfFwPwChylDdKENBZbtD0VFK10vutVyMuZ5ygaAUrwVBm
            QWE4CFuDuWp2jnGsr6p8VkGgl3s3+9H4T3LyZLBWU5AaaKNBj+D+aUT/ZwJcgub7
            KMsjvR7SXEe08rQlTPkLR1BshnURER+a5vhEIDgMKvEzS9pF1/lDi1lU3arZzS8v
            7yGAyYlSu2hnIXglfcTXIh5ODODcglhjWYAfAuvrjXcP68quQjGoU7IQ4T5Fhey8
            m6CtaeD42Kma+1sQG6tagLOa0yWaJ6md90/j106fTQH3gNtZL3X9BAavG43xqSJ/
            VohgSJdSmr5IbrJIT+M90lwBpTUeMf5NPrtM4Hk6zNL7kN1fF1TvglCcs/jDAp9K
            GcLZWHb3q4UTrW+cIE+oR43DAaYfyX/I4h+rtNdWblqmCGehmAWXGWfA8qgpdkeE
            KEBblEvcXavdRR6FiQ==
            =nZ/H
            -----END PGP MESSAGE-----
        fp: 6B9CB4956CDDD0599A518BA6CFF195C6AE9E4939
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQf9ELqvJ2QwKKphBJvISs0gMu1Q7IcUtJe3VuQEi1zmOqxr
            zoiGrH5ZAuiIveuTiGyBy5jx3MFCka/LVhVg6G7d7Z3rrzaend8YIIchDGyV1lyR
            YTcVnabliH0VtC4Npdn6l0yZ/qqnYin1xYCHkelOpBZixLp63ENBbWZjD27E8KA0
            YVle7l9jlHQX4I6MQKFGn7+nrJqbg/3yOSRGbowxXbg+8lOddILnYuLrzjddzT9+
            QTrWzayup4PTvvYTjs+79XGPycTNQKKdqB7JztP1jfRLUkQoJOwJpAshCtyqw4hn
            gS6PWK6jhp4/OTwHEd6ONkMT/IxLdhd6i9ilSmf8SdJcAVuaDT5TPTZkrpYbGjdG
            fXQ1FyGQYGZwp/iQO7jN0dHOKJeRRhqx7Z9R2iu+k2Vmb5P3Ak/RpersjIjUB7jd
            ptfHiTyNpYJxKtSYHJOaTl5sz0isv75zFHKICSI=
            =OmbY
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T13:51:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0ZhTnV170YBAQwAppJyTyCfrzDFwrZneEEZbT2PVxt63/jMgrVbsCZKPpb7
            84o7E/JQ8uRBCxA0mtAUQWjLL57h1IU8RoIJH0Qgv0o0futoAOM1RIEjLePUXshy
            aoIV3D9DcfAtAtW4DZBioa7DPOiAlXALigaplxLF+2vu5r+VdmEtCakJ7XgsVo+e
            /OrMm3eOvCfpVcYOoa82Q/B9kbxo6JsGnnlz/WdmiGKTr3ItnV2RqHWR09PtRIeG
            x1edMRTIZANXk41APZNMT3Oc4tZEqWOXfRcxbZVOduuUIej0nLhLrGj2KUVJxlBk
            vqfaEDt8U22Si+OTjF0JU53z1ZtEQrxnQzABHDTVUWuK6IatvH2An/ugxYz5yBev
            jBo5s+OVYNSEJaAPDch214084g0gRjL1sXSqvaP3pQWWzai1ZzOSbfgcVLwrOj0F
            QaS99We6+pstnHke7PcvK1Q100gIY3pIIZJURD7zLPBChE2PxpkLB92MFh5uddFH
            d2PdoSbO72PiWqdF+3tt0lwBfL9q5p/sWkgAIFZa+z58H+vkXP8TEDL4In/aDIOl
            D1QLlhZJkiNTSiXyiEev9ssXlJEE8WGn1mHe66DiFEdb5fWssfXrQfiHTbIV/FUe
            AW4pkl5L5U7TfRAbnQ==
            =qD9M
            -----END PGP MESSAGE-----
        fp: CC69D686B0FCFF3B5C2147AD8AFEC23AB1EB36A3
    unencrypted_regex: ^(implementer)$
    version: 3.6.1
