tssc-config:
    global-defaults:
        container-registries:
            registry.redhat.io:
                password: ENC[AES256_GCM,data:HtKfiFn8aOZM3WSygJy9Kx60BiHfZfQdhjmf8SoGeqX/y3PCHo0uNUuoJ2NFoSaM5JDgZs9D+6ORejB4DveXVKQ4gEjsC3seCuO2UA3eDuwyGMZP/eoQZv9n61aEPw7RKQplFNkWicAwf/kcDDyYe4H0U18cG6fN4GJoqEIlWxUSGScsNi+n95n8PST2hQECxU4BolnPJPAxX40cfzLcPBIUDaccJwxX5YNPsqUL75Hs6kU8y5tzpGaAi6DUZSEozgz8n9NEYHX7T17TnXLdYrgH4LjNV9e38mA4heAlQU2nQq6jZPjyB19idKd8rFBskU3bNSVs2ca2zLe2wxzExkzdBug8gZfF+4vPGAuVsBlU1oz0KSBrTgLof26A4ba954BfNeDi5mQ0zXGlSQhOJULAUcnoImic66mjX3d9yzY7XfR+zqlEi3TmUHNf+3H/pXE4qGCnm7pGEMNVTZHUb/Rs7nF+2DB53i2nI3dbWD1Y0SrLXJ71cNg9Gw8WemYNJnYEc4IOQ+mUOZeSuD9e0J27vg4EDUqbHKIV4xVHY2xhI+onQoeS8Xn6XV9DAjAlceWrP+pNVSzCMEMUFUJlB3F7fh4JdIiz1UD/UF4mjsdZX2MmLtkuWLqFo6CZJDyS4/UpYAqrX4gRpCu19jwqPY+y0sxu0UZU9f54Sw4lqZbycS577rhUWXtMFHuwM+/rcDWt844ssoXMhfAGggJBMgv7p3hHVbjH8COz3VcmDF17QpfJMfWSgsL2Xk7Srm4190EbIi3jIThHbBGrKvgZGukpIfCJy5/IOFtQ0OZipCfSaSh14oDdiXEqI2Xer6fY23zWp/KNcqMYUg8tS+NCpHV5AXu8Xi3cdyrGbrmcFuWkXpJHfJXK601TFPT/XKj1fv/f01Xel8Dl+RrTnY2d0eozTv9T8Tcqc01Ab3wATpDZbJjFV7GYiaG7cAchzpjoZClPZCZqfiiLa0KfdovQb86hoytNWWBlV35OaV9iukDhKQsQCE5H0UE=,iv:93KcZ3bxvwzE7O6nFFSs9vT7o6XpgoayrLu6dE5X7TE=,tag:2PkeHD53ETfFhlzdemDZSg==,type:str]
            quay-quay-enterprise.apps.tssc.rht-set.com:
                password: ENC[AES256_GCM,data:h0gJJH24p2rPgkWTmhMVttxBxm+Gul8JI1UXZyjpXzxJ5vwADQO7LzDFl1ZJ+EmfWIhCvFHTX2hXDa2A01qDMQ==,iv:mR8l22fGvXhshcw7/xDIYpTulWSpYPWSj6RO3hmIgqk=,tag:i3ch0Ibi3UIP7RKr0ZX5Jw==,type:str]
        maven-servers:
            internal-mirror:
                password: ENC[AES256_GCM,data:44yBL7kZa9MMDSnf+bfbadgT,iv:+RAq6DyV0SoIuZnl4FLs7RffTBXkX1epmimJFrPjd1I=,tag:01lX20SxnFnjZYSh4GnCEw==,type:str]
    tag-source:
    -   implementer: Git
        config:
            password: ENC[AES256_GCM,data:vB9oDQVVrY0J7kTM,iv:toZfJoC1YD0ITJLyNDMNfjNwmvGKen9uW4482EdHS+Y=,tag:fiyeXoJ8KSWOlwMjKzHkiw==,type:str]
    static-code-analysis:
    -   implementer: SonarQube
        config:
            password: ENC[AES256_GCM,data:bcuFOO4RJnoEECf634/UVzfS,iv:8gQcDymaM1vEShKnqj+T5piN3WhD0o+hH0vsa9S+o3M=,tag:dnz5OqQPjg0JFxCh6bZIaw==,type:str]
    deploy:
    -   implementer: ArgoCD
        config:
            git-password: ENC[AES256_GCM,data:unWLu/2Y/d5dhqL6,iv:SLrnc2qH2P6n4hhEIOh5XC3MyX7wxuUswHMvSJglVq8=,tag:6QcneuGvlIx56xppWfauBQ==,type:str]
            argocd-password: ENC[AES256_GCM,data:i0oSyzkU,iv:th7hP+6NseHk27537wS98XBe/kQta1m2jnnxHcHozHg=,tag:kvLPCBesEhniCqTpiyMJrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-30T21:53:37Z'
    mac: ENC[AES256_GCM,data:STbnDgQ21BKR8DnmJRqYmjyMWwlaqZINYmH9Fv5QUM+M54nxcmWtvcf/eYGwNrMnLGEDDrgBNJZ7R+PZiI8gaOKMLxdvd/jx5zHz8I7biH5GkIjRdkwsBH6xU+5AnuCqg2mf5PValB+kJjDjyqgym7Uvz6Lf90rxsHWqBNbsgug=,iv:rDnh3jQp06PAoMC9i6DEdZsLCjr5HYFOxNPUe9AHt5U=,tag:paUwIKoYurFvcZVY38OioQ==,type:str]
    pgp:
    -   created_at: '2020-09-28T12:23:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQf8CjTiQee/YjKY3RBl6zvXrQsE0oUrRupV+X937FoVx3bR
            ieCIZNf9Hjc9OU5xoGNasjalWCIJ5p5/XDpTqic8cMf+a++k1Ud5e8zLa6zVPLXo
            NgbSx76bHeQEkcZoAhyQM1dJSUDUTI8MUQzUN93jkdhrfkhmMPt5SKLNwSsZ/fkw
            L1pFSvAtWfP3Msz2+QqalKVndXx879dyT5J4tNscguyiMEGV3AE1jqKzPOnLgbZ5
            3s066iZHygE/wli3ySNGaZ6MVF+zGEDoC5kfZVKTw0zee4qdcv/txiaMACqbXU2P
            9b17zpeevO/Wbm/FLinW38NtrLIQkLd8zTtXoK+jCdJeAVvTHjw2azvcXdoantgw
            2+48sWf9gQf0ARuCEk5b5rbjSkkQziCtVaqlm9xfwk90FlYWLIrqdp2V6/twtdyI
            G+xCt8/Y4ABUq+lMj3BUjjlBRaOcBNGyz1xXBPs1ZA==
            =1eL9
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T12:28:18Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/pHJVB+8SuwAQ/+OYMUt78221wVDQGvYcLITmsU9Jj2RzaDlNWRUS8bExxp
            krHF5B9K0YrDutErV4PBvdyUQcyNfpg8EdveqWjeguRG3r3z0r6BZAtZjQiyN9wL
            rJNLI5G4Lk1bT2W3w0IXa/Y8NNy69DGnAfsaGITRtZjZNTBbkGH5qPaDO0Uy7vPm
            q5yTK2G+PbVmbdYTZsooOpgVfM8UKbkbkt1DtTqDrjrDHHtU/auo0ytRAj+L9pXo
            czuDoYnjL9FVltVivzZmmi/K9m33+9NYU/t2PJ4DkvnCUQoSBHmlK6cOxo1aW8UT
            fGO8QiWv5N277mg8fpvtKwtXxTV0gmcsPA3mQ8k6nOcnCgeI71Eo/cDjzKCBQemK
            mAur9IhFYTXk/7kwTP6ZADGYe3r7/61a/iuxOMxRrLGGaaqLQOdbBz6UrcHC4CFM
            q3ytevL/2VxIfu8nKQ+mHVtjCEF+WdPHjYnyQkY8NMQ5gLPjzah408OjZNftV1OR
            ukX6IdzQA1TUXOK4HCmAHP+GbIls+IdToh6dNymoIAUPmaUEMVZYgFBaZ1F9tJag
            HbIv0YkwEDLvGpnG/6Qr7yLp8EGZW2Igl4BEz6DO5FxzWFzxbLLXHMErQgTVBGnZ
            lxIJBPcewEM76ZI1DsC62WHPEkeuw6sUl+AGV+aUpCRSj91ctaH+aiY1owOo3iLS
            XgHN69G4tWbb0tlRlEV9pWluE5K3dQnXYF4VkCGjId4Rrj9nrkaT9G7oLzsoZrGr
            iC+u819XrKb/E8JNgrhTvxdvXmgCm6AuO0Xt0rVLClNmI6zU0EG3jAZQsTBWbUs=
            =7cXG
            -----END PGP MESSAGE-----
        fp: 355C11B55E83B15E5CF6366283637FAF9D7905E1
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/JEnAHZDjB7AQf9HkBl2EJO8owne/kyEa6kst0xOKK6FKKPi/SKNwnmvPd+
            XWOqxWQJowDZ5nxffaUOZrGeGl0Qtkls2NCOfy31bfuz4eEKVr2nEQMfVgqegaQ+
            e0tvgO5yoGw23Q3Cq7dxRykM+bm8HlJ7pfvLRVAqZlgVg5CbR0nZwqjJzo2VX3Tc
            /Vgt3WWdYGuUuY6D2m3js77SP7dAa/yh+KE5bbolf7rcIzRZ2JyMy6+qjdK4I7bC
            XhFU21giTiYE0vZHUYQMhICsBQdiSaviUcPE7Q403ZBpHLdmJOpJee5okLRik6OL
            v+KOvicQYnuIqJ5phshozSAgDvVlVxSM9AZtTh1sOtJeARtqn4fAR4Gq6ExgTjSP
            elP2Vbsv3QjBuSNw5+ugQvV5DAFrE9esbGq59fGVZ8aceIS371HI8AbkXzlrWZWH
            CROiFI3O1587XXmVyKZxQnoVMVfKu2tN8m4Odf0/lg==
            =cszq
            -----END PGP MESSAGE-----
        fp: 2A25DA15018235A6206921952730D7A70EC35190
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6220UozeaaQAQ//RmrQN76HzwdFDNsPIfkwUm1mBrhbOpr4lH3PBNdamjDa
            Yt/VTpNxZDzOw/2j/B4RIeGIBMHqhzCtcJeKVTOPrbV6mS07XrZ5Jxtx98g4CMFs
            3xyLgovhT8Dypdavueqhc6z06ioZFKZ5KyujlIuWxHG2p0PEJwX3q/veTM4e9DLK
            BjbOqCrqlUEDn8ni1K6bBlK6wGWVIfJiCLvJ3x370Sx89vWm0z9N78Q1p5l4DeDD
            g4nHMN+2Jh6OvpamI+oCW40JMjc5mC60dD/YZ4TwSkA4P9HrYJPxIsUIoQVw/KPs
            ViqyrcWGGUxixWyP5sfH4qIbroXTSpfHf7vG8NQa8dKMPjPeUQMQGdjJaHHcQVgf
            qCqAGSKF4kulAsDM0LSTr1ffFgTAArHXLnoqol2oDCxPX8gB5OnhrcKt+CdWO9V3
            RLVXlrVe4XyC75HdNqrC/zCCz81L2uy/ZUt+GiYZk2nVVQhNAXcVENI/isQFMkA2
            knkFu0o/sgTwQYsgfnsx4xrk/pPl4NMeqMhEPTu61b7wz8mJNlr/EQArBffun0JD
            6WtuUCMx0XE8i1LCwh6BJOacE3KBCR5j69XSWZ/M2h1c9pxLfWLpa4FaFtXzAH7G
            KOWx1AViWTKwhmT8oRcVB0Jhaus2FOm6VK5Q5AQwsHJEJXSnT5KuITK8vLufuyXS
            XgFZw90KNpWd3TkY7vTWhJyNHUXJHmPcTXcifZdV+hR54YDREBOYMaPqME3U1X8k
            SSLTJAMOchpN/VhJddqTgOuRXoPkQ4xMmdcbiBV8z0JRFNZjwy/UIIVYF0ydD1k=
            =J4I5
            -----END PGP MESSAGE-----
        fp: DA7B00C8ACAFED2DA7E33D1ADFA8C968E1F69B13
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx6ne7Mq17RmARAAn16aVmUpCvCjni23mFx+c7eqtHiOAirN4kjiNFZ5PjVQ
            HBxy0csggKUS6uMeTVZj6W44SsDSP0KzWp0YAoKxt+ahXcBl+4d/XVh5JMyvRqNw
            4s9t8EtrFHuuktIRGAA3/qYg83R79ydHCxj9aqYJzr38gCHWW7zm3eST+ZLa+ExL
            8Vay/TKd7sgJOQfxsfCbiHR34T5CXknX6i0/g5b1LXWim2RG9HEOlojg6Nciwacb
            n7aQG29fhFtLuXCS9TWcpawMh+577CGt4STO008JH5IcFlMSUonTlqfh+CSHGbcd
            uXoP8Xr57+hi3yoe072uuVEwnHKp42yd2zSeNAUoKpMoU3+aLpXXLBGgBXiKRVxZ
            TOgT0KoDNIQnc7rKu2zmLtcM2k2FgpC+YlxLR4yJ/7tt8A326nDWO6nY9ssjhCFE
            u3/7/MHM+w72OdBQbb9qb//pJ6b2Ct1QBbeRJLHcNjU3LXdp6X8iZ7SA8AwyWRik
            xtG5iTwMtWaIN3w1mLb219W9662rCaw0ifq4HIZXQMLOEmCuj4Fae3EN/bwdLB+B
            SJGar+yQ2uSO+EnT7HNBdSafub+aKleQakOTLouQmWWyBlBCzwWr+j8/aaH4CQTB
            tNDWDyDJgvDr0dJywOnP9kE56fvk6RXXhPLFEIMMU5rgZ5+WkTZFHHq33+EbeJvS
            XgHZXWj1LYJYyLRzcv8NI3Y+7shYZbezqzYccq9PdCIsqBmF5xAv4ZBoXITUojjf
            SEOPbSvIzImYtHs9stU/GgyoVKScUTBhzOSgMdEx9n+pCDRw6u/RO5NpYxPNgtI=
            =y9lV
            -----END PGP MESSAGE-----
        fp: 911B366FD384B2CF3BCAE8EE01F9B7BD00DCD57B
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75NWiDtWcDHAQ/8CT45prcjTKQmO/DkupJcJshzAjFvZWnCRPhBFlKAe8Sv
            UYj+PhDAPwpXI+Jtsw9SVED8WggOKZzSOwVbxeqNxTOcQ/MUrx0ELoQ6vOD8x879
            ZwUgF2Jzt6UfGKi4lF7Wn0CyxU17xNffWmyOO2Jz7P/0/G8qhZlkevrJCXmiSpXu
            IiFPijrE+dbyOPp/O+I40W6TGFk/OYXbq3HCg9YR6KY1f0Zl6emkygDlm4UYJcRg
            u0H17BodqG6oQInPqKManzTzlDUWQ1/e3ThzGEMJlBSn9bs7XwJwx0cHRElULpuw
            pwv6QbfcjUlR7MyQ5ul9pWeYYnD/tYNEMdUOyzGlrMXUaRo7RoY5sYzefOu/hv7W
            L3f80LnPgrpgDEullF6tNP7Ls0QjE0JJaJWjZ3fibDnBk/BAz72i+NVvgMpkQRd8
            A9zw1QO3VZsARYWtpgxIj8LVQ6tl5Aaaf/AC9hUZkz/OWRxkmEYJAsoI59o+Pz5J
            UKrAcgxtX4zq46MydM7/q07+EYJ9dTegYZmJhG7jRtmvG8zyYeyQCDE564HBWity
            sCE/nXzJQ+TVPZ51kXBUNPIzi85x7sSmdhhdAJARAKUaU6GQzTdwUp3XVULXXMgd
            xatqicwl6HrBl3cfIbLRZTS5v318tWfh0aJdkrgjSb3FvToxY+qRzHeZErEk6SnS
            XgFT7v3vxzlaRttvQBqKLGc1+jGfQ3O84yjYFDLIwUcs8aHgVXq/ohoTLaL7JU0L
            rKKNPiTlIdRLNeWrECJzj1TnNJd+BePGDJHwIF7Gk/yGhWC6b5kpxODPlN614oc=
            =GGy+
            -----END PGP MESSAGE-----
        fp: 4A4B9A8F518CD36766AF86DE065BDAD92D70F679
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA/haI43zIlNcAQv+LBCMD/1rqBD1bDhAi+9cj3xBuEB/oeIOlFDwMn26e1qu
            h55wx3uXCrXEIpDSbmXvfwhMmkKpY3bvwovAigYWz1xkQXktwTcmr0cng5nIzXJX
            8tW2gpVeOJUE2pKYAXXkDP5uh97oR18WLZvz1hpv1fQFRV+cptiwog8RRPosDA56
            il5PmAtk6Ib6wogAutau6sjGTD28Yv7hBLTQiwfEmxRBE5/4oU/4jo5ZvesJ7YdC
            PhHhjemIZUxTvkCZV65NbPvDRC232K9/losvk7FUCvwptxTKnGXa7VL+grtS1Qhq
            5PzMwcZokO33wKZXUTKkUNZe/50NA4Omhbns/r8+K6J0F3dybEVQVCC3ITfH2pyJ
            vMUY4xlknV89BGdV9eiyF2ceY25ODUAINr5miMvvByRGFpxwLb1rtMAtdwDg/9Ox
            fZAZ8Y40iJ6dSPwKHy2yERgqpZIg+rK8Tq2ZnCKOi/OVquM57aN7QcM27hcfN3ku
            HCXMHfCM5HAC8H/8PMb40l4BwnhhWGtnomOFcazVQI9NrjQHtWITGumxr2iXq0DG
            sShWpoDZA7I40YykXp9XurooDdcwTUFJAwIP/YJ8F9gpsRxEduogAUrlYg6W4m8E
            NMkSZ58ONSsUlkfNjCo8
            =qWIL
            -----END PGP MESSAGE-----
        fp: 6B9CB4956CDDD0599A518BA6CFF195C6AE9E4939
    -   created_at: '2020-09-28T12:53:08Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA3GO6GKnGxytAQf7Bwl6uOV7+geUHWxlYRbQjLKvkkm9Hjt98ZYXJtXpP2/Q
            RpiGZWfGNYqDa6Jh3sM8QeDs83ZhYbYn6zdXh+tOrbVqzrbN+3s6uIsuU7l6Qn9+
            PvrYY/LMpoVtVVA0r4gVO8KA3YxP9isPkLtYIVchcVEuDjhMkWdfM3vWUKBM1Oi+
            Tc+li1MTTHkUuhazSGWQi8udffJ1PmKaO/pg24fispkc8q/d98bvURQmnTCmf5HX
            LBtwYUQ7YdRTQcoMF2PQMy9ERxdhb4JA2Ukha0Uxzm+u5bOLNSq9wl0uq7lGSVaT
            CObi1EnYhNjYx9lhiqs6flTcVH/fzoM8IvZQWnZF0tJeAa5KE84riGiq/rUrvCBR
            ZPH6YdKtLegL+tdqNO+gZkRZ4LWrTKOCsJsiIoty8+5SIwBXl62KRMhykwXCBH1N
            T4pqVdrTHWJKiXwGqbJIC3A7Pxew4HENN57SJBjhEQ==
            =NN/v
            -----END PGP MESSAGE-----
        fp: 7EFB417E546C45EE36EE43F0DD2047E4342B2EBA
    -   created_at: '2020-09-28T13:51:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA0ZhTnV170YBAQv8CulyWeaQ53YSBsTHO2l+uaTf7m5BLbRWrLplIcrVqBqg
            prj36pi+A8ZFdvt9Y+ziHuNOvXmmIa4fkOoDjiuQWItpzew6Zb+Wlqg26rgp3+kv
            ZV38fJ4gBJuihzL3/Bzr1A24t+gSXxuxijMzTQbNrJQyjhwP0DlFvsnLKxNNqFk0
            M6BTtmL0JPqxus1vPTE2vLe3JMdtyRjef1iJIEJDhgfZcujUwCK4SPX8/1XQGAJM
            onl7NYBCritMWgk2aFuqzp1bgJBtudYqm0v9XxuZkjl7dxSzNfB4+bULJEAWQpmS
            Zqve8zwFL5psN5Z886z76fNw2GyZg2XV11a1b1iXrOkyLzInjRRFwKzoRgs3FVOY
            M7FuML4IdYZRS/HhiFcs/DJBTPCUhqOl4QCs/uvyr8HZGN+HCyKHpJkOXFAl+/s8
            KqTDvHXtDo8MmwaLC1mH8+Cqko7Se3WW9NXnCp+EwJPDySq5cGyyX65zeuWLSKa8
            aJNXWF7ahSwUhp10BC7F0l4BCSABGws9TLckDMwyd7wgOsX3aZrl4rbvmBSLyhyB
            WpuRT7XAaSlmFuW6cPu1l+ddvJZsiv6fjZp8wnQlI/5dWQ95JAZKgOdG4tKHEJZO
            jmlAIjJVdfIdjl+xwYgr
            =/EaN
            -----END PGP MESSAGE-----
        fp: CC69D686B0FCFF3B5C2147AD8AFEC23AB1EB36A3
    unencrypted_regex: ^(implementer)$
    version: 3.6.1
