tssc-config:
    global-defaults:
        container-registries:
            registry.redhat.io:
                password: ENC[AES256_GCM,data:cd+TzqkvYC/ELofSkgjEuUAD4TQw0wEkGrcu4mlqqeHR5gRnRhYjkLKaUVw0XcxcBdhdSXc/gP6pDfAKnd4MvlTMz7x8GN+AngzUcJ5eiN2ONBy95+n7FN8qYMO7ltUIRMKRLvUrblrgDskNADT8C+WiLPQ0gYaTjozE7XHH8jEG1QwxW6LbYsoGhFRvExBu3ohq+713LecW9UWhBHZ/JBtjDcdpRlBbC+cokzo0BlSDlTKgb7Lv+CjiA5GmnYzBqDpOSJew2DGl9B3VAhpWWysfxUYBP3VT090hs48zXxaq5nIwiJ725g4BoQXaZYTSjyZInEwmMxGM5SnlJG/W5VZ8SmMLeCijeLGBuHx7zdAzNnk0YM5xPN3jB+x3vPVqI9JGY4R9svgMAvD8jWKEqhpyDlZM60jaXwFuik0pC4DwiC3QVoebj12ZZquaKA8W9KX1PM8U+XhOYtrH+dlnA7JpUnood9R9w4lzNeEFigWO4OcSAa+qGWwfIa1cjIp0UKWwo2gI8svGQdPzLz57IoCqbmvGAw3T/Yv6AXT2Y2NCAXxCqQdbFj8XqMZHDknlDwGiLU8hBjYKneoSb53jF/wV8BlXle7IeQdx2GGBW9S0c/kw5UP+DBd4Yf1SF14+xH4QWPPIwdFkE6JEuRi7tGe0S2h4HI6r0oSMTx6oDmo7uNT7y42x1QlQRs5L3vmtLZ5FKjQmsjJmFQhXiPULF1P+d5BvmzU9c5QJi9BtDmwd8auI9RUmLDzAg8/UBDg0sX8sWg1I9YHBgs8tRwv5CZgtRfhZRpGueJMSeJQNrh3WDNFOeOc5uzXSp4jINFOvJhcprIG0Ra2gzHCJo+/3qKKeBY5aZUutD3u6n1WjPNhgBNwK5QuuR9YsWWUarirF92cwVsDvtbVvZoYo+VHOFB2L+JcwIpiIrjI2cN+rZAvtpQfVhCXwQi+h7QMjRS/O+WbwXR/g5ZYWmBHQmQ4FXjOcEzfHOCPpMp/6Xt4E/dLSREhFqF/oI24=,iv:0TVntM+JilSW8z0OeZjq7OAeW6D7A+kHbNr3dYMhjC8=,tag:5VC0oGTJSKVeD6CUPk+bsg==,type:str]
            quay-quay-enterprise.apps.tssc.rht-set.com:
                password: ENC[AES256_GCM,data:t8UfttGh+TID8rppyYibJP/9841n8c66Gyfky+kGfkg28wtGEb0SniSMeVV2t1F+uyULTf7gZfsJKkWsh3IHLA==,iv:olNwlkYXECCrIxnbXYFMAIKjVv2OfJbZd91bQxFbKnU=,tag:75vkRsdpJUTPd2DbKqjHpw==,type:str]
        maven-servers:
        -   id: ENC[AES256_GCM,data:8+ISwn/LvTiUza+l6P5D,iv:WDZcbQiaYWfJIsPFiLZrffe52rR8dyjEgjgdoEHni6w=,tag:7cX4tyKLNmtObudy0vJx9w==,type:str]
            username: ENC[AES256_GCM,data:suqfnw==,iv:jgPTUcBIG7zuv8Kiu+DlxsGMbYowu0O22mIL1SVJDW4=,tag:VNIqZLkVrq0uPe7zeQXfRQ==,type:str]
            password: ENC[AES256_GCM,data:H1GOgLOHNDsiPK8comvxXTzc,iv:JNDRO60KQmi7Ee8GQiGscXHJptYSugrmpWtSD5xCa94=,tag:iNyGV4in3w3tkO2GeTqbIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-25T13:54:27Z'
    mac: ENC[AES256_GCM,data:DOrJlVh20E9VzWedQBoCHBwF4CMUQtWOGZ609ISREN4Z0cGmi5QvpLCifmONC5bcqGx/u6foPTVMlN96Onzao2trsSH0pN0RooL3uw6STfHfrvW8kYCOO9eAVSyrG6g7r6MQuSryKKgCsc3poh8R2XBgXKl24aYuVrlft3EHGLs=,iv:xEOML4P0S79ctF0IrKjTDyMC8JMMjPUfCvf7nuaYnpc=,tag:Tucujvo1bTWbvwVek8K2oA==,type:str]
    pgp:
    -   created_at: '2020-09-25T13:20:47Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6220UozeaaQARAAkVIfxqfIPce8sDOrH74i4GRWZXCCVa3eO0YIcAXZMTr2
            TxfY3GALlFvNDaUb1I1Yz04C5g91SUeV0RdF4OSvkB/WyAmOtcMKN8524sPeMTAs
            8gZwxqRkCnsvv7J+bmEUSd4PCIFstcbuLd4AH+DjuuW2C9vFsot7ESgx0u7tvT2f
            JaDN3HgaypVHtd/JfuKSM5iFfnUDQtO46fTx2CvscUfaFNSrKfHezZTK2e+C6OdC
            eSaA11D73Trq/NP2muIzxY1iSXI/bqLhtfE9QDmuYL7ho6lh45oPe+9E2QRmVaci
            n9CIUED1FoynkOtydTkfba1rr99g20OB4rCdMhJsekIT/swxX+do9mC/37c6TGgx
            qks3ELKCReghpnwnOIlwuWoGYcO03Sd11uEJMCkUvFyY8kfs+J2ThJjHRczh374G
            aDZk6vErBgcLwhdjDiv3u7xbWA8EL2gMFg0WXruNv1q07qRKUCpSHNPsV3j3dzIw
            YzIyZZGxkjVsqdu47b89UeCfGFggsxzakaeRzByk23AnMYzaoRb80De0iS010u8j
            aL/rydHlibhH09BNXUiSwOsVMEVSMxZoIwPKvQYPKyeoS45Hwx1aExOiZD3VF4kO
            n4O3mSdTQ+RAvE/aeKniX4/ESUPmxkI7mrl3wDXNPK1laRoiLZVhdA8AqzFqc0TS
            XgG+JBpv22eB3VNo9Vdw9FHODYclLwR/udZaWiCjEI4JFIg2UC2sN+5gd34nEF1H
            2SLhSwtzHUI285/x2IzwscmqwSyQXM6uSy19Q53XoXFDgGMEGULFy3aVW/S3nEI=
            =fzNC
            -----END PGP MESSAGE-----
        fp: DA7B00C8ACAFED2DA7E33D1ADFA8C968E1F69B13
    -   created_at: '2020-09-25T13:36:39Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA75NWiDtWcDHAQ//e27DgFhUmZ5PzgGMEbaGPCOFAM+LKvJBC7DQ6eGdNLi3
            gGJwTTTRywwd4NfP3ByX5ts7+3k7jsCljJYWvDEr0UizU6KCJUTqvXm/ATImDCyr
            ywaADfbS4MkrnMlA2d8E7M8GtXLVQNQOR0sw77+9iV8Y6PF6dlyqEUyUrMeCLTpL
            QtXcH0JgDSnANg7XIXq/yxCWEAo9vUCeJMaufzm2mSHL+OaTp2dhMZ2qEkSqBQ40
            3Okr7xfo6BnRt1xJjxWx7qyEUoXe/uufxSUy2bbcz7UUxZoUaLTW8qWAW9HxtoOU
            lozenzTJH4X5H1oCHIshwW8W5wACRs0my4FeUzZglx4aNranRF4o6piEyDIH+zYv
            O1MKH6B65W6Xww/fP5Z2URJCJi8FI3XE+fpW3F6M7s4V88gPg6AlhEiYOim/DPsP
            MFHN9TlO/EIMsc1cD4CgNEFNRhLzumAkNTiDCn7M9V4vQ6ZVBdzoa3qMbokkBA+v
            ZEf8gf5IXcE2K7DSc18NEGeCHQZLF7yJcg2msC5RqYyrLTLAkq5WNu/i2x9jbiPh
            ZaXs3qiZpb1Bkdhsmet0rb+zTskLLM3L07t+TvByea3kgMpI1M4Ol21xC/hvI5iS
            WNVdO0efEn0FrRvUKEuU25mVWUfSL6XRK5z/UKAUjMf++UHulB9DCgWnhQDFjzTS
            XgHPO38Pbvym/atx0bOuhRaddsW58UfabuNQhhzOJqRb5T6/xTKYMYOleDibSTOs
            sI1BfJr3/SWTMzeI5x+LmwrB5sdz81pU03FIuDKCrcdeS0dPUQ46y07q6jXcJs4=
            =IygG
            -----END PGP MESSAGE-----
        fp: 4A4B9A8F518CD36766AF86DE065BDAD92D70F679
    -   created_at: '2020-09-25T13:54:26Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx6ne7Mq17RmAQ//d9iYTqHYBXY9/pOJsg/oYZLkjmYZd8ELBketvLCSTSOB
            hTBpf3Ncige07fAwiiWRMLUYxa5ad14WEqNjMfmKI1O6WV/XFxQzuW25kRYbE+/A
            3eHfw/AMnG3i+Sdp55YQoq8zt6RZEF+iOpKc0cd1zSVXmw0jcjjMVYFJ/z9sWEC0
            kfm8Pbt3YHgKCUYduQEgx5sbbUS8eJae2Rt6S7u/U65cwWJSJ4U7SJFsPAL4EOnK
            87JJu+d19ACetlORdpdv907/KAGTI0gG4OV8H9Ljj+r5cZnE8u53Bjh9i2+ovOBu
            T1IKgohxoN2HdWGe3eb37cejVNLaHEagUbdfrL0eq3K+i9pGmUfuBI8AYDN+mc/4
            dJBI91etOehX/iZWg2Evx0YudtsRq2DK/d/yhrVlMzTGeZnPZU36BZSy42rGLzcy
            Qh9S4GDG52Bdmt98ZciUYvxhJC4k/8SMxZVNGp+BR0uS7iexytTQJ15VcGgpwCsW
            yZyoMilbNXlOBNh3egdIS+zK70JI5FQ1PhEawPg9/hw02yMFkqSsnLJ1noloYAm2
            stVDqneI8B/zVD/j8hCOfezjt8yTm5nSF9kBWuY7XGftDepLaciwhLAwcqqp5uKX
            DovxO6Zm5qONVq555N3/XgLyhbU9nrkjlP22l/Kiu33oMK/MzM9ZocqyHKsZwsHS
            XgGj4sGnJrKKjpiRN7OBKn2Nh4VkYWZ88dXmQ1epen0jRbZnkq85oXPmD5112iuT
            WfkOStF9vCMKrU3YCJyuT6JrzW7LF9pi5wY7aHigCUuFkxf9UFXXVqt6oSW3KeU=
            =R6h1
            -----END PGP MESSAGE-----
        fp: 911B366FD384B2CF3BCAE8EE01F9B7BD00DCD57B
    unencrypted_suffix: _unencrypted
    version: 3.6.1
