---
tssc-config:
  config-decryptors:
  - implementer: SOPS
  global-defaults:
    service-name: backend
    application-name: ref-app-quarkus
    organization: tssc-team
    argocd-api: argocd-server-argocd.apps.tssc.rht-set.com
    maven-mirrors:
    - id: internal-mirror
      url: http://artifactory.apps.tssc.rht-set.com/artifactory/release/
      mirror-of: '*'
    container-registries:
        registry.redhat.io:
            username: 6340056|tssc-integration-infra
        quay-quay-enterprise.apps.tssc.rht-set.com:
            username: tssc-team+tssc_reference_app_quarkus_rest_json
  global-environment-defaults:
    DEV:
      kube-app-domain: dev.apps.tssc.rht-set.com
    TEST:
      kube-app-domain: test.apps.tssc.rht-set.com
    PROD:
      kube-app-domain: apps.tssc.rht-set.com
  generate-metadata:
  - implementer: Maven
  - implementer: Git
  - implementer: SemanticVersion
  tag-source:
  - implementer: Git
    config:
      username: reference-apps-sa
  unit-test:
  - implementer: Maven
    config: {
    }
  package:
  - implementer: Maven
    config: {
    }
  static-code-analysis:
  - implementer: SonarQube
    config:
      url: https://sonarqube-sonarqube.apps.tssc.rht-set.com/
      user: reference-apps-sa
  push-artifacts:
  - implementer: Maven
    config:
      maven-push-artifact-repo-id: internal-server
      maven-push-artifact-repo-url: http://artifactory.apps.tssc.rht-set.com/artifactory/tssc/
  create-container-image:
  - implementer: Buildah
    config:
      destination: localhost/tssc-reference-app-quarkus-rest-json
  push-container-image:
  - implementer: Skopeo
    config:
      source: docker-archive:backend.tar
      destination-url: quay-quay-enterprise.apps.tssc.rht-set.com
  container-image-static-compliance-scan:
  - implementer: OpenSCAP
    config:
      scap-input-file: /usr/share/xml/scap/ssg/content/ssg-jre-oval.xml
  deploy:
  - implementer: ArgoCD
    config:
      git-email: 'napsspo+tssc@redhat.com'
      helm-config-repo: http://gitea.gitea.svc.cluster.local:3000/tssc-references/tssc-reference-app-quarkus-rest-json-config.git
      num-replicas: 1
      route-enabled: true
      readiness-probe-path: /fruits
      liveness-probe-path: /fruits
      destination-url: docker://quay-quay-enterprise.apps.tssc.rht-set.com
      argocd-username: admin
      git-username: reference-apps-sa
  validate-environment-configuration:
  - implementer: ConfiglintFromArgocd
  - implementer: Configlint
    config:
      rules: cicd/ValidateEnv/
  uat:
  - implementer: Maven
    config: {
      selenium-hub-url: http://67.207.93.102:4444
    }
