// Load the TSSC Jenkins Library
library identifier: 'tssc-jenkins-library@main',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/RedHatGov/tssc-jenkins-library.git'
])

// run the pipeline
pipelineMaven(
    configDir: 'cicd/tssc/',
    credentialIDsopsPGPKey: 'sops-pgp-private-key-jenkins-tssc-references',

    jenkinsWorkersImageRegesitryURI: 'quay.io',
    jenkinsWorkersImageRepositoryName: 'tssc',
    jenkinsWorkersImageTag: 'edge',
    jenkinsWorkersImagePullPolicy: 'Always',

    updateTsscLibrary: true,
    tsscLibSourceUrl: "git+https://github.com/ploigos/ploigos-step-runner.git@v0.14.0"
)
