// Load the TSSC Jenkins Library
library identifier: 'tssc-jenkins-library@main',
retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'http://gitea.devsecops.svc.cluster.local:3000/platform/tssc-jenkins-library.git'
])

// run the pipeline
pipelineMaven(
    configDir: 'cicd/tssc/',
    credentialIDsopsPGPKey: 'sops-pgp-private-key-jenkins-tssc-references',

    jenkinsWorkersImageRegesitryURI: 'quay.io',
    jenkinsWorkersImageRepositoryName: 'tssc',
    jenkinsWorkersImageTag: 'edge',
    jenkinsWorkersImagePullPolicy: 'Always',

    updateTsscLibrary: true,
    tsscLibSourceUrl: "git+https://github.com/rhtconsulting/tssc-python-package.git@main"
)
